### ISSUE TITLE
WSDL support: issue generating request and response body

### ISSUE THREAD

**Issue by KonradMaterek** [a85/POSTMan-Chrome-Extension#10179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have encountered an issue related to generating collection from XML schema imported with WSDL link: collection is created correctly with all requests, but I have an error in the request body: 

<soap:Body>
    <error>The element or type could not be found _*request name*_</error>
</soap:Body>

I'd been using the same WSDL link with SoapUI with no issues until I read the news about WSDL support in Postman. Any help will be appreciated!

### Steps To Reproduce

1. Click 'Import' button in My Workspace.
2. Select 'Link'
3. Paste URL to WSDL.
4. Once API is added to the APIs section go to 'Define' and click 'Generate Collection'.
5. Type in a collection name and select 'API Documentation'. 
6. Click 'Generate Collection'.

Result: each request generated from schema contains an error: 
![image](https://user-images.githubusercontent.com/65237810/127687792-2acf8359-2c07-4cb8-9752-bb92d850b5f6.png)

### Environment Information

```markdown
- Operating System: macOS Catalina 10.15.7
- Platform Type: Native App
- Postman Version: 8.9.1
```

**Comment by stondini** [comment]
Same issue on my side with same Postman version.
The WSDL imports a few XSD like:
```
<wsdl:types>
  <xsd:schema targetNamespace="http://test.com/api/v5/registration" elementFormDefault="qualified">
    <xsd:import namespace="http://test.com/api/v5/registration/messages" schemaLocation="api-registration-messages-v5.xsd"/>
    <xsd:import namespace="http://test.com/api/v5/common/messages" schemaLocation="api-common-messages-v5.xsd"/>
    <xsd:import namespace="http://test.com/api/v5/common/types" schemaLocation="api-common-types-v5.xsd"/>
  </xsd:schema>
</wsdl:types>
```

Thank you,
Stephane

**Comment by VShingala** [comment]
@KonradMaterek @stondini At the moment, external imports (`<import>` tags) will not be resolved for `Import > URL` flow. As it will only import one file at the corresponding URL. Meaning the request body where these imports are used will have an error that you have reported (As they are not resolved, they are reported missing).

To successfully import schema split across multiple files that are present locally on your machine, You can use `Import > Folder` flow. Here select the folder where your main WSDL file is present.

If the above is not the issue, then can you share an actual example of where this issue is happening to debug it better?

![image](https://user-images.githubusercontent.com/16756296/127862278-73e418fc-8312-4ca7-b36e-5fdd4c02323f.png)

**Comment by KonradMaterek** [comment]
Hey @VShingala, thank you for your reply! I think the issue indeed lies in the external imports. I was able to successfully import a WSDL file and create a collection following the same steps but using a different URL (http://www.dneonline.com/calculator.asmx?WSDL). In this case, no external imports are defined in WSDL file.

Since the problematic one has the `<import>` tag as shown below, I understand that for the time being, we'll be getting the errors in the request body?
![image](https://user-images.githubusercontent.com/65237810/127911830-2a8874d9-ca62-4791-bc6e-6f76ca0c252f.png)

**Comment by stondini** [comment]
Hello @VShingala, I trried using `Import -> Folder` and I got the same result.
Please, find a full example in attachment.
[wsld-import.zip](https://github.com/postmanlabs/postman-app-support/files/6919414/wsld-import.zip)

Thank you for your help,
Stephane

**Comment by VShingala** [comment]
@KonradMaterek You're correct here. Any external imports will not be resolved currently and any place where they are used will provide an error in the request body.

@stondini It seems there is an issue with the conversion process of multi-file schema here. We are investigating the issue and will update the thread with any further information.

**Comment by KonradMaterek** [comment]
Thank you once again @VShingala, fingers crossed for having external imports supported at some point then! :)

**Comment by pranav-davar** [comment]
Hi,

In the latest release 8.12.2, release notes mentioned this bug to be fixed. But I am still seeing the same issue. I tried to import the WSDL, which contained external references and sample requests and responses show below.

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <error>The element or type could not be found undefined</error>
  </soap:Body>
</soap:Envelope>
```
Link to WSDL: https://www.crcind.com/csp/samples/SOAP.Demo.cls?WSDL

I have even tried to create local file references, still it failed. Can you please check and help?

**Comment by stondini** [comment]
Hi @cipherwizard9,

I got the same behaviour as you. It seems the release 8.12.2 doesn't fix this issue.

**Comment by VShingala** [comment]
@stondini There is a restriction while importing folder where we restrict more than one WSDL root files (By root files I mean files with `<definitions>` tag at top level). To successfully import, In files provided by you, you can try removing `registration.wsdl` and `registration-messages.xsd` from the folder and then import it.

Also if you would be fine with it, wanted to understand use-case of having 2 WSDL files or 2 XSD files which uses all elements from other. i.e. `registration.wsdl` uses all elements from `registration-common.wsdl` and `registration-messages.xsd` uses `registration-messages-common.xsd` and there is nothing apart from import mentioned in former files. As there aren't much WSDL public specification out there, we are trying to understand user reported specifications.

@cipherwizard9 There is separate issue that's present with WSDL mentioned by you. we are working on a fix for it.

**Comment by stondini** [comment]
@VShingala I don't have the hand on the WSDLs. They come from a third party provider (I've just simplifed them).
So, I don't want to change them by hand.
This [article](https://blog.postman.com/postman-now-supports-wsdl) from Postman official blog says that WSDL is supported. No restriction is mentionned.
Could you provide all the restrictions please ?

**Comment by VShingala** [comment]
@stondini No restrictions as such for single file import. But for specification split across multiple files, we only are importing one collection from one multi-file specification at a time.

So what we have built the conversion process for these WSDL specs is there should be one root document with `<definitions>` tag which will have imports/includes statements per generated collection. As I mentioned due to the lack of a real-world example of WSDL specs, we haven't seen such a specification where there are 2 root files for the same service and thus the ask to understand the potential use case. Also were you able to import a folder with 2 files not present?

**Comment by stondini** [comment]
@VShingala I tested SoapUI and it imports these WSDLs correctly.
Here the specifications: https://www.w3.org/TR/wsdl/#imports

Anyway, I will follow the Postman WSDL support improvements.
Thank you.

**Comment by soma-kurisu** [comment]
won't there be any canary release this time? current win64 canary 8.10. still does not resolve requestmessages from complex hierarchical xml type-declarations in multiple xml schema definitions; e.g.:
> - L0.wsdl
>   - L1-1.xsd
>      - L2-1.xsd
>   - L1-2.xsd
>   - L1-3.xsd

**Comment by VShingala** [comment]
@cipherwizard9 Issue mentioned by you is now fixed with the latest Postman App.

@sca-ai We have added improvements to file resolution in WSDL file using local imports in Postman app v9.1.2. Could you give it a try and let me know if you are facing issue with it?

**Comment by soma-kurisu** [comment]
@VShingala I've updated to v9.1.2 but the problem unfortunately still remains. After several different ways(*) of importing a .wsdl plus its type defining, locally referred hierarchical .xsds the API inferred raw request body always looks like: 
```
 <?xml version="1.0" encoding="utf-8"?>
 <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> 
  <soap:Body>
    <LEVEL_0_TYPE xmlns="ns://some.ns.uri/some/type">
      <types:LEVEL_1_TYPE>The element or type could not be found</types:LEVEL_1_TYPE>
    </LEVEL_0_TYPE>
  </soap:Body>
 </soap:Envelope>
```

(add *) Used Postman's API import via file and folder import.

The licensing contract for the SOAP API we use has some rather restricting clauses which prohibit me in providing you the interface vendor's .wsdl and .xsds. I'd still like to share Postman's debug logs with you. Is there a quick way to crank them up?

**Comment by VShingala** [comment]
@sca-ai We were able to identify the issue with the structure that you mentioned. [Here](https://github.com/VShingala/wsdl-specs) is a specification with a similar structure but failing to create correct elements at the moment.

Meanwhile simpler WSDL specification (no nested XSDs inside XSD) are working correctly. (i.e. [this example](https://github.com/VShingala/api-schema/tree/master/WSDL%20Folder%20example) should import fine in postman app)

We are working on the fix, but it would be also helpful if you could send us the debug logs at help@postman.com with this issue as a reference.

**Comment by pranav-davar** [comment]
@VShingala,

Thank you for the update. Now I am able to import WSDL. But as you mentioned in the above comment, there is still an issue when we have multiple nested XSDs.

**Comment by Uugsx** [comment]
hi, have you news?

**Comment by VShingala** [comment]
@Uugsx @sca-ai @cipherwizard9 We've fixed the issue mentioned in [this comment](https://github.com/postmanlabs/postman-app-support/issues/10179#issuecomment-954017894) with the latest Postman app (v9.7).

You should be now able to import multi-file WSDL specifications [like these](https://github.com/VShingala/wsdl-specs) successfully.

**Comment by Uugsx** [comment]
> @Uugsx @sca-ai @cipherwizard9 Мы исправили проблему, упомянутую в [этом комментарии](https://github.com/postmanlabs/postman-app-support/issues/10179#issuecomment-954017894) , в последней версии приложения Postman (v9.7).
> 
> Теперь вы сможете успешно импортировать многофайловые спецификации WSDL, [подобные этим .](https://github.com/VShingala/wsdl-specs)

That's not what I meant. I want to import a wsdl so that the query structure is loaded immediately (a bare array of the query). How it is done in SOAPUI. 

Now when I download the wsdl by the link, a RESPONSE MESSAGE is automatically generated for me, and not the REQUEST BODY ITSELF. 
Do the same as in SOAPUI and there will be no price for you, my colleagues and I will be ready to switch to your software.

**Comment by Uugsx** [comment]
> @Uugsx @sca-ai @cipherwizard9 We've fixed the issue mentioned in [this comment](https://github.com/postmanlabs/postman-app-support/issues/10179#issuecomment-954017894) with the latest Postman app (v9.7).
> 
> You should be now able to import multi-file WSDL specifications [like these](https://github.com/VShingala/wsdl-specs) successfully.

That's not what I meant. I want to import a wsdl so that the query structure is loaded immediately (a bare array of the query). How it is done in SOAPUI. 

Now when I download the wsdl by the link, a RESPONSE MESSAGE is automatically generated for me, and not the REQUEST BODY ITSELF. 
Do the same as in SOAPUI and there will be no price for you, my colleagues and I will be ready to switch to your software.

**Comment by VShingala** [comment]
Hey @Uugsx, I wasn't able to understand the question or issue. Could you explain a bit more on the following things?

- Is it an issue or a sort of feature request?
- If it's an issue and If possible, could you share WSDL spec or sample spec with an issue.
- In case of feature request, could you explain a bit more about what's current behavior for you and the expected behavior?

This would help us understand more about it. Thanks!

**Comment by aakashsethi20** [comment]
> You should be now able to import multi-file WSDL specifications [like these](https://github.com/VShingala/wsdl-specs) successfully.

Hi @VShingala, I'm still facing this issue locally using a link to top level WSDL in Postman 9.12. Are the multi-file WSDLs supported only through folder import?

**Comment by VShingala** [comment]
@aakashsethi20 Yes, `Import > Link` flow can only capture what's present at mentioned link and not anything other than that. At the moment, `Import > Floder` flow is the only way you can achieve multi-file imports.

**Comment by irwinindy** [comment]
I am attempting to Import a .wsdl into Postman and I am getting this error.

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <error>The element or type could not be found TestOTA_VehAvailRateRQModel</error>
  </soap:Body>
</soap:Envelope>

My scenario is as follows:
I .NET Core project with a single folder with multiple .xsd's
I have a single folder with .NET Poco's generated from the .xsd's
I have attempted to link the .wsdl for a single one of these files and I receive the error above.
I have also attempted to put the .wsdl in a single folder and import Folder
I have also attempted import the file itself.
Each time I receive the error above.
The wsdl is attached with a .txt file type as you don't support .wsdl uploads
Thanks in advance your help.
[OTA_VehAvailRateRQ.txt](https://github.com/postmanlabs/postman-app-support/files/10536618/OTA_VehAvailRateRQ.txt)

**Comment by Uugsx** [comment]
> Hey @Uugsx, I wasn't able to understand the question or issue. Could you explain a bit more on the following things?
> 
> * Is it an issue or a sort of feature request?
> * If it's an issue and If possible, could you share WSDL spec or sample spec with an issue.
> * In case of feature request, could you explain a bit more about what's current behavior for you and the expected behavior?
> 
> This would help us understand more about it. Thanks!

hi
ok

in SOAPUI program there is a button " recreates a default request from schema". which can update your xml request and pull up the default data.

You should take this program and see how it works with any soap query. 

This is something that is sorely lacking in postman

**Comment by Davebo85** [comment]
the initial issue is still present also in the last version of postman and trying to search for a solution on the web seems not to be possible.
