### ISSUE TITLE
View model schema details in rendered API documentation

### ISSUE THREAD

**Issue by br-tyler-milner** [a85/POSTMan-Chrome-Extension#10347]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

We're practicing API-first development and using Postman as the "source of truth" for all things API-related on a new project. Unfortunately, we've run into showstoppers with regard to how Postman renders documentation generated from an OpenAPI spec. Core details about an endpoint's request and response body structure are just not visible in the documentation view that Postman provides. This includes things like:
* What fields are required/optional.
* Special format considerations for fields.
* Enumeration values (when applicable).
* Descriptions of each field.

Basically, Postman's documentation seems to be missing the "schema view" for request/response bodies, which seems to be a core feature in other API tooling. For example, Swagger provides a "Schema" button that you can click, which will show a rendered view of the schema, including things like the description of each JSON property:
![image](https://user-images.githubusercontent.com/78233128/136107742-e36cf82f-1f4c-442a-b40d-b0c3d88266bf.png)

Instead, all we get in Postman's documentation is a very basic auto-generated JSON example, which does nothing to give additional context or clarity to the reader:
![image](https://user-images.githubusercontent.com/78233128/136107960-17cf7ecf-283a-417b-b06c-0aea362fde5f.png)

Sure, one can switch to the "Definition" tab and read the raw OpenAPI YAML to see the values of the `description` fields, but that is neither intuitive or user-friendly:
![image](https://user-images.githubusercontent.com/78233128/136108129-a30b2656-76b3-4f17-836c-8db4aba8ce81.png)

We spend a lot of time making sure our OpenAPI specs are complete, including descriptions and examples for each field. The fact that Postman's rendered documentation fails to even render the contents of the basic `description` field associated with each model schema is causing confusion for developers and QA and leading to rework. It's frustrating that all of the necessary details are accounted for within the OpenAPI spec itself, yet are not visible to consumers of the documentation.

### Describe the solution you'd like

Postman's rendered documentation view needs to catch up to other API platform offerings. Specifically, there needs to be the ability to view the details of a JSON body schema, as there is in tools like Swagger:
![image](https://user-images.githubusercontent.com/78233128/136108700-045b80b3-5764-4949-ac1e-75990ef6d5b3.png)

See above for other suggestions on other core documentation features that are missing (marking which fields are required/optional, enumeration values, etc.).

### Describe alternatives you've considered

Really, I only see two possibilities:
* Train everyone in the OpenAPI 3.0 specification so that they can view and understand the API from the raw OpenAPI YAML. Due to technical skills, time, and ease of use, this is simply not a feasible option.
* Switch to a different tool for all API design/documentation.

Alternate tools worth considering are:
* [Stoplight](https://stoplight.io)
* [Swagger](https://swagger.io)
* [Apiary](https://apiary.io)

### Additional context

I searched, but didn't see an issue/feature request directly related to rendering the "schema view" in Postman documentation. The closest thing I found was [this comment](https://github.com/postmanlabs/postman-app-support/issues/3117#issuecomment-619790432) in #3117, but that seemed unrelated to that issue's original topic. And, with that issue being 4+ years old, I felt this needed to be called out explicitly.

**Comment by kwolfy** [comment]
This feature is really needed

**Comment by deemeetree** [comment]
This feature is really needed! How can you even consider Postman to be a serious tool for API design if you can't properly document a schema with it? Even when I create a schema using OpenAPI in Postman, my schemas are not exported in the documentation. This is not even a feature request, it is a bug and it should be fixed.

**Comment by wcf-todd** [comment]
Please implement this feature!  We are having to go with Stoplight.io because of this lack of functionality in creating the #/Components/schemas in the generated docs.  We are using OpenAPI 3.0.3 to create our API definitions.  Also, a huge thanks to @br-tyler-milner for taking the time to fill out all of the info for this request!  I was so happy this has been logged...now I hope it will get some attention.  This is a game-stopper!

**Comment by Raja-Simha** [comment]
Hey @wcf-todd @deemeetree @kwolfy @br-tyler-milner 
Firstly, thank you for the detailed description and reaching out to us. 

Secondly,  I am happy to let you guys know that you can now generate documentation from your OpenAPI 3.0 schema. You can try out the feature as explained [here](https://learning.postman.com/docs/publishing-your-api/documenting-your-api/#generating-api-documentation). 

As we make further improvements, we'd love your feedback on API schema documentation. Do share your thoughts with us once you have tried it out. If you'd like to connect and discuss over a call, feel free to schedule one [here](https://calendly.com/raja-postman/office-hours).

**Comment by petkostas** [comment]
@Raja-Simha this doesn't seem to fix the issue of the missing request/response documentation which other tools support. This is also a problem for our development organization, as our source of truth is the OpenAPI specification and everything related to operations is documented within the OAS. The current status means that our developers have to properly specify payloads in the OAS file and then manually add them in the descriptions of the path operations, this is obviously not desirable.

**Comment by Raja-Simha** [comment]
@petkostas thanks for your response. 

> our source of truth is the OpenAPI specification and everything related to operations is documented within the OAS

That is exactly why we are auto generating documentation from your OAS file as explained in [this blog post](https://blog.postman.com/open-api-3-0-documentation/). You can check out how request/response info is represented in schema documentation [here.](https://www.postman.com/postman/workspace/postman-public-workspace/api/f00b3236-8241-43ce-925f-80f6f73f8ffc/version/26b1363e-2b53-4ec3-85b2-21ae480c86fe?tab=documentation)

Do elaborate if I am missing something here. Alternatively, I'd love to connect over a call and discuss your use-case. Feel free to schedule a call [here](https://calendly.com/raja-postman/office-hours).

**Comment by petkostas** [comment]
@Raja-Simha the rendered documentation of the collections does not document the request and response bodies, this has been open since 2017 (this should be marked as a duplicate):
https://github.com/postmanlabs/postman-app-support/issues/3117

**Comment by jimmyn** [comment]
I have the same issue, the rendered documentation shows the raw body of the request and not the property list with the description

Generated postman documentation:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/5391775/201078978-ac6e6890-00a3-4f50-94da-1dec28cdb0c8.png">

API definition:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/5391775/201079181-67078729-bdca-45a8-ad93-d58fcf3ff096.png">

Until this is fixed, we are using a custom website to generate documentation from openapi schema

**Comment by wcf-todd** [comment]
I have not been able to internally promote using Postman because the generated API documentation lacks the core aspects of request response bodies.  stoplight.io has a nice layout though, and seems to do it correctly. We switched our documentation rendering over to them.  stoplight.io also has a nice GUI tool that builds the OAS spec for you.

**Comment by Andreas-T** [comment]
I add my voice to this issue. Until there is a representation of the schema in the request/response sections of the documentation, similar to what Swagger and Stoplight offer,  we are unable to use Postman as an API documentation tool.

**Comment by elizatlawy** [comment]
Add my voice as well, the lack of representation of the schema is a big issue for us as well.

**Comment by shashankawasthi88** [comment]
@Andreas-T @elizatlawy thanks for bringing this over again. I am the product manager for the API builder domain in Postman. I want to understand how mix of the schema documentation and the collection documentation can help us achieve your usecase. Can we get onto a short call to discuss this in detail. You can pick a time to talk to me using [this](https://calendly.com/shashank-awasthi/v10-feedback).

**Comment by Zack-Heisnberg** [comment]
lol come on do this already

**Comment by shashankawasthi88** [comment]
@Zack-Heisnberg can you explain your workflow once? Also, have you tried using schema-based documentation that Postman provides - https://learning.postman.com/docs/publishing-your-api/documenting-your-api/. The schema-based documentation will have the details needed.

**Comment by hexesisb** [comment]
This feature is really needed

**Comment by Andreas-T** [comment]
More than 2 years later and nothing has happened. Based on the comments from Postman staff, it looks like they don't understand the problem. I urge the devs to read the original post again, it should be clear enough. As it is now, the API documentation is lacking the schema description from the definition and thus is practically useless and we have to use other tools for documentation.

**Comment by sergei-ft** [comment]
OpenAPI became a standard in the industry. At the same time Postman-like way to describe requests/responses and docs based on it lack some important features which OpenAPI provides. There is no way to list enums, add full text description to a property, add format of a values, etc.
I wonder why this request is ignored for such a long time. On my mind, it is so easy to implement - use any opensource renderer for OpenAPI doc. As I see, you even tried to implement it, there is Definition in APIs which is actually a rendered OpenAPI. But this render is so inconvenient. UX is do bad as sections are not highlighted, everything is just plane block with text. It doesn't work properly with multi-file doc rendering a lot of "undefined entities" instead of meaningful names. Look at the screenshot - it is so hard to read.
![image](https://github.com/postmanlabs/postman-app-support/assets/141429485/81473928-05a1-4d1e-9e8d-8323cd1ddb81)

So, better OpenAPI render and OpenAPI doc is must have for tools like Postman. We pay for it. All your competitors have it. I don't see any reason to postpone implementation of the feature for 2 years.

**Comment by athish-t** [comment]
+1. Really need this

**Comment by shashankawasthi88** [comment]
@athish-t  and others thanks for bumping this up. We are working on a feature to introduce types in collection, which should allow you to accomplish the usecase using collections. Here is what the feature looks like - https://www.loom.com/share/24284f7c2b07410ab1237783b9476248?sid=d23c26b2-c3e2-4963-821a-b934f2c3fbba

Please get in touch with me on shashank.awasthi@postman.com to get an early access to the feature.
cc: @sergei-ft @Andreas-T @br-tyler-milner

**Comment by preethammavin** [comment]
Hey team, we have released describing [types](https://learning.postman.com/docs/design-apis/collections/overview/) in Collections for all users. With this, you can describe: 

- What fields are required/optional.
- Special format considerations for fields.
- Enumeration values.
- Descriptions of each field.

This propagates to requests when executing, and also in documentation view as well.

You can read more about how and what you can do with this capability [here](https://learning.postman.com/docs/design-apis/collections/overview/)

Feel free to re-open the issue if this does not address the workflows.

**Comment by SantiagoMoreira-Resonet** [comment]
Hi, types is great, but it isn't being generated from the schema I already have in the spec, so it's pointless....
I need to double work....

**Comment by preethammavin** [comment]
Hey, @SanMorei-opos , if you have the Spec in our Spec Hub and generate a collection from it, it will generate the types based on the schema already defined. 
I have attached a recording to show how it works. 
https://github.com/user-attachments/assets/97a4a93f-a5b4-47ea-8aa0-c8ecc6e1b7b2

**Comment by SantiagoMoreira-Resonet** [comment]
@preethammavin I have spec in spec hub, tried doing the same you did, but I cannot make it work.
Schemas do not appear.
It´s like you have Types already turned on, but on default it´s off for me.

**Comment by shashankawasthi-postman** [comment]
Hi @SanMorei-opos can you confirm that you are on the latest Postman version? This should be available in the product now. Also, you can schedule a call with us using [this](https://calendly.com/shashank-awasthi/typed-information-in-collections-clone) link. We can debug this live.

**Comment by SantiagoMoreira-Resonet** [comment]
Hi  @shashankawasthi-postman , yes, using latest version.
Sure, I will schedule a call!

<img width="246" height="71" alt="Image" src="https://github.com/user-attachments/assets/bc18e9d2-0b9f-41e9-bfc4-5f1f925daa28" />

**Comment by shashankawasthi88** [comment]
Hi @SanMorei-opos - the issue should now be resolved! You should now be able to see the schema and type information when generating a collection from an Open API Specification.

**Comment by eaicalvet** [comment]
Guys, this can't be that hard. We DON'T WANT to generate the schema via Open API Specification, we WANT TO SHOW THE SCHEMA ON THE RENDERED DOCUMENTATION.

Just a tab over here saying "schema" would be good enough. 
<img width="264" height="135" alt="Image" src="https://github.com/user-attachments/assets/b4658964-66a7-4f9d-896f-8de9e95ae67c" />

4 years and a ton of employees saw that thread and nobody could understand that request. What a shame!
