### ISSUE TITLE
Invalid characters in native dialog on Snap 

### ISSUE THREAD

**Issue by sombriks** [a85/POSTMan-Chrome-Extension#10449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

![Captura de tela de 2021-11-18 22-09-22](https://user-images.githubusercontent.com/556695/142526008-9d4eef41-cdee-4aaa-b9d0-e5acfd2469b4.jpg)

### Steps To Reproduce

create collection, then try to export it

### Environment Information

```markdown
- Operating System: fedora 34
- Platform Type: linux/snap store
- Postman Version: Postman v8.12.5
```

### Similar reports

* https://github.com/postmanlabs/postman-app-support/issues/10688
* https://github.com/postmanlabs/postman-app-support/issues/10557
* https://github.com/postmanlabs/postman-app-support/issues/10401

**Comment by DannyDainton** [comment]
Hey @sombriks 

Is this still an issue, it looks like the file explorer of your OS is showing that, Postman seems to look fine behind it. 

Are there any more details that you can provide, please?

**Comment by sombriks** [comment]
Hello @DannyDainton ,

yes it works mostly fine but when it tries to export a collection it brings that corrupted dialog.
it might be snap fault, not postman.

in another "installation", which i just unzip postman that issue does not occur.

is there any chance to offer postman as an .rpm package?

**Comment by sombriks** [comment]
indeed looks like an issue on snap itself not postman: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365

**Comment by 1bitphoenix** [comment]
Hi @sombriks,
Can you provide the steps to reproduce the issue? I tried to reproduce it at my end by using custom fonts, but I couldn't.

Thank you and regards,
Rituka, Postman

**Comment by 1bitphoenix** [comment]
As mentioned above, this is an issue with snaps and exists for other snap apps as well. There’s nothing much that Postman can do here. Therefore closing the issue.

**Comment by RaisinTen** [comment]
As asked by @1bitphoenix, I'm closing this issue:

> Marking as closed - this is an issue with snaps and exists for other snap apps as well. There's nothing much that Postman can do here.

**Comment by ramilani12** [comment]
I have this issue on my Ubuntu 22.04

**Comment by ramilani12** [comment]
![image](https://user-images.githubusercontent.com/142189/208977330-58d4da8b-565f-4d84-98c5-2f0d445908c9.png)

See the image on Ubuntu 22.04

**Comment by mau21mau** [comment]
I fixed this issue by unninstalling the stable version and installing the edge version on Ubuntu Software.

**Comment by brenton-sdc** [comment]
Any other fix besides updating to the latest/edge? Work requires v9. Latest version in the snap store for v9 is 9.31.28 (stable) and the same version for edge and I cannot select a local json file for a test run

**Comment by dhruvilpirimid** [comment]
For People facing this issue:

Clearing the chromium cache worked for me:
`rm -rf ~/snap/postman/common/.cache`

Close all your active chromium windows (Including Postman) after running this and open again. The issue should be fixed.
[Source](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365)

**Comment by mat-twg** [comment]
ubuntu 23.04
![image](https://github.com/postmanlabs/postman-app-support/assets/64251479/a08809d5-b161-42d5-9b40-56debf17da8b)

**Comment by luisalvarado** [comment]
Ubuntu 23.10

![image](https://github.com/postmanlabs/postman-app-support/assets/29236/b580daf1-5f3f-40a7-a3e3-3806c8efb9de)

This is the dialog for enabling hardware acceleration.

The uploading box shows properly now. Here is the version tested:

![image](https://github.com/postmanlabs/postman-app-support/assets/29236/84b53687-f24e-4663-8a41-176757471d3b)

**Comment by alisamie97** [comment]
I'm using ubuntu 23 and I have the same issue, tried clearing chrome cache as mentioned here: https://github.com/postmanlabs/postman-app-support/issues/10449#issuecomment-1602468844 but it didn't fix the issue.

**Comment by vistarsvo** [comment]
same issue...
clearing snap postman cache, chromium cache, fontconfig, etc.... Nothing. Still have a problem

**Comment by VuKhoiGVM** [comment]
have the same issue.. had fixed it successfully yet. Here is step:

1. update font `sudo fc-cache -r -v` and `reboot`
2. find font config of snap application (postman): `find ~/snap/postman/ -name 'fontconfig'`
3. remove all cache font config in the result from above: `rm -rf ~/snap/postman/common/.cache/fontconfig/`

Hope it helpful!

**Comment by scr4bble** [comment]
Any progress here? Could we reopen this issue please? It's not fixed and it is extremely annoying.

**Comment by soorajsprakash** [comment]
![image](https://github.com/user-attachments/assets/937f8fbf-e308-499e-9d41-384f35e19f5f)

Updated to this latest version from snap, and the issue is fixed.

**Comment by antonimarek** [comment]
Tried all advices and nothing works :(

**Comment by maxidev** [comment]
Same issue here ubuntu 24.04 latest postman on snap

**Comment by ErikMCM** [comment]
To everyone still struggling with this, the following solution worked for me, along with removing the Postman font cache directory [mentioned earlier](https://github.com/postmanlabs/postman-app-support/issues/10449#issuecomment-2083106851).

https://github.com/electron-userland/electron-builder/issues/5217#issuecomment-700707564

**Comment by avallbona** [comment]
Using the option of "Clear cache and reload" from the "Help" menu worked for me 🤷‍♂

**Comment by alexcorvis84** [comment]
> Using the option of "Clear cache and reload" from the "Help" menu worked for me 🤷‍♂

That option doesn't show on **snap store** version of Postman. Probably you're referring to the [Linux download ](https://www.postman.com/downloads/) versions...which is quite different.

<img width="473" height="229" alt="Image" src="https://github.com/user-attachments/assets/1b12d86b-a160-414d-8f64-8e5892e68d80" />

PS: In my case I've 'fixed' the issue uninstalling snap version **(in Ubuntu 24.04 issue still remains)** and opted to use the linux one...no issues so far.

**Comment by nerdy-panda** [comment]
My issue was resolved using these commands. : 
```
sudo rm /var/cache/fontconfig/*
rm -rf ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by FedePalm** [comment]
@nerdy-panda thanks! Worked for Ubuntu 24.

**Comment by ket4z** [comment]
Broken again on (copied from about dialog)
* version 11.72.3 
* UI version 11.72.3-ui-251118-0501 
* Desktop platform version 11.71.7
* Architecture x64
* OS platform linux 6.14.0-35-generic (ubuntu 24.04 with all updates applied as of today)

<img width="1513" height="597" alt="Image" src="https://github.com/user-attachments/assets/d42aa0a8-d7aa-4028-ae1d-f10d615c90cc" />

Nnone of the above font cache cleaning steps resolves the issue
