### ISSUE TITLE
Inconsistent indentation for syncing vs exporting collections

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#10820]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If an API is integrated with GitHub, collections synced as part of the API use 4 spaces as indentation:
```
{
  "info": {
    "_postman_id":
```

If the same collection file is exported, however, the file uses tabs as indentation:
```
{
	"info": {
		"_postman_id":
```

All files coming from Postman should use the same type of indentation.

Initially reported on https://github.com/postmanlabs/postman-app-support/issues/9622

### Steps To Reproduce

1. Export a collection, and compare it with what is synced to a repository as part of the API<>Git Integration flow.

### Operating System

OSX

### Postman Version

9.15

### Postman Platform

Postman App

**Comment by helloint** [comment]
@abhijitkane thank you.
one more question, about "_postman_id":
When I export the collection and import again, it will cause the "_postman_id" changed to be a new one.
Is there a way to avoid this?

Thank you.

**Comment by abhijitkane** [comment]
@helloint Not at the moment. Can you describe the use case that requires you to export and reimport? There might be an alternate solution we can suggest.

**Comment by helloint** [comment]
@abhijitkane I have a collection with a lot of requests in it. Some of the requests share some common test and prerequest scripts. instead of change them manually one by one via app GUI, I export the JSON and do batch replacement via text editor then import again.
I tried delete the "_postman_id" before import, still doesn't work, new ID being generated.

Thanks.

**Comment by abhijitkane** [comment]
@helloint This should be fixed now. Feel free to reopen if you're still seeing inconsistencies in the indentation.

**Comment by helloint** [comment]
@abhijitkane I tested today and it doesn't seem to be fixed.
1. I tried the github integration sync. the indent is still 2 spaces, no way to change it.
2. I download the latest Postman App v9.16, export the collection using v2, the indent is still Tab.

I guess I don't have access to reopen this ticket.
Thanks.

**Comment by prashantRaghu** [comment]
@helloint Could you describe what you did in step 1. ?
Did you push a new relation/collection to Github via the integration sync flow?

**Comment by helloint** [comment]
> @helloint Could you describe what you did in step 1. ? Did you push a new relation/collection to Github via the integration sync flow?

Hi @prashantRaghu ,
I first delete the old GitHub integration, and then created a new one, via personal access token. After it is done, the integration will automatically push the collection configuration into the specific branch.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/4143533/167303844-c7448dc8-4a67-4fd5-9ffb-bfa6a4878183.png">
you see, the indent is still 2 spaces.

**Comment by prashantRaghu** [comment]
@helloint Deleting an integration and doing a reintegration would show a conflict if a collection file exists in both the places and if remote files are selected to be kept it will not push and rather just link those as the same.
What would actually change the indentation is any further pushes to the repository from Postman eg,
1. Adding a new collection to the repository.
2. Editing a synced collection in Postman and pushing the update.

Reintegration doesn't fall under these cases as it just links the entities present in Postman and Repo without a Push/commit to the Repo so can you try any of those 2 and let us know if you still see the issue.

**Comment by helloint** [comment]
@prashantRaghu 
i created a new collection, created a new repo, public one, just for this indent test.
https://github.com/helloint/postman/blob/sync/postman/indent-test.postman_collection.json
still space as indent.
there are 2 branches: 
1.` main` is the default one, and I suppose to do manually change here and the automation will checkout and run. The config comes from Postman App export (v9.16).
2. `sync` is to integrate with postman. i will do PR from `sync` to `main` for changes that comes from Postman App.

Please help to see what's going on.
Many thanks!

**Comment by prashantRaghu** [comment]
@helloint Could you describe the flow you went through to bring your collection from Postman into the Repository after adding it as a relation to the API Version?

I tried reproducing the steps you mentioned and this is what the [format is like](https://github.com/prashantRaghu/indent-test/blob/dev/postman/collections/indent-test_46185845-cac3-4474-8402-e3ce3004982a.json)

**Comment by helloint** [comment]
@prashantRaghu I see the github commit log, looks like you commit yourself, not via integration.
if the commit comes from integration, the comment format should be '[user_id] updated [collection name]'

**Comment by prashantRaghu** [comment]
@helloint  What do you mean by 'integration' here? which integration flow are we talking about

**Comment by helloint** [comment]
@prashantRaghu ok, let me describe it step by step.
1. I have a collection for testing this indent issue, the name is 'indent-test'
<img width="569" alt="image" src="https://user-images.githubusercontent.com/4143533/167857429-96ba7b74-3091-4dbb-94df-b0010b4dfc28.png">

2. I created a GitHub repo named `postman`, and in the default `main` branch, I upload the collection configuration I export from Postman App. [Here it is](https://github.com/helloint/postman/blob/main/postman/indent-test.postman_collection.json)
3. I created a new branch named `sync`, to let Postman server to sync collection configuration to GitHub, everything someone update the collection.
4. I then created a Postman Sync Integration, see configuration below:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/4143533/167858653-d2599946-ea6f-4b40-b134-2abafb8f2c90.png">
5. After the integration created, I manually made a change to the Request in Postman App, and I then see the Postman server pushed a commit to my GitHub. Here is the commit: https://github.com/helloint/postman/commit/e8e706076d6fb6d86554abdf00595b921d46430c.
As you can see, the indent changes from tab to spaces.
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/4143533/167859357-5eaca0d0-590d-4ea9-b789-cf8656ea5296.png">

I think this is the issue this ticket originally described.

**Comment by theshubhamjoshi** [comment]
Hello @helloint, This is Shubham from Postman's Integrations squad. Thanks for reporting this descrepency in our flow. We have identified the difference which was causing this difference of tabs vs spaces on the synced collection via Postman's Github Integration. We have pushed a fix for the same and you should now be able to see tabs in your synced collection similar to what you currently get in the exported collection. Can you the flow once again and verify the same?
Thanks!

**Comment by helloint** [comment]
Hi @smartron1, yeah the indent issue seem to be resolved.
Just I noticed another new difference between the export and the sync version. See:
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/4143533/168116208-5bf618d0-e3df-428f-b9f0-4cbd0a03d92f.png">
I tried Import the file from sync, and export again, I still get the same file as before.
I hope these 2 files can be the same...
