### ISSUE TITLE
Schema auto fetch for GraphQL does not send Authentication header when authentication is set to OAuth2.

### ISSUE THREAD

**Issue by k1th** [a85/POSTMan-Chrome-Extension#10922]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Schema auto fetch for GraphQL does not send Authentication header when authentication is set to OAuth2.
It does not matter, if it's set in the request or inherited from the collection. 
In both cases no auth header is sent.

### Steps To Reproduce

- Setup auth for OAuth2
- Get a token
- Create GraphQL Request
- Refresh schema

### Screenshots or Videos

<img width="686" alt="image" src="https://user-images.githubusercontent.com/671141/169025524-5d5254e0-ccce-4a84-b4d3-d699b4a044a8.png">

### Operating System

macOS

### Postman Version

9.19.2

### Postman Platform

Postman App

**Comment by aalmazan** [comment]
Writing here before I create a new ticket, but I'm also experiencing the same with Basic Auth. Both the Postman client (hidden headers shown) and my local testing server do not show authorization headers. With the same settings on a normal "HTTP request" type, enabling Basic auth shows authorization headers properly. 

Steps:
* Create GraphQL request
* Authorization tab: Change/add username and/or pass.
* Headers tab: Show all fields if not already.  No authorization headers.
* Send request, no authorization data will be sent.

**Comment by SterlingChin** [comment]
The new GraphQL client is in open beta. I tried to reproduce in the new client and was unable to. Can you try OAuth and Basic Auth with the new client and confirm this issue has been solved?

The screenshot is of Basic Auth and shows 'authorization` in the body.
![Screen Shot 2023-02-27 at 3 51 12 PM](https://user-images.githubusercontent.com/8900638/221694246-b1478cf4-6a65-4067-8ec4-5002e9d26088.png)

**Comment by rayo-cvent** [comment]
I have a similar issue with the beta GraphQL client. Steps to reproduce the issue:

- Set Authorization API Key: Key to x-api-key, Value to any valid value
- Go to the Schema tab
- Click the refresh button next to Using GraphQL Introspection
- The x-api-key authorization header is not sent; receive HTTP 403 Forbidden

**Comment by SterlingChin** [comment]
Following up on this, we are aware of an OAuth2 bug and are working on a fix.

**Comment by nibblesnbits** [comment]
Any movement on this?

**Comment by jonmcwest** [comment]
Still having this issue with x-api-key inherited from parent folder - it's sent in the main request, but not in the schema fetch request.
