### ISSUE TITLE
Flatpak Postman crashes trying to load certificates

### ISSUE THREAD

**Issue by luckyone89** [a85/POSTMan-Chrome-Extension#12330]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I try to start the flatpak Postman app, the application initially starts to load and then crashes.

The problem seems to come from OpenSSL. The command used to create the `postman-proxy-ca.cert` file doesn't seem to recognize the req argument, and instead exits with the return code 1.

Some Postman issues seems similar to my issue, but the application seems to work despite the issues and the workarounds necessary.

#10299

### Steps To Reproduce

1. Start the latest version of the flatpak app
2. Wait a bit on the loading screen
3. *Crash*

### Screenshots or Videos

The crash in question:
![Postman-crash.webm](https://github.com/postmanlabs/postman-app-support/assets/16344048/eae1ab37-38b8-48da-a190-9f55c9c31870)

The entire logs of this crash:
```text
The disableGPU setting is set to undefined
Not disabling GPU
Gtk-Message: 17:14:28.234: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:14:28.236: Failed to load module "canberra-gtk-module"
[10:0920/171428.251011:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
[10:0920/171428.251051:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
Main: Starting cleanup of stale files
Main: Cleanup of stale files completed
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: ligne 1: xdg-mime : commande introuvable

LaunchProcess: failed to execvp:
xdg-settings
Main~createDefaultWorkingDir - Default working dir creation already attempted
1695244468316 main info "Booting Postman 10.18.3, linux-6.4.15-200.fc38.x86_64 on x64"
1695244468317 main info "EventBus~initialize - Success"
1695244468319 main info "Proxy configuration has not been setup"
1695244468319 main info "CloudProxyManager~init - Success"
1695244468335 main info "performShellDataMigration: Migration has already been done. Bailing out"
1695244468340 main info "UpdateHandler~init - Success"
1695244468342 main info "LeaderSelection: Initialized successfully"
1695244468343 main info "VersionDependencyService: Initialized successfully"
error reading fileError: ENOENT: no such file or directory, open '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695244468349 main info "Generated root certificate for linux"
1695244468350 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1695244469585 main info "GPU detected VID 4318 DID 9504 ACTIVE true"
1695244469585 main info "GPU detected VID 32902 DID 39497 ACTIVE false"
1695244469650 main error "Error encountered while creating root CA",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
1695244469650 main error "Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
1695244469650 main error "HTTPSProxy~Unable to generate certificates",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /var/home/olivierlachance/.var/app/com.getpostman.Postman/cache/a7a13e365a6d7041cad5addba9148aadd8ffcc78\n40478075987F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
[52:0920/171429.705096:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
1695244469767 main info "shellController~init: Success"
1695244469786 main info "shellMeta~init: Success"
1695244469786 main info "partitionMigrationService: State of V7 partition:"
1695244469787 main info "partitionMigrationService: V7 partitions",[]
1695244469787 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"
1695244469787 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"
1695244469787 main info "partitionMigrationService~init: Success"
1695244469804 main info "partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]
1695244469819 main info "userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","5a1ee78d-ff76-4d00-913b-ed7029c4479c"
1695244469819 main info "userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","5a1ee78d-ff76-4d00-913b-ed7029c4479c"
1695244469829 main info "userPartitionService~init: Success"
1695244469898 main info "userPartitionService: State of v8 partition system:"
1695244469907 main info "shell~init~getPartitionToLoad: loading active partition"
1695244469908 main info "userPartitionService: List of partitions:",[{"partitionId":"5a1ee78d-ff76-4d00-913b-ed7029c4479c","namespace":"users","userId":"25859634","teamId":"0","lastUpdated":"2023-09-18T22:31:44.639Z"},{"partitionId":"a46a3b76-fe65-4d1d-9155-df8c58490edd","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1695244469909 main info "userPartitionService: users global meta:",{}
1695244472487 main info "RuntimeIPCAgent~started: Success"
1695244472706 main info "Main~getRemoteInitPath:: "
1695244473040 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1695244473042 main info "@postman/app-updater: version Updated","10.17.4","10.18.3"
1695244473042 main info "UpdateHandler~app-update-events - Received event",{"name":"electronVersionUpdated","namespace":"appUpdate","data":{"lastKnownVersion":"10.17.4","currentVersion":"10.18.3"}}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
Error: ENOENT: no such file or directory, open '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695244473051 main error "Main~handleUncaughtError - Uncaught errors",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt","name":"Error","message":"ENOENT: no such file or directory, open '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'","stack":"Error: ENOENT: no such file or directory, open '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'"}
Main~handleUncaughtError - Uncaught errors [Error: ENOENT: no such file or directory, open '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/home/olivierlachance/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
}
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1695244473067 main info "windowManager: First requester booted successfully."
1695244473068 main info "windowManager~restoreWindows: Restoring requester windows"
1695244473068 main info "Main~AppEvents - Received booted event for process requester.Version 10.18.3 UI Version: 10.18.3-ui-230918-0902 Desktop Platform Version: 10.18.3"
```

This is the openssl command ran inside the Postman flatpak sandbox:
![openssl-postman](https://github.com/postmanlabs/postman-app-support/assets/16344048/a48c8f29-d0d2-4579-adb9-1be9ebdfcf6a)

### Operating System

Linux

### Postman Version

10.18.4

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

I've already tried to reinstall and delete all the old config files.

**Comment by chrsrns** [comment]
I can confirm this on my side. The lightweight version works fine, but logging in crashes the application.

**Comment by amreshh** [comment]
Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`

```bash
openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
```

(https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639)

**Comment by anaximeno** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

I had the same problems under LMDE 6 (based on Debian 12) and Linux Mint 21.2 (based on Ubuntu 22.04), the command above fixed the problem.

**Comment by MichelRibeiro1** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

I had the same problem here under Fedora 38 with the flatpak Postman instalation. The command above fixed the problem. Thank you!

**Comment by guilhermesousa-cwi** [comment]
Ubuntu 22.04.3 LTS

X11

Postman: 
 10.18.4 [FLATPAK]
 10.18.7 [.TAR.GZ]

-------------------------------------------------------------------------------------------------

The above command did not resolve the issue. I downloaded the .tar.gz version, but when logging in, the application does not receive browser validation and then closes.

-------------------------------------------------------------------------------------------------

Via CLI we can see some logs.

flatpak run com.getpostman.Postman
The disableGPU setting is set to undefined
Not disabling GPU
Gtk-Message: 12:19:22.829: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:19:22.942: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:19:22.946: Failed to load module "canberra-gtk-module"
[10:0921/121923.009665:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[10:0921/121923.009772:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
Main: Starting cleanup of stale files
Main: Cleanup of stale files completed
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: linha 1: xdg-mime: comando não encontrado

LaunchProcess: failed to execvp:
xdg-settings
MaincreateDefaultWorkingDir - Default working dir creation already attempted
1695309563229 main info "Booting Postman 10.18.4, linux-6.2.0-33-generic on x64"
1695309563232 main info "EventBusinitialize - Success"
1695309563235 main info "Proxy configuration has not been setup"
1695309563237 main info "CloudProxyManagerinit - Success"
1695309563298 main info "performShellDataMigration: Migration has already been done. Bailing out"
1695309563316 main info "UpdateHandlerinit - Success"
1695309563320 main info "LeaderSelection: Initialized successfully"
1695309563322 main info "VersionDependencyService: Initialized successfully"
error reading fileError: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695309563347 main info "Generated root certificate for linux"
1695309563350 main info "LinuxAutoUpdaterCleanup - Initial cleanup successful"
1695309563392 main info "GPU detected VID 32902 DID 39745 ACTIVE true"
[47:0921/121923.421370:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
1695309563465 main info "shellControllerinit: Success"
1695309563502 main info "shellMetainit: Success"
1695309563503 main info "partitionMigrationService: State of V7 partition:"
1695309563504 main info "partitionMigrationService: V7 partitions",[]
1695309563505 main info "partitionMigrationServicerectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"
1695309563506 main info "partitionMigrationServicerectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"
1695309563506 main info "partitionMigrationServiceinit: Success"
1695309563573 main info "partitionMigrationServicerunV8PartitionsIntegrity: Two way migration removing the following partitions from v8",[]
1695309563680 main error "Error encountered while creating root CA",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n at ChildProcess. (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n at ChildProcess.emit (node:events:390:28)\n at ChildProcess.emit (node:domain:475:12)\n at maybeClose (node:internal/child_process:1064:16)\n at Socket. (node:internal/child_process:450:11)\n at Socket.emit (node:events:390:28)\n at Socket.emit (node:domain:475:12)\n at Pipe. (node:net:687:12)"}
1695309563680 main error "Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n at ChildProcess. (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n at ChildProcess.emit (node:events:390:28)\n at ChildProcess.emit (node:domain:475:12)\n at maybeClose (node:internal/child_process:1064:16)\n at Socket. (node:internal/child_process:450:11)\n at Socket.emit (node:events:390:28)\n at Socket.emit (node:domain:475:12)\n at Pipe. (node:net:687:12)"}
1695309563681 main error "HTTPSProxyUnable to generate certificates",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n at ChildProcess. (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n at ChildProcess.emit (node:events:390:28)\n at ChildProcess.emit (node:domain:475:12)\n at maybeClose (node:internal/child_process:1064:16)\n at Socket. (node:internal/child_process:450:11)\n at Socket.emit (node:events:390:28)\n at Socket.emit (node:domain:475:12)\n at Pipe. (node:net:687:12)"}
1695309563692 main info "userPartitionServicegetRecentV8UserPartition: recent v8 user context partition ","50b2391e-b37c-421f-bd4f-231d2a493541"
1695309563692 main info "userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","50b2391e-b37c-421f-bd4f-231d2a493541"
1695309563719 main info "userPartitionServiceinit: Success"
1695309563764 main info "userPartitionService: State of v8 partition system:"
1695309563778 main info "shellinitgetPartitionToLoad: loading active partition"
1695309563784 main info "userPartitionService: List of partitions:",[{"partitionId":"50b2391e-b37c-421f-bd4f-231d2a493541","namespace":"users","userId":"21137513","teamId":"1285670","lastUpdated":"2023-09-21T14:20:15.045Z"},{"partitionId":"5a9b379b-1c82-43e0-9e43-9b2c20aeb041","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1695309563784 main info "userPartitionService: users global meta:",{}
1695309570805 main info "RuntimeIPCAgentstarted: Success"
1695309571502 main info "MaingetRemoteInitPath:: "
1695309571990 main info "UpdateHandlerapp-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695309572000 main error "MainhandleUncaughtError - Uncaught errors",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt","name":"Error","message":"ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'","stack":"Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'"}
MainhandleUncaughtError - Uncaught errors [Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1695309572047 main info "windowManager: First requester booted successfully."
1695309572047 main info "windowManagerrestoreWindows: Restoring requester windows"
1695309572048 main info "MainAppEvents - Received booted event for process requester.Version 10.18.5 UI Version: 10.18.5-ui-230920-1358 Desktop Platform Version: 10.18.4"

**Comment by anaximeno** [comment]
@guilhermesousa-cwi for the flatpak wrapper make sure you execute the command [above](https://github.com/postmanlabs/postman-app-support/issues/12330#issuecomment-1730195683) inside the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy` after that it should look like the following:

![Screenshot from 2023-09-25 12-42-31](https://github.com/postmanlabs/postman-app-support/assets/63073056/148abeeb-0536-4936-9e2e-a9cc0a72f338)

**Comment by rolodoom** [comment]
I have the same issue. I fixed following this steps:
1. Downloaded and executed the official app  from [https://www.postman.com/downloads/](https://www.postman.com/downloads/)
2. Copied the certificate from ~/.config to ~/.var
```
cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman
```

**Comment by guilhermesousa-cwi** [comment]
@rolodoom Wonderful, it worked. Good job!

cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman

**Comment by tonibgd** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

Had the same issue with flatpak Postman 10.18.7, this fixed the problem, thanks!

**Comment by cferber2341** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

This also fixed the issue for me. 

Flatpak: 1.15.4
Postman: 10.18.10

**Comment by CJFxTiKiMoN** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

This also fixed the issue for me

Flatpak: 1.15.4
Postman: 10.18.10

**Comment by shak0x90** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

thanks, man u saved my day

**Comment by brunofunnie** [comment]
Also fixe

> @guilhermesousa-cwi for the flatpak wrapper make sure you execute the command [above](https://github.com/postmanlabs/postman-app-support/issues/12330#issuecomment-1730195683) inside the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy` after that it should look like the following:
> 
> ![Screenshot from 2023-09-25 12-42-31](https://user-images.githubusercontent.com/63073056/270360518-148abeeb-0536-4936-9e2e-a9cc0a72f338.png)

Also fixed for me. For the lazy guys below a "fix line":

> mkdir -p ~/.var/app/com.getpostman.Postman/config/Postman/proxy && openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout ~/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.key -out ~/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt

**Comment by CDLProduction** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

This one fixed issue for me.
OS: Pop OS

**Comment by sombriks** [comment]
i understand that Flatpak version is a 3rd party distribution, but should it be?

at the same time, what's the issue regarding to offer .deb and .rpm versions?

it took me less than a few hours to "package" and test it using official .tar.gz download so i can have official postman for all users.

https://github.com/sombriks/postman-rpm

But it's temporary, you guys should provide Flatpak support, you already has snap on your site, embrace flatpak too.

Or come back to .dev / .rpm packages, no one will complain since you guys will also be able to sign those too.

**Comment by rohit-d-code** [comment]
I installed postman manually and same issue start happening after i just logged in. Then i did the same thing manually make the directory
`~/.var/app/com.getpostman.Postman/config/Postman/proxy`
and run the same command everyone is telling to use
 `openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
`

**Comment by Black-Sirius69** [comment]
I have faced the same issue and sadly didn't find any fix had to switch to a distro which supports postman .deb files

**Comment by samislam** [comment]
I fixed the problem by running the following commands:
```bash
$ cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
$ openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
```
Postman downloaded from Flathub, On Linux Mint.

**Comment by antoniovj1** [comment]
> I have the same issue. I fixed following this steps:
> 
> 1. Downloaded and executed the official app  from https://www.postman.com/downloads/
> 2. Copied the certificate from ~/.config to ~/.var
> 
> ```
> cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman
> ```

This one worked for me in Ubuntu 23

**Comment by abdilra7eem** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

I had the same issue with the latest Flathub version after logging in. OS: Fedora 39. 
This fixed the issue. Thanks a lot! :-)

**Comment by JonathanRamosNascimento** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

Thanks

**Comment by ayush-gupta-novopay** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

Worked for me also. Fedora 38 and Postman 10.22.6. Thanks.

**Comment by Alopalao** [comment]
> @guilhermesousa-cwi for the flatpak wrapper make sure you execute the command [above](https://github.com/postmanlabs/postman-app-support/issues/12330#issuecomment-1730195683) inside the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy` after that it should look like the following:
> 
> ![Screenshot from 2023-09-25 12-42-31](https://private-user-images.githubusercontent.com/63073056/270360518-148abeeb-0536-4936-9e2e-a9cc0a72f338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTg5MDAsIm5iZiI6MTcwNjM5ODYwMCwicGF0aCI6Ii82MzA3MzA1Ni8yNzAzNjA1MTgtMTQ4YWJlZWItMDUzNi00OTM2LTllMmUtYTljYzBhNzJmMzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIzMzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYmEzODQ4MTJjNzUzMDhhNTdhNWRmMjIzODNlMmIyNzJmMmE5NWY1NzRjMzFhOTM1MmZjNzYzYmE1ZmRjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7wl0VW5VUmsPo2ezF59zNiQw4lPHkKUC-fck4zc0IVs)

Works in Debian 12 Bookworm, postman installed with flatpak

**Comment by NikColonel** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

It fixed my problem too.
Flatpack Postman v10.22.6
Fedora 39
GNOME
Wayland

**Comment by HendrikHuebner** [comment]
Still having the same issue on Debian 12 / KDE Plasma 5.27.5 / Kwin. amreshh's solution worked

**Comment by All3xJ** [comment]
still have this.

**Comment by todor0v** [comment]
For anyone else creating the certificate manually and facing the same issue with the following command:
```
openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
```
Make sure you do so in the correct folder (cd into it beforehand). You can find it by running `flatpak run com.getpostman.Postman` and looking in the terminal. For example in my case:
```/home/{user}/.var/app/com.getpostman.Postman/config/Postman/proxy/```

cc: @All3xJ

**Comment by MajorAchilles** [comment]
> For anyone else creating the certificate manually and facing the same issue with the following command:
> 
> ```
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> Make sure you do so in the correct folder (cd into it beforehand). You can find it by running `flatpak run com.getpostman.Postman` and looking in the terminal. For example in my case: `/home/{user}/.var/app/com.getpostman.Postman/config/Postman/proxy/`
> 
> cc: @All3xJ

This is the one that worked for me. System info:

```
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.8.0-76060800daily20240311-generic 
```

**Comment by glauberdm** [comment]
> I have the same issue. I fixed following this steps:
> 
> 1. Downloaded and executed the official app  from https://www.postman.com/downloads/
> 2. Copied the certificate from ~/.config to ~/.var
> 
> ```
> cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman
> ```

Based above works for me on Fedora Linux 40 (Workstation Edition):

```
ln -s ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman/proxy
```

P.S.: probably needs to be removed before:

```
rm -rf ~/.var/app/com.getpostman.Postman/config/Postman/proxy/
```

**Comment by itokun99** [comment]
> For anyone else creating the certificate manually and facing the same issue with the following command:
> 
> ```
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> Make sure you do so in the correct folder (cd into it beforehand). You can find it by running `flatpak run com.getpostman.Postman` and looking in the terminal. For example in my case: `/home/{user}/.var/app/com.getpostman.Postman/config/Postman/proxy/`
> 
> cc: @All3xJ

from me, fixed by this comment, smoth after install from flatpak :)

**Comment by phpclub** [comment]
Same problem 
Ubuntu 24.04 
cd folder + make sert

**Comment by lebowsskii** [comment]
Same problem
Fedora 40
```
cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
```
Worked for me

**Comment by hlafaille** [comment]
Still have this issue. Running the above suggested openssl command fixes the problem.

NAME="Linux Mint"
VERSION="21.3 (Virginia)"
Linux pc 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ronrodrigues** [comment]
> Same problem Fedora 40
> 
> ```
> cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> Worked for me

Yeah, worked for me too.

**Comment by BlakeGardner** [comment]
Having the same problem on Fedora 40.

**Comment by vzolin** [comment]
Confirm that the same issue returned on Fedora 40.

Also confirmed that the workaround works

**Comment by ahmedulfuad** [comment]
>I have the same issue. I fixed following this steps:
Downloaded and executed the official app from https://www.postman.com/downloads/
Copied the certificate from ~/.config to ~/.var
`cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman`

Worked for me on Zorin OS 17. Thanks @rolodoom.

**Comment by ahmedulfuad** [comment]
> I have the same issue. I fixed following this steps:
> 
> 1. Downloaded and executed the official app  from https://www.postman.com/downloads/
> 2. Copied the certificate from ~/.config to ~/.var
> 
> ```
> cp -r ~/.config/Postman/proxy ~/.var/app/com.getpostman.Postman/config/Postman
> ```
Worked for me on Zorin OS 17. Thanks @rolodoom.

**Comment by wwk-github** [comment]
> Having the same problem on Fedora 40.

I had a similar problem.
Just make sure you have openssl installed (like dnf install openssl).

wget postman-linux-x64.tar.gz
tar xvzf postman-linux-x64.tar.gz
Postman
./Postman

Fedora 40 - seems to be working that way.

**Comment by vhdmoradi** [comment]
> @guilhermesousa-cwi for the flatpak wrapper make sure you execute the command [above](https://github.com/postmanlabs/postman-app-support/issues/12330#issuecomment-1730195683) inside the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy` after that it should look like the following:
> 
> ![Screenshot from 2023-09-25 12-42-31](https://private-user-images.githubusercontent.com/63073056/270360518-148abeeb-0536-4936-9e2e-a9cc0a72f338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzQ4NzMsIm5iZiI6MTczMTIzNDU3MywicGF0aCI6Ii82MzA3MzA1Ni8yNzAzNjA1MTgtMTQ4YWJlZWItMDUzNi00OTM2LTllMmUtYTljYzBhNzJmMzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwMjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzg1ZGE0NTJlYTU0NTY3MjU0NWU1NGZiOWRkNjc4OTViN2M1YTQ3ZTg4YWVkNTA3NTZhMzA4ZGExNmUyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J7Ypn7hZMB0CqjVtlpxD0sCc3Ban7a8e_CS37tEd9xE)

This Solved my problem.

**Comment by Tamal** [comment]
Upgraded to Fedora 41 user and faced the same problem. The above solution worked for me.

```
cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
```

**Comment by munje** [comment]
> Have the same issue, as a workaround I manually create the certificates in `~/.var/app/com.getpostman.Postman/config/Postman/proxy`
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> ([#11620 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639))

Dec 5 2024 - the problem still persists :(
Above fix works for me again .. I forgot I did it already last year

Fedora 41
Gnome 47
Postman v11.21.0  - installed via flat

**Comment by ZODIAC3K** [comment]
> Upgraded to Fedora 41 user and faced the same problem. The above solution worked for me.
> 
> ```
> cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```

yes it work's.
On Fedora 41 installed Postman from Flatpack.

**Comment by ralphm123** [comment]
> Same problem Fedora 40
> 
> ```
> cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```
> 
> Worked for me

This worked for me too on Mint

**Comment by maisonhai3** [comment]
> Upgraded to Fedora 41 user and faced the same problem. The above solution worked for me.
> 
> ```
> cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> ```

This works on Ubuntu 24.04.
