### ISSUE TITLE
Can't export collection because endless loading at "Export collection" window

### ISSUE THREAD

**Issue by veraaleksandrovna** [a85/POSTMan-Chrome-Extension#13423]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While I try to Export collection the "Export collection" window doesn't load

### Steps To Reproduce

1. Open your workspace
2. Select collection
3. Click "View more actions"
4. Choose "Export"

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/232c89a9-cf84-4ad9-8571-2bc65f67586d)

### Operating System

macOS

### Postman Version

11.30.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The problem was reproduced several times at my colleagues computers

**Comment by vedkribhu** [comment]
Hi @veraaleksandrovna, I am not able to reproduce the issue on my end. Can you help me with the following to debug this further:
1. Is this happening for all your collections?
2. Is this happening consistently for you, even after restarting the app?
3. Is this happening on both postman web and app?

**Comment by veraaleksandrovna** [comment]
Hi @vedkribhu  ! 
1. Yes, it's happening for each collection in my workspace.
2. Yes. I tried to restart the postman for 3 times.
3. I've checked both web and desktop app, the problem is reproducing.

**Comment by veraaleksandrovna** [comment]
In addition, we've checked the same problem on Windows and Ubuntu laptop. Everything works correctly

**Comment by vedkribhu** [comment]
@veraaleksandrovna 
Could you once try logging out and logging back into the Postman App?

If this doesn't fix your issue, can you please send an email to [support@postman.com](mailto:support@postman.com) from your email address that is registered with Postman? It'll help us figure out the issue from our end better. In your email, please add a reference to this GitHub issue's link. Thanks!

**Comment by andrybany** [comment]
I have the same problem

Operating System
Windows

Postman Version
11.44.0

Postman Platform
Postman App

User Account Type
Signed In User

**Comment by johnm123** [comment]
Hi,

I also had the same issue but accidentally found a workaround which may help someone. 

OS: MacOS Sequoia
Version: Postman 11.43.5

I found nothing worked, including fully removing Postman and reinstalling. I was consistently unable to export any collection. 

Where I had some luck was when I did the following, so may be worth trying:

-  Fully uninstalled Postman as per official instructions.
- Reinstall but select Lightweight mode instead without logging in. 
- After doing this I logged in, reverting to the normal mode and I seemed to be able to export again. 

No idea why this worked however.

**Comment by johnm123** [comment]
Same problem. Thought it was resolved but appears not to be. The only thing that appears to work is signing in with a new account.

Operating System
MacOS

Postman Version
11.44.0

Postman Platform
Postman App

User Account Type
Signed In User

**Comment by davmaene** [comment]
> Same problem. Thought it was resolved but appears not to be. The only thing that appears to work is signing in with a new account.
> 
> Operating System MacOS
> 
> Postman Version 11.44.0
> 
> Postman Platform Postman App
> 
> User Account Type Signed In User



> ### Is there an existing issue for this?
> * [x]  I have searched the tracker for existing similar issues and I know that duplicates will be closed
> 
> ### Describe the Issue
> While I try to Export collection the "Export collection" window doesn't load
> 
> ### Steps To Reproduce
> 1. Open your workspace
> 2. Select collection
> 3. Click "View more actions"
> 4. Choose "Export"
> 
> ### Screenshots or Videos
> ![Image](https://github.com/user-attachments/assets/232c89a9-cf84-4ad9-8571-2bc65f67586d)
> 
> ### Operating System
> macOS
> 
> ### Postman Version
> 11.30.0
> 
> ### Postman Platform
> Postman App
> 
> ### User Account Type
> Signed In User
> 
> ### Additional Context?
> The problem was reproduced several times at my colleagues computers



> Same problem. Thought it was resolved but appears not to be. The only thing that appears to work is signing in with a new account.
> 
> Operating System MacOS
> 
> Postman Version 11.44.0
> 
> Postman Platform Postman App
> 
> User Account Type Signed In User

**Comment by richa2988** [comment]
I am also facing same issue.
This was working before but suddenly seeing this export issue.
Kindly resolve this issue.

![Image](https://github.com/user-attachments/assets/71daca06-9d71-4a44-a769-fbf6a01258a4)

**Comment by javor454** [comment]
Hello, i encountered the same problem. Im pretty sure it worked 2-3 weeks ago now i cant export any collection, environments work fine. I tried it on mac client, ark and safari browser with same effect.

Mac client version:
Version 11.44.2
UI Version: 11.44.2-ui-250506-0337
Desktop Platform Version: 11.44.0 (11.44.0)

**Comment by GiovanniMistura** [comment]
Today i tried to export a collection and i had the same problem.

Operating System
Windows

Postman Version
11.44.6

Postman Platform
Postman App

User Account Type
Signed In User

**Comment by priyanshu-coditas** [comment]
Getting same on Windows

**Comment by collins-nc** [comment]
Updated to Postman v11.46.5, issue should be fixed

**Comment by emersonline86** [comment]
Same problem here on version 11.47.4. Both Windows desktop app and online environment have the same issue.

**Comment by davmaene** [comment]
You have just to update to latest version of Postman and the issue will be
resolved

**Comment by emersonline86** [comment]
> You have just to update to latest version of Postman and the issue will be
> resolved
> […](#)

11.47.4 is the latest version

**Comment by FeehGb** [comment]
Same problem here on version of Postman v11.48.3.

**Comment by emersonline86** [comment]
Updated Postman to version v11.48.3, but the bug is still present. As previously reported by other users, it seems to be related to specific accounts. On my main Postman account, I am unable to export any collection. However, when logging into another account, the export process works fine. Returning to the main account, the issue persists—an endless loading screen appears after clicking the export collection option.

**Comment by emersonline86** [comment]
I tested the project export today and it started working normally again. Coincidentally, the trial period and messages for upgrading Postman to a higher plan had expired. I suspect that two things must be related and that's why it wasn't happening for all accounts. In my secondary account, there were no messages asking me to upgrade. This would also explain why the problem happens sporadically with different users on different versions. May other users facing the same problem could confirm this context.

**Comment by richa2988** [comment]
Yes, it started working for me as well. When I stopped using shared
workspace.

**Comment by kartikjain26** [comment]
Hey folks, just popping in here to check if this is still an issue or it works for you guys ?

**Comment by shivabhaggan2024** [comment]
@kartikjain26 the issue is still there for me
I am not even logged in and running on Version `11.55.3`

Update:
Closing and reopening the app did the trick.

**Comment by kartikjain26** [comment]
thanks @shivabhaggan2024 . closing this ticket. Please update your app and relaunch.
