### ISSUE TITLE
Postman hangs when trying to make a request and doesnt start the request process for 15sec - 45sec

### ISSUE THREAD

**Issue by apla1297** [a85/POSTMan-Chrome-Extension#13682]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After upgrading to version 11.55.2 all calls made from a specific collection hang when trying to call anything. Postman just waits 15-45 seconds before starting to make the call. When the call does finally fire it returns from the API in a normal amount of time. I'm also able to replicate this when the API isn't running which i would expect an immediate connection failed error but it still hangs for 15-45 seconds. Calls not in a collection work as expected. There are no scripts or other pre flight items on the collection. I can replicate this on multiple computers across MAC and Windows platforms. 

[EDIT] : I thought it was bound to the collection, its not, its bound to the auth token. Whenever i use the OAuth2 saved token it freezes up. New video added.

### Steps To Reproduce

https://github.com/user-attachments/assets/f2e4e238-4b61-40e9-b183-7f9115519d8b

https://github.com/user-attachments/assets/6b4fefc1-658b-4872-8bc5-04cdfa0ab423

### Screenshots or Videos

See above

### Operating System

Windows

### Postman Version

11.55.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by apla1297** [comment]
UPDATE: I was able to confirm that the issue does not persist on previous versions of Postman

**Comment by pedrocmota** [comment]
Same problem.

**Comment by DSchau** [comment]
Can confirm the issue. Seems to be a delay of 15-20+ seconds on request send specifically with the OAuth authentication type, and manifests in (at least) v11.55.2. 

We will investigate and fix! Thanks for the helpful reproductions, videos, and examples.

**Comment by grantsunny** [comment]
I second this. This happens only about latest version and confirmed that latest version of Desktop Agent does not have this problem.

**Comment by coditva** [comment]
Hey all, thanks for reporting and apologies for the inconvenience caused. I'm happy to report that we've fixed this issue in the latest release (`v11.55.3`)! Please update and let us know if you're still facing any issues.

**Comment by apla1297** [comment]
Confirmed the issue has been resolved in 11.55.3

Thank you @coditva @DSchau

**Comment by apla1297** [comment]
Update: This is still happening, however, its much harder to reproduce now, and closing all tabs in postman and then reopening the call you are working on seems to solve the issue. Ill try to dependably re-create the issue, but 3 times now randomly I've had the same lockup. It seems to happen when duplicating or moving requests that use OAuth 2, but i cant get it to happen all the time.

**Comment by coditva** [comment]
@apla1297 Would you be able to send us the logs to investigate further?
Here's how you can find the logs: [How to get logs from the Postman Desktop app](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ).

Please send us the logs on help@postman.com citing this GitHub ticket ID. It would really help to debug this faster.

**Comment by apla1297** [comment]
[logs.zip](https://github.com/user-attachments/files/21411797/logs.zip)

Let me know if there is anything else i can provide, still trying to replicate but i cant pinpoint the cause

**Comment by pedrocmota** [comment]
I confirm that the issue still persists in v11.55.3, although it is much rare.

**Comment by coditva** [comment]
@apla1297 / @pedrocmota I haven't been able to replicate this. I tried duplicating the requests as well as tabs but can't replicate this case. Can you share more info on what's your workflow like? Any steps that you perform and any info on number of tabs open, whether it's saved/unsaved request, etc.? If getting on a call is easier, we can schedule something next week.

**Comment by apla1297** [comment]
For me everything has been saved tabs with 5-7 calls. That's said, its become less and less frequent as time has gone on, any chance there remanence from the fix you guys did and as meta data and other things get over written the problem will self solve? Because its not happening much at all now.

**Comment by coditva** [comment]
@apla1297 Not sure if that should be the case. The fix should be one-shot. In any case, let me know if you see this more often or there's some specific case you can narrow it down to. I'll keep my eyes open for similar issues if anyone else reports.

**Comment by coditva** [comment]
@apla1297 I'll close out the issue for now since we've not been able to replicate it. You can re-open it or create a new issue if you encounter it again. Thanks for reaching out and all the help with the logs! 🙂

**Comment by Aroniez** [comment]
Still experiencing it in v11.69.2
Restarting it fixes the issue. I experience it every single day on Windows 11 PC

**Comment by XeroDays** [comment]
The issue still in the version : 
```
Version
11.82.3
UI version
11.82.3-ui-260128-0255

Desktop platform version
11.82.1

Architecture
x64

OS platform
win32 10.0.26100
```


<img width="1294" height="376" alt="Image" src="https://github.com/user-attachments/assets/3f8d524f-d31d-4ff2-a568-35f60d4e887b" />

**Comment by coditva** [comment]
@XeroDays The screenshot you've shared seems to be a different issue where the request tab is not opening at all. Would you mind opening a new issue and attaching more info about it there? Thanks!
