### ISSUE TITLE
Tab consistently hangs everytime after machine wakes from sleep / hibernation

### ISSUE THREAD

**Issue by zehawki** [a85/POSTMan-Chrome-Extension#13800]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Consistently happening EVERY single time laptop wakes from sleep / hibernation with Postman open (it always is). Clicking on "Send" does nothing for ever - 
1. no actual network call is made
2. spinner does not show
3. call does not appear in console
4. the tab hangs
5. the button is greyed out with "Cancel" and is unresponsive

At this point I can open a new tab, and start a new request in it - that also results in the same behavior as mentioned. Postman app is responsive, the tab is not.

Only way to recover is to close and reopen Postman app, and then its fine - until the next wake from sleep.

See screenshot where I am doing a call to https://reqbin.com/echo/get/json, it will just stay in this state for ever. 

### Steps To Reproduce

1. Make any request, eg make a GET to https://reqbin.com/echo/get/json - should be fine
2. Leave Postman and tab open
3. Put Windows to sleep
4. Wake from sleep and try to run the same request from the previously opened tab

### Screenshots or Videos

<img width="897" height="840" alt="Image" src="https://github.com/user-attachments/assets/ab24940c-9de6-4190-8e89-704f15866b03" />

### Operating System

Windows

### Postman Version

11.66.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Version 11.66.0

UI version 11.66.0-ui-251006-0112

Desktop platform version 11.65.4

Architecture x64

OS platform win32 10.0.26100

**Comment by Yoonassh** [comment]
Same here. Started after last update.
Also sometimes tab become broken with error like "no resources found" (I will try to update with screenshot later).
Another frequent error is not uploading file even it exists. The fix is to remove and add same file again. Actually it's only occasionally NOT happen. It's almost constant issue now.

All issues started after last update to 11.66.1

**Comment by aistvan** [comment]
Same happening here. I cant work. Switched to another app temporary.

**Comment by kalvaabhinav** [comment]
I hope a fix will be available soon for this issue. I hate to close and reopen the application every time the computer goes to sleep.

**Comment by michaelthedev** [comment]
Same for me, happening for a while now, the support agents said they haven't received any similar report

<img width="2219" height="341" alt="Image" src="https://github.com/user-attachments/assets/c23c9d6a-8e20-428f-b550-6b9bf8ec81e7" />

**Comment by zehawki** [comment]
> the support agents said they haven't received any similar report

Funny guys. Guess they cant be bothered to even look at bug reports on their own repo.

**Comment by coditva** [comment]
Hey everyone, I haven't been able to replicate this on Windows on my end. Would it be possible to share application logs to help me debug this further? Here's how you can do this: [How to collect application logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ)

1. Open View > Developer
2. Select View Logs in Finder (macOS) / View Logs in Explorer (Windows) / View Logs in File Manager (Linux). Your OS file manager will open the logs directory which contains your application logs.
3. Select all files and create a single .zip file.

You can email us the logs at help@postman.com and mention this issue.

---

Alternately, it would help debug this faster if we can get on a call. You can use this link to book a time slot: https://calendar.app.google/yW9RXguAD3bF26bk9

**Comment by mattgentle** [comment]
Yep, also seeing this since last / last but one update (now on v11.68.2).

@coditva, have suggested a time for a call on the calendar.

**Comment by coditva** [comment]
@mattgentle Thanks for reaching out! Unfortunately I haven't got the calendar invite. Can you try again? I've also increased the number of slots for your time zone.

**Comment by zehawki** [comment]
Still the same in subsequent versions (now on 11.69.2)

**Comment by ivan-gospodinov** [comment]
I confirm that the issue exists in version 11.69.2. I have sent my app logs to the email mentioned above.

**Comment by aistvan** [comment]
I would confirm that with the latest update the problem still exists.
My postman hangs after a long sleep at the first call.
I have to use other tools to do my work.

**Comment by michaelthedev** [comment]
Any update on the call @coditva ?

Having to close and reopen postman every time I unlock my pc is not very nice

btw, Saw these errors/warnings when i checked dev tools if it means anything

<img width="2194" height="1137" alt="Image" src="https://github.com/user-attachments/assets/8388bc34-4b7f-421e-b834-3c85359ad3f7" />

**Comment by mattgentle** [comment]
@coditva, apologies, work got in the way.  Will look for a new calendar slot now.  Tried to take a screen recording too

![Image](https://github.com/user-attachments/assets/f9f5e33e-931f-4ea8-96d6-b9c06676b922)

**Comment by coditva** [comment]
Thanks everyone for sharing logs and screenshots. 🙌🏼  We've been able to replicate the issue and are working on a fix. I'll post the updates here once we fix it.

**Comment by coditva** [comment]
Hi everyone, we have fixed the issue in Postman `v11.69.6`. Please update the app and let us know how it goes!

**Comment by kalvaabhinav** [comment]
Things are looking better after the update.

**Comment by zehawki** [comment]
Working just fine, thank you @coditva and Postman devs.

**Comment by mattgentle** [comment]
Yep, looks good now, thanks guys

**Comment by michaelthedev** [comment]
am i the only one experiencing this again in v11.74.5?
it was fixed before

**Comment by zehawki** [comment]
Ah yes, same for me on:

Version
11.74.5
UI version
11.74.5-ui-251205-0111

Desktop platform version
11.74.5

Architecture
x64

OS platform
win32 10.0.26200

**Comment by mattgentle** [comment]
Yep, back for me too on 11.74.5

**Comment by coditva** [comment]
Thank you for notifying that the issue is back. It helps us get closer to the fix! Apologies that it's happening again. We're working on it and you can expect a fix soon.

**Update: It is now fixed in `v11.75.1` onwards.**

**Comment by coditva** [comment]
I hope no one has been experiencing this since last time. I'll be closing this issue out. In case anyone faces this again, please let us know.
