### ISSUE TITLE
response not coming while hit the API and stuck in cancel button

### ISSUE THREAD

**Issue by fluvinu** [a85/POSTMan-Chrome-Extension#13805]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We need to restart Postman to resolve this issue.
First, we hit the POST API. The blue "Send" button changes to "Cancel," but it gets stuck there.
The request doesn't reach the API, and no response is returned.
To get out of this state, we have to restart the Postman app on Windows.
 

### Steps To Reproduce

1) Write a POST API for login or something similar.

2) Hit the "Send" button.

3) Sometimes it gets stuck there — no response comes back, and it's not possible to cancel the request either.

### Screenshots or Videos

<img width="631" height="152" alt="Image" src="https://github.com/user-attachments/assets/72902e36-1863-4991-8524-93b89be92b58" />

<img width="630" height="370" alt="Image" src="https://github.com/user-attachments/assets/6110056a-6b25-46be-b0dd-94b20aadfafc" />

### Operating System

Windows

### Postman Version

11.66.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by coditva** [comment]
@fluvinu Thanks for reaching out. Would it be possible to share the application logs? ([How to get logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app))
You can email us the logs at help@postman.com and mention this ticket.

Also, can you check if this issue also exists in the web version (postman.com)?

**Comment by fluvinu** [comment]
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/fb9836f8-1071-4a93-a78d-2f401b003baa" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1032d935-feab-4880-82e6-8660b6d4a365" />

@coditva  please see this

**Comment by fluvinu** [comment]
I cant share har file hope you understand

**Comment by coditva** [comment]
@fluvinu you don't have to share the HAR files. That's ok. We just need the application logs to debug.

How to collect application logs

Launch the Postman Desktop app and then follow these steps:

Open View > Developer

Select View Logs in Finder (macOS) / View Logs in Explorer (Windows) / View Logs in File Manager (Linux).

Your OS file manager will open the logs directory which contains your application logs.

Select all files and create a single .zip file.

**Comment by fluvinu** [comment]
I can mail you that right ? ok

**Comment by coditva** [comment]
@fluvinu Yes, you can mail us at help@postman.com. Also can you confirm if you are able to see the issue in web https://www.postman.com ?

**Comment by rzaq-alshoshan** [comment]
I have a similar issue.
Here is the log attached

[postmanlog.txt](https://github.com/user-attachments/files/22903736/postmanlog.txt)

**Comment by coditva** [comment]
@fluvinu @rzaq-alshoshan Would either of you be able to get on a short call to debug this issue further? Here's a link that you can use to schedule: https://calendar.app.google/tsjNTD3CwSH4QbxE8

**Comment by wiggisser** [comment]
@fluvinu Any chance this is always/only happening after windows woke up from sleep/hibernation? Could be the same as #13800

**Comment by rzaq-alshoshan** [comment]
There is no clear way how it is happening, but from what I observed it happens after I clean my workspace.
By this I mean, closing unwanted open tabs, saving unsaved requests/projects, or reordering tabs, etc. 
At least in these times I noticed the weird behavior which won't get solved until the complete Postman app is closed and reopened.

**Comment by tapetfjes** [comment]
Hi, I am regularly experiencing this issue as well, requests seemingly sending, nothing happens, no way to cancel.
Restart of application is the only remedy, which is fairly annoying.
It could be related to updating environment variables, but I am not certain.

**Comment by LC805** [comment]
Good Morning,

Glad to see this post. I am also seeing this issue when sending a request and no response is returned. The Cancel button shows enabled however it has no action when selected. It is happening in both Desktop and the browser version. It appears intermittent and noticable to me only after the recent AWS outages were resolved. Closing the window and restarting clears the issue for a while. I am also on Windows. I saw it happen again on after this morning’s Postman update to **version 11.68.5** between 8:00am - 8:40am EST. Another colleague also mentioned he is having the same issues.  I have seen this occur on various requests methods and not specific to POST. 

Thanks,
Laurie Conley

**Comment by blackhat-coder** [comment]
Hello, I have the same experience
After I click the Send button, nothing happens.. Tried clicking the Cancel button but nothing happens. My only way of resolving is to restart the application.

Thanks.

**Comment by richja** [comment]
Can confirm this issue as well. Only on desktop app, Windows. 
It works after app restart but after few mins (let's say 10, and no sleep or hibernation in between), the issue is back.

**Comment by fluminis** [comment]
Hello,
Same bug here. Windows ; Postman v11.69.0
My only way of resolving is to restart the application.
Thanks.

**Comment by ravindra-singh-amla** [comment]
Same issue we are facing as well.

<img width="884" height="127" alt="Image" src="https://github.com/user-attachments/assets/dcfc4f86-f037-4069-b573-c4d895627232" />

**Comment by carlosedsferreira** [comment]
Same happens to me and it seems related with PC being to sleep or hibernation. If continuous work doesn't happen

**Comment by samyan** [comment]
Same here, with postman 11.69.2 on win11

**Comment by Samgrocock** [comment]
same here on Windows 11 enterprise, Postman v11.69.2

**Comment by jancysebastian** [comment]
I have the same issue Version
11.69.4

**Comment by rfancheX** [comment]
Seeing the same issue, 11.69.2, saw the same behavior in 11.69.0, restart app resolves the issue

**Comment by coditva** [comment]
Hi everyone, thank you for your patience. This issue has been fixed in `v11.69.6`! Please update the app and let us know if you're still facing any issues.

**Comment by coditva** [comment]
I hope no one has been experiencing this since last time. I'll be closing this issue out. In case anyone faces this again, please let us know.

**Comment by Etiabasi** [comment]
hello @coditva , i have just hit this on version 11.80.4 while streaming some batched data on windows desktop app.

**Comment by avichovatiya67** [comment]
facing same issue on ubuntu
@coditva

**Comment by oatyuttha** [comment]
I'm on Gentoo, I found that the console keep telling me this `libsecret-1.so.0` is not found, so for me just install the lib and everything came back to work.

Hope it help!
