### ISSUE TITLE
Variables with empty value are being resolved as the word "null"

### ISSUE THREAD

**Issue by kbhutchinson** [a85/POSTMan-Chrome-Extension#1533]
In the past, variables with an empty value have resolved to nothing. For example, the following:

![emptyvar](https://cloud.githubusercontent.com/assets/8618197/10791437/d5f82300-7d5e-11e5-9093-169ede9102c8.png)

with the request `http://{{subdomain}}host.com/` would resolve to `http://host.com`. However, now empty variables are resolving to the word "null", so that the same request is resolving to `http://nullhost.com/`.

Due to quirks of our network configuration, some host names in our QA environment have different prefixes than those in our production environment, and I've been managing that by setting up different Postman environments with some variables being left empty so that the same collection would work with either environment.

That's been working fine. I'm not exactly sure when this issue started, as I haven't made requests to these affected endpoints for a while.

I'm currently running version 3.0.25 of the packaged app.

**Comment by ghowar** [comment]
Also seeing this:

Runner treats empty key values differently from Builder
Builder will fire key value=""
Runner will fire key value="null"
This means that tests pass/fail differently depending on where they are run from.
Version 3.1.0.0 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
@ghowar Thanks for pointing this out. We'll work on this soon.

**Comment by Chris-thomson** [comment]
@ghowar Good Spot!

**Comment by caseymarcallen** [comment]
+1 on getting this bug resolved. I just migrated a large number of collections and environments over to the packaged app and am now being tripped up by this issue.

**Comment by lonsun** [comment]
+1 on getting this bug resolved.  My situation is similar to the initial commenter's.   E.g. "app1" looks like "http://localhost/app1/login" on my local environment, but on QA it looks like "http://app1.example.com/login".

Chrome version  46.0.2490.86 (64-bit).

From the about section in postman:
Version 3.2.1 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by dewdad** [comment]
+1 Please resolve this issue. Many of the environments I have setup have stopped working because of this regression. I have started looking around for alternatives to your wonderful product just because of this issue.

**Comment by abhijitkane** [comment]
@dewdad Can you confirm this fixed in v3.2.8 of the app?

**Comment by kbhutchinson** [comment]
Updated to v3.2.8 and this issue seems resolved. Thanks.

**Comment by lonsun** [comment]
I just tried with v3.2.8 and it worked for me as well.  Thanks!

**Comment by dewdad** [comment]
I'm still facing the issue, but instead of being null, it is the variable template itself being used. This should not be possible I think. I believe that in the case of an undefined variable scenario an empty string should be used as the value. This would make the most sense and would allow for contexts to not define variables that are irrelevant respectively.
![postmanbug](https://cloud.githubusercontent.com/assets/6195827/12041160/6cabce98-ae77-11e5-9907-cb63813c30e0.jpg)

**Comment by abhijitkane** [comment]
This is intended behavior. Having a blank variable and not having a variable should produce different results. We'll look at ways to identify variables that have not been declared in the selected environment. A warning near `{{varName}}` if `varName` is undeclared, perhaps.

**Comment by dewdad** [comment]
Different results... I"m not sure. But I cannot foresee anyone wanting to use the {{varname}} template itself.

**Comment by gcbartlett** [comment]
I agree with @dewdad that passing `{{varName}}` when the variable is currently undefined is seldom desirable, especially when it's being sent as a _param_, where you can't simply 'uncheck' the parameter to not send it.

Additionally, it appears that trying to programmatically (via a _Pre-request Script_ or a _Test_) set a variable to empty  (e.g. `postman.setGlobalVariable("varName", "")` or `postman.setGlobalVariable("varName", null)`) removes the variable, leaving you in the same situation as above.

**Comment by sdnts** [comment]
@gcbartlett That's a known bug. We've fixed this, and it'll be out with the next release. You can track it here: https://github.com/postmanlabs/postman-app-support/issues/2596

**Comment by gcbartlett** [comment]
Thanks @madebysid. I look forward to this next release, or is there a way to get a developer/nightly build earlier than this?

**Comment by neha19988** [comment]
Hey i have an issue like in post api there are 14 parameters so i have to test positive scenario as well negative  so in negative if there will be any null value 
i have to give a msg like provide valid value for  that in pre request script i write 
let swicthCaseIteration= +pm.environment.get("swicthCaseIteration");
 switch(swicthCaseIteration) {
  case 0:( for postive)
pm.environment.set("userMobileNumber", +pm.environment.get("userMobileNumber")+1);
pm.environment.set("i", +pm.environment.get("i")+1);
//pm.environment.set("userName", +pm.environment.get("userName")+1);
pm.variables.set("addressOne", "delhi");
pm.variables.set("addressTwo", "varansi");
pm.variables.set("cityCode", "IN-BR-DH");
pm.variables.set("countryCode", "IN");
pm.variables.set("domainId", 75);
pm.variables.set("emailId", "emailId3{{i}}@gmail.com");
pm.variables.set("firstName", "automate");
pm.variables.set("lastName", "string");
pm.variables.set("mobileCode", "+91");
pm.variables.set("mobileNumber","{{userMobileNumber}}");
pm.variables.set("orgId", 170);
pm.variables.set("roleId", 4);
pm.variables.set("stateCode", "IN-BR");
pm.variables.set("userName", "automation98{{i}}");
pm.variables.set("zipCode", "656689");break;
 case 1: (for negative
pm.variables.set("addressOne", null );
pm.variables.set("addressTwo", "varansi");
pm.variables.set("cityCode", "IN-BR-DH");
pm.variables.set("countryCode", "IN");
pm.variables.set("domainId", 75);
pm.variables.set("emailId",  "emailId3Negativee{{i}}@gmail.com");
pm.variables.set("firstName", "automate");
pm.variables.set("lastName", "string");
pm.variables.set("mobileCode", "+91");
pm.variables.set("mobileNumber","5678907898");
pm.variables.set("orgId", 170);
pm.variables.set("roleId", 4);
pm.variables.set("stateCode", "IN-BR");
pm.variables.set("userName", "automation98Negativee{{i}}");
pm.variables.set("zipCode", "656689");break;
case 2:
So like this i write 14 cases by providing null value respectively and in test i use switch case like 
If switch iteration===1 then print provide valid address 
But problem is that in pre request no of lines is 300 so how can i reduce it
