### ISSUE TITLE
POST form-data does not upload Filedata

### ISSUE THREAD

**Issue by mikefadhl** [a85/POSTMan-Chrome-Extension#1843]
Version: 4.0.1
After choosing file to POST the filename is undefined, this what the generate code looks like:

POST /profile/services/users/6633580729/avatar?maxSize=350 HTTP/1.1
Host: ecn91-www.nikedev.com
Cookie: slCheck=4YSKqJWXbZk9coFlCFcWxq/ufWmHFiYtI2vQ5PR72jBMO5uJitOUED3yHMK3Ol/vLPGpC/C9UUHEaJ0qWRJ92A==
Cookie: sls=3
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Filedata"; filename="undefined"
Content-Type: undefined

----WebKitFormBoundary7MA4YWxkTrZu0gW

**Comment by abhijitkane** [comment]
@mikefadhl We've fixed this in our internal build, and will slowly be rolling out the fix to all users over the next few days.

**Comment by jeremymills** [comment]
~~getting this in v4.1.0, what is the status of the release ?~~ resolved in v4.1.2

**Comment by rayfaddis** [comment]
I still experience this with version 4.1.2

> ----WebKitFormBoundary7MA4YWxkTrZu0gW
> Content-Disposition: form-data; name="document"; filename="undefined"
> Content-Type: undefined

**Comment by abhijitkane** [comment]
@rayfaddis Is this from the HTTP Preview? The code generation module doesn't handle filenames right now. Can you try posting a file to POST http://echo.getpostman.com/post? The response should contain the filename.

**Comment by rayfaddis** [comment]
@abhijitkane yes I was looking at the preview via Generate Code. Though the file still isn't actually being submitted for me which is why I'm noticing this at all.

I submitted a POST to http://echo.getpostman.com/post as well and no file in the response.

**Response:**

> {
>   "args": {},
>   "data": {},
>   "files": {},
>   "form": {
>     "test": "Where's my file yo?"
>   },
>   "headers": {
>     "host": "echo.getpostman.com",
>     "content-length": "154",
>     "cache-control": "no-cache",
>     "origin": "chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo",
>     "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryzgTHweCUXo5RYWT7",
>     "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36",
>     "postman-token": "77756393-cf69-7fad-8ab3-457a92527023",
>     "accept": "_/_",
>     "accept-encoding": "gzip, deflate",
>     "accept-language": "en-US,en;q=0.8",
>     "cookie": "_ga=GA1.2.175529458.1455220529; sails.sid=s%3AFtAqSgj4Ty4dNjquAXCaTsZXzSBuYtGN.0u3zxmUrazbgj0G0UjbPJttkKI3X%2Bwdrzvv34VENDbk"
>   },
>   "json": null,
>   "url": "http://echo.getpostman.com/post"
> }

**Form-Data**
![postman](https://cloud.githubusercontent.com/assets/1969780/13963864/9ba1c330-f03d-11e5-9592-b5fc4dab92b7.png)

**Chrome Extension Version**
![extensions](https://cloud.githubusercontent.com/assets/1969780/13963985/0d630024-f03e-11e5-827e-a3941bc6fe8c.png)

**Comment by jeremymills** [comment]
@abhijitkane using postman to POST to `echo.getpostman.com/post` does not show the filename or parameters for me either, it seems the implementation or the dependencies between them may have been broken. My implementation of POST for my api receives the postman's POST with the file and all data without problem, all the testing I have done shows that POSTMAN itself is working properly.

I am wondering how `echo.getpostman.com/post` is receiving the data, and if there may be a broken link in there?

**Comment by rayfaddis** [comment]
@abhijitkane @jeremymills I stumbled across issue #1908 and have confirmed my issue is exactly the same as the one described there, if I submit files without spaces on version 4.1.2 they go through successfully. @jeremymills not sure if your tests included a file with spaces or not. It seems my comments here are more so related to that issue and not the bug that was previously fixed in this issue.

Looking forward to the next release that includes that fix :smile: Thanks for the help :+1:

**Comment by jeremymills** [comment]
@rayfaddis funny that issue was brought up I submitted an encoding issue #1874 that upon further investigation came down to exactly that, spaces not getting encoded properly.. looking forward to next update as well!

**Comment by shamasis** [comment]
seems like in Postman v4.5+ the app does not crash when uploading large files in form-data mode. The binary mode is still crashing though.
