### ISSUE TITLE
Feature Request: Open link in default browser

### ISSUE THREAD

**Issue by jimonthebarn** [a85/POSTMan-Chrome-Extension#2030]
When clicking links in postman the current default behaviour is to open a new tab with the request url pointing to the link location.

What I really would like to be able is to open the link in the default browser instead. To not break existing behaviour maybe by using an modifier key like CTRL + click.

Motivation: 
A couple of API's we are developing at our company generate redirect urls and return them via the response body. These urls need to be opened in a browser to proceed with the underlying process. Since postman opens links in a different tab inside postman the workflow usually is:
- click on the link (new tab is opened)
- set focus on request url in new tab -> ctrl-a -> ctrl-c
- fire up browser -> open tab -> ctrl-v - enter

Cheers,
Ben

**Comment by haidaraM** [comment]
Any news about this feature ?

**Comment by invernizzie** [comment]
Much needed.

**Comment by Millais** [comment]
Is this feature being considered? (It would really help with certain types of workflows)

**Comment by Seb-degraff** [comment]
+1

**Comment by StephenGoodall** [comment]
+1
would be good if we could define what tag (in the case of an XML response) the URL is in, so that it auto follows the URL

**Comment by wheavin** [comment]
+1

**Comment by gzur** [comment]
+1

**Comment by marsie84** [comment]
+1

**Comment by norcino** [comment]
+1

**Comment by mraty** [comment]
+1

**Comment by mrbapa** [comment]
+1

**Comment by TopherGopher** [comment]
+1

**Comment by cirick** [comment]
+1

**Comment by ratsdiov** [comment]
+1

**Comment by yakup38** [comment]
+1

**Comment by Millais** [comment]
The type of scenario where this would be beneficial is with HATEOAS links that require manual user interaction: e.g authentication in the browser.

Really like @jimonthebarn's idea to use a simple modifier combination like _cmd + click_ to access this feature.

![screen shot 2017-11-14 at 10 44 42 am](https://user-images.githubusercontent.com/7149113/32775964-e93ea944-c928-11e7-9070-07078efae8e7.png)

**Comment by silviucotilici** [comment]
+1. It will save tons of time

**Comment by n1k1ch** [comment]
+1

**Comment by MrAaronOlsen** [comment]
+1
I've had a few scenarios where I've wanted the response, not just a link from preview, to pop open my default browser automatically. We have some rather complicated OAuth procedures and it would really help with our Dev Env to be able to fire off an OAuth flow from Postman but continue in a "real" browser environment. Like others here I end up copying and pasting my request in the browser manually.

Where I intuitively looked when I dreamed this existed:
- An "Open Response in Browser" button, or option in dropdown from Send button.
- Some kind of flag in the Postman Environment would do, or a snippet in the test?

**Comment by jonathan-clark** [comment]
+1

**Comment by suseek** [comment]
+1

**Comment by chakibBH** [comment]
+1
much need thanks a loaf :sake:

**Comment by crmatei** [comment]
+1

**Comment by johanngomes** [comment]
+1

**Comment by dasx199** [comment]
+1

**Comment by jokrent88** [comment]
+1

**Comment by EeKay** [comment]
+1

**Comment by ilya40umov** [comment]
+1

**Comment by katsharp** [comment]
+1

**Comment by zaplitnyak** [comment]
+1

**Comment by miklos-toth-olx** [comment]
+1

**Comment by PeteBoucher** [comment]
+1

**Comment by XavierTolza** [comment]
+1

**Comment by SrikarGajjala** [comment]
+1

**Comment by mkimont** [comment]
+1

**Comment by gkatzioura** [comment]
+1

**Comment by mvalezy** [comment]
+1

**Comment by lgardon** [comment]
+10000

**Comment by tomkurt** [comment]
+100000

**Comment by origamium** [comment]
+5000000000000000

**Comment by igolus** [comment]
+1

But also from the response headers

**Comment by smnkgv** [comment]
+1

**Comment by mig-1** [comment]
+1

**Comment by btosic** [comment]
+1

**Comment by jcezarms** [comment]
The way Postman handles URLs in its Windows client is awfully misleading to me. It should at least show an 'Open in browser' option if the user clicks on the link with the right button, while its blue "hyperlink highlight" is showing.

**Comment by prashantagarwal** [comment]
Hey Everyone, We have fixed this internally and will be made available in next release. Cmd/Ctrl + Click will open the link in default browser.

**Comment by StephenGoodall** [comment]
Great to hear! Look forward to trying it out soon :)

**Comment by jokrent88** [comment]
Thanks for the update @prashantagarwal !

**Comment by chakibBH** [comment]
Thank you  @prashantagarwal, it will be very helpfull

**Comment by prashantagarwal** [comment]
Hey Everyone, we have released this with version 6.1.2. Thanks for being patient with this issue.

**Comment by buraga-dmitrii** [comment]
Thank you so much!

**Comment by DocGreenRob** [comment]
But how do I do this in postman? What is the postman syntax to click on a link. for example, I know how to save values in the response to variables, but how do I click a link using the api where the link is in the response body?

**Comment by gonglong** [comment]
still not work after cmd + click on Mac on version  7.11.0

**Comment by gonglong** [comment]
fixed in 7.12.0

**Comment by mensoh** [comment]
Seems broken in 7.13 on OS X..

**Comment by Aeroverra** [comment]
Why is this closed? It doesn't work.

**Comment by SamuelTissot** [comment]
broken for me as well 
Pop!_os19.10 (Ubuntu)

**Comment by arturhaddad** [comment]
Still inconsistent on Ubuntu 18.04.3 LTS + Postman v7.14.0.
Using CTRL + Click, sometimes it opens on browser and sometimes it opens on a new tab of Postman.

**Comment by matthew-macgregor** [comment]
Seems broken for me as well, I'm afraid on `macOS 10.14.6 (18G103)`. CMD + Click opens in a new tab in Postman.
For the record, this did work for me at one time...

**Comment by baby5** [comment]
@prashantagarwal this should be reopened to solve

**Comment by SamuelTissot** [comment]
I am on Ubuntu and I noticed that for me the issue arises if I have lots of tabs open. After a certain amount of tabs, `ctr+click` just opens another tab. I hope it helps to debug

**Comment by testingapipaul** [comment]
works for me in postman 7.22 in MAC
cmd+click opens a browser 
ctrl+click opens a new postman tab

**Comment by CleverHosting** [comment]
I am on Win 10 and its still not working here :(

**Comment by CleverHosting** [comment]
On Linux same :(

**Comment by stevenxzhou-zz** [comment]
Is it still not resolved? May I ask which link do I need to click? Here?
![image](https://user-images.githubusercontent.com/3982775/81729216-77fb5800-9440-11ea-9a1d-af785aaa2ded.png)

**Comment by mehrad-meraji** [comment]
+1

**Comment by yavieira** [comment]
+100000000 Ubuntu

**Comment by anthonybouton** [comment]
+1 jep still broken

**Comment by DanielPalafox** [comment]
+1 still broken

**Comment by axelzuzek** [comment]
Worked for a while, now its broken again under windows (v 8.5.1)

**Comment by Siedlerchr** [comment]
Broken in mac.
It would be nice to have this as a setting e.g. default click open in browser

**Comment by Gunasekar006** [comment]
+1

**Comment by vikoff2** [comment]
+1
all links are opened in Firefox instead of the default browser (Chrome). Ubuntu 21.04, KDE Plasma Version: 5.21.4,  Postman 8.10.0

**Comment by ndhbr** [comment]
Is there any update on this? I don't get it running on macOS.

**Comment by jmorris-dev** [comment]
broken in win 10

**Comment by ADTC** [comment]
Issue opened: #10389 

On **Postman Web**, this feature is available but **broken**. It open the link in the **same browser tab** where Postman Web is, instead of launching a new browser tab in the browser window. Really frustrating because when I go back to Postman Web, it launches a new session with none of what I was working on.

This also happens for other links like, if you click the Help icon on bottom right and click on links like Documentation or Support. These things should also open in a new browser tab so that I don't lose my place in the current Postman Web session.

**Also annoying:** These links don't appear as links to the browser. They are using some Javascript trickery to act like links when I interact with them. Because of this, right-clicking them doesn't give the same browser context menu that normal links have. So I cannot open the link in a new tab, a new window or an incognito window this way.

**Comment by kgrozdanovski** [comment]
+1
Broken on Mac

**Comment by jb203** [comment]
+1
Broken on windows

**Comment by ChadSpears** [comment]
+1 
Would prefer window.open(JSON.parse(responseBody).Url) in Tests run, but the link to open in a new window would be sufficient if it worked.

**Comment by vkaegis** [comment]
Hey @jimonthebarn and others , this should be fixed as of v10.8.8. Could you take a look and let me know if this behaves as expected?

**Comment by ADTC** [comment]
@vkaegis do the links open in a new tab now when using Postman Web? (See my last comment please)

**Comment by jmorris-dev** [comment]
GET THESE RESPONSES OUT OF MY EMAIL NOW

**Comment by ADTC** [comment]
@jmorris-dev WTH dude. You can just tap on unsubscribe at the bottom of the email...

**Comment by ssukienn** [comment]
Still happens on Mac. Opens headerless browser window with normal one opened in the background
Version 10.12.11
UI Version: 10.12.11-ui-230406-1230
Desktop Platform Version: 10.12.0 (10.12.0)

**Comment by thetilliwilli** [comment]
this is still broken when link is located in collection description area
![image](https://user-images.githubusercontent.com/25109940/232476726-6f59a7d6-7be7-4492-8f6d-288e3344fbde.png)
