### ISSUE TITLE
Add hotkey for selecting url bar, similar to ctrl + L in web browsers

### ISSUE THREAD

**Issue by joaqo** [a85/POSTMan-Chrome-Extension#2587]
It would be great if we could just ctrl + l to select the url bar, as we do in browsers, in order to minimize the use of the mouse

**Comment by sdnts** [comment]
@joaqo We're currently revisiting all shortcuts in the app, and this exact shortcut is what we landed on for jumping to the URL bar. This will be out in our next release. Will keep you updated!

**Comment by sdnts** [comment]
@joaqo 4.10.2 has support for Ctrl + L. Can you try updating and verifying?

**Comment by joaqo** [comment]
Hey @madebysid its working awesomely! Just one small detail, right after I select an environment on the drop down menu in the top right, I lose the ability to use the keyboard shortcuts. I have to click somewhere in the app before I can use keyboard shortcuts again.

**Comment by sdnts** [comment]
@joaqo 4.10.3 should fix that as well :D Can you try updating and confirming?

**Comment by joaqo** [comment]
@madebysid Its working perfectly now, thanks!

**Comment by KochVA** [comment]
Desktop version 10.20.7
It looks like it doesn't work anymore.
@sdnts, Do we need to create separate ticket to check and fix this error or will this be done in the current ticket?

**Comment by Harsh1796** [comment]
Hello @KochVA ! The issue is being tracked under #12521. We've just pushed a fix in our latest app update v10.22. Could you please update your app and let us know if you're still experiencing the issue ?

**Comment by KochVA** [comment]
Hi  @Harsh1796.
Ctrl+L still doesn't work.
![image](https://github.com/postmanlabs/postman-app-support/assets/78483056/d1c6120f-0c1c-4e9f-96f0-cc29760ed977)
