### ISSUE TITLE
Postman 4.10.2 : Can not enable in-app proxy on Windows native app

### ISSUE THREAD

**Issue by trivial-search** [a85/POSTMan-Chrome-Extension#2727]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 8.1
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: ONly after upgrade to 4.10.2
 6. Expected behaviour:
The in-app proxy should be succesfully set on clicking "connect" on the Proxy settings dialog in the Windows native app
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

_xml.js:22 Uncaught Error Uncaught ReferenceError: mode is not defined file:///C:/Users/sunje_000/AppData/Local/Postman/app-4.10.2/resources/app.asar/js/common.js 4312 8 ReferenceError: mode is not defined(…)(anonymous function) @ xml.js:22
common.js:4312 Uncaught ReferenceError: mode is not definedhandleConnect @ xml.js:22handleClick @ common.js:55648invokeGuardedCallback @ common.js:4286executeDispatch @ common.js:4131executeDispatchesInOrder @ common.js:4154executeDispatchesAndRelease @ common.js:3586executeDispatchesAndReleaseTopLevel @ common.js:3597forEachAccumulated @ common.js:4428processEventQueue @ common.js:3802runEventQueueInBatch @ common.js:4457handleTopLevel @ common.js:4473handleTopLevelWithoutPath @ common.js:14647handleTopLevelImpl @ common.js:14627perform @ common.js:6617batchedUpdates @ common.js:10641batchedUpdates @ common.js:6125dispatchEvent @ common.js:14758_

 8. Screenshots , as below ...

![image](https://cloud.githubusercontent.com/assets/15244739/23089356/85c9a054-f5ec-11e6-9c1a-1723fc2c9202.png)

Steps to reproduce the problem:
1. Click on the interceptor icon 
2. Proxy setting dialog pops up 
3. Keep the port as default (5555) and choose target as History 
4. Click Connect 

Nothing happens ! 

The following exception is logged in the developer console 

xml.js:22 Uncaught Error Uncaught ReferenceError: mode is not defined file:///C:/Users/sunje_000/AppData/Local/Postman/app-4.10.2/resources/app.asar/js/common.js 4312 8 ReferenceError: mode is not defined(…)(anonymous function) @ xml.js:22
common.js:4312 Uncaught ReferenceError: mode is not definedhandleConnect @ xml.js:22handleClick @ common.js:55648invokeGuardedCallback @ common.js:4286executeDispatch @ common.js:4131executeDispatchesInOrder @ common.js:4154executeDispatchesAndRelease @ common.js:3586executeDispatchesAndReleaseTopLevel @ common.js:3597forEachAccumulated @ common.js:4428processEventQueue @ common.js:3802runEventQueueInBatch @ common.js:4457handleTopLevel @ common.js:4473handleTopLevelWithoutPath @ common.js:14647handleTopLevelImpl @ common.js:14627perform @ common.js:6617batchedUpdates @ common.js:10641batchedUpdates @ common.js:6125dispatchEvent @ common.js:14758

**Comment by clarketm** [comment]
I experienced the same issue on Mac.

**file:** Postman.app/Contents/Resources/app/js/requester.js

**lines:** 163430-163430
![image](https://cloud.githubusercontent.com/assets/9957358/23094970/2f459114-f5b7-11e6-9bea-bf257e094975.png)

**error:**
![image](https://cloud.githubusercontent.com/assets/9957358/23095014/d0e487be-f5b7-11e6-8313-5ef68919bb88.png)

**Comment by SamvelRaja** [comment]
@sunjeet-khokhar @clarketm This has been identified and the fix has been released in our canary channel, Can you guys switch to that app to continue using without any trouble. You can download them here,
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by clarketm** [comment]
Sure thing @SamvelRaja. Thank you for the quick feedback and resolution.

**Comment by kdcarlisle42** [comment]
I grabbed the OSX version and am now able to connect the proxy.  However, nothing appears in postman.  The postman proxy settings are port 5555 and target History.  I also updated my network (thunderbolt ethernet) proxy settings.  I select both HTTP and HTTPS and listed the web proxy server as 127.0.0.1 on port 5555.

I feel like I am overlooking something obvious, but cannot figure it out.  Is there something else that needs to be setup/configured or is the canary version not actually working?

I've also opened the DevTools and Console windows, neither is showing any errors, nor traffic.

UPDATE:  ARGH, it was the VPN software.  I tested again this morning before connecting and it worked like it should.  Thanks for the update!!

**Comment by Silviu-Surcica** [comment]
SamvelRaja I have downloaded the version from canary for win64 and the issue is not fixed.

**Comment by SamvelRaja** [comment]
@Silviu-Surcica Can you give me some more details on your issue?
Just make sure your are in 4.10.3-canary01 version of the app.

**Comment by Silviu-Surcica** [comment]
@SamvelRaja Apparently i have Version 4.10.2 (Postman for windows) but I have downloaded it from the above links that you posted.

My issue is that I can't select Target History and when I click connect, nothing happens.
**The download links for windows versions are for version 4.10.2, not for 4.10.3-canary01.** 
I managed to download the canary version, and it is working. 
Thank you!

**Comment by SamvelRaja** [comment]
@Silviu-Surcica there was an issue with our release server in serving the canary apps, now you can download the canary app through the link provided. Let me know if you still gets downloaded the 4.10.2 version instead pf PostmanCanary 4.10.3-canary01 app.

**Comment by SamvelRaja** [comment]
@sunjeet-khokhar  @Silviu-Surcica  @clarketm  @kdcarlisle42  the fix has been rolledout in our 4.10.3 app. kindly update and verify the same 😄
