### ISSUE TITLE
Upload using binary body type fails in POSTMan Mac App due to missing Content-Length header

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#2756]
Version/App Information:
 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Mac App  (Issue DOES NOT occur for Chrome app
 3. OS details: Sierra 10.12.3
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Not sure. I think it was working before but can't say when.
 6. Expected behavior:  Add Content-Length header and Upload succeeds.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

Create API with POST using body="binary" and specifying a file to upload with the "Choose File" selection button.

Create new API entry with following values:

    POST /v2/media_files?offset=0&amp;upload_id=03bbed29d90442e0af8ebfb82f0512a7 HTTP/1.1
    Host: XXX
    Authorization: XXX
    X-RPC-AUTHORIZATION: XXX
    Content-Type: application/octet-stream
    Cache-Control: no-cache
    
    <binary data>

Making this request returns error from server complaining of missing Content-Length header.

Same request that works (with Content-Length manually inserted):

    POST /v2/media_files?offset=0&amp;upload_id=03bbed29d90442e0af8ebfb82f0512a7 HTTP/1.1
    Host: XXX
    Authorization: XXX
    X-RPC-AUTHORIZATION: XXX
    Content-Type: application/octet-stream
    Content-Length: 2401580
    Cache-Control: no-cache
    
    <binary data>

As a test, I manually added Content-Length by measuring # of bytes in the file and adding that header to above.  The request succeeded in this case.

This issue ONLY happens in the Mac App.  Does not occur with Chrome app on Mac.  Since Chrome app is being deprecated I hope this bug can be fixed soon. This is a blocking issue for uploading files thru our APIs since we have a few that just use binary data method.

**Comment by vegetableman** [comment]
@stevemcmillen Thanks for letting us know about this issue 👍 . We are able to reproduce it and will keep you posted.

**Comment by tmack8001** [comment]
When I try to use binary body, it sends the request with no content to my local server.

**Comment by scottadamsmith** [comment]
@stevemcmillen Curious, does the installed app allow you to manually insert a Content-Length header? The chrome app restricts the ability to set this header. 

Please disregard, just confirmed with a teammate that the installed app does let you set the value manually.

**Comment by numaanashraf** [comment]
@stevemcmillen @tmack8001 @scottadamsmith This is fixed in v4.11.0

**Comment by teledemic** [comment]
This does not appear to be fixed - when sending a binary body in 4.11.1, no Content-Length header is attached.

**Comment by kud202** [comment]
Facing the same issue, no Content-Length header,  Postman: 5.0.0

**Comment by YenF** [comment]
5.0.2 still has this issue. Updated to 5.1.3 and everything is good.

**Comment by szafirov** [comment]
I have 5.1.3 on Mac, and I still have the issue. Selecting the binary option in the Body tab, browsing to a local file and the file is not sent on POST with headers: "Content-Type: application/json"

**Comment by andreacab** [comment]
I also have the issue with postman 6.7.4. I posted a SO issue [here](https://stackoverflow.com/questions/55049263/file-upload-with-postman-with-pre-signed-url-not-working)
