### ISSUE TITLE
Variable is not resolving when value is null

### ISSUE THREAD

**Issue by antk43** [a85/POSTMan-Chrome-Extension#2861]
Version/App Information:

 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Postman for Windows
 3. OS details: 
 4. Is the Interceptor on and enabled in the app: no unable to set my own proxy settings
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: as per the Chrome extension version when using a data file; any cell that contains no data is regarded as null so no data is added to the data variable contained within the request URL
 7. Console logs: the log simply outputs the URL that is being used (I have hidden the first part with ...): 
.../products/21051111/?skip=0&limit={{limit}}&validity_from_date={{validity_from_date}}&validity_period_length={{validity_period_length}}
 8. Screenshots (if applicable)

Steps to Reproduce
1. Set one or more environment/data variables within the request URL.
2. Running the request using the environment variables works as expected creating the following request URL to post: ...products/21051111/?skip=&limit=&validity_from_date=&validity_period_length=
3. Running the request through the runner using a data file, that contains null values within some of the rows, creates the following request URL: .../products/21051111/?skip=0&limit={{limit}}&validity_from_date={{validity_from_date}}&validity_period_length={{validity_period_length}}

This works fine within the Chrome extension version but the Windows version is not replacing the data variable names with no value when a data file cell contains no value.

**Comment by ghost** [comment]
Hey, 

Do we have any ETA on this, Its identical to the issue I'm having. However, I'm getting the same problem with both Chrome extension and windows installation

**Comment by mjkraner** [comment]
this seems to still be the case, we need a null to go in but when we leave the field blank it pulls the variable name instead

**Comment by grzegorzjudas** [comment]
Confirming on OSX app - `{{varname}}` resolves to `{{varname}}` if it's value is null instead of actually parsing it and putting `null` in it's place.

Need to pass null in a POST body and I indeed want to pass null...

**Comment by rastephens86** [comment]
updated postman to the latest version and i am experiencing this same issue. any updates?

**Comment by FlanderJam** [comment]
This issue is still occurring on Postman 5.5.0 for Windows.

{{varname}} resolves to {{varname}} if the value of varname = null. I would like for {{varname}} to resolve to null if the value of varname is indeed null.

Is there any update available for the resolution of this bug?

**Comment by bhingston-va** [comment]
Running postman version 6.1.3 on OSX; what's the status of this bug?

**Comment by numaanashraf** [comment]
@bhingston-va @kwilmot @rastephens86 @grzegorzjudas @mjkraner @Forebinder2010 Could you gimme a screenshot to help us replicate this issue at our end? I tried assigning null to an environment value through the environment editor and pre-request script and the variable is resolving correctly.

<img width="909" alt="screen shot 2018-06-29 at 2 25 05 pm" src="https://user-images.githubusercontent.com/3295568/42083381-5729a26a-7ba8-11e8-9fef-529c636c028e.png">

**Comment by grzegorzjudas** [comment]
@numaanashraf It's not a string with value "null" that I (we) want to pass, but *null* itself.
![zrzut ekranu 2018-07-03 o 09 28 02](https://user-images.githubusercontent.com/3832059/42204975-762525d8-7ea3-11e8-9a93-cb68069c19b9.png)
![zrzut ekranu 2018-07-03 o 09 28 21](https://user-images.githubusercontent.com/3832059/42204976-76448874-7ea3-11e8-893d-6155ee343279.png)
![zrzut ekranu 2018-07-03 o 09 28 24](https://user-images.githubusercontent.com/3832059/42204977-76638e72-7ea3-11e8-8b60-0e0313cfe45b.png)
I confirm it works if you pass "null" as value for environment variable (as you've shown). But it works for numbers without quotes (and gets rendered as number, not string).

**Comment by jsavidge** [comment]
I am also having this issue, but it only applies to variables being brought in from a Data File.
In the CSV the fields are left blank and in Postman's Data Preview it sees them correctly as 'nulls'. However when the iteration is run, it is passing the Variable name, please see the screenshots below;

![postmanvariables](https://user-images.githubusercontent.com/40893483/42383169-577fe978-812e-11e8-9ce8-c04622f7027e.png)

**Comment by abcabc1** [comment]
null is passed ok for me when i excuted single request, but it didn't work for collection run with datafile. if i put null value in datafile, the request send {{variable}} which crash my code.

**Comment by Kal6** [comment]
when run from newman it is working fine as we do expect it is reading data file null values as null, but from Postman Collection Runner when run the test scripts null values are reading as variable key names {{var name}} so the problem is with **Postman Collection Runner**

This is my csv datafile, in which i am passing org id and store number as empty values.
![image](https://user-images.githubusercontent.com/38101846/44312709-399b4b00-a3ca-11e8-8709-030e326990cb.png)
When run from Collection Runner it is passing as Variable key name like below
![image](https://user-images.githubusercontent.com/38101846/44312746-ea094f00-a3ca-11e8-9b92-8944f530a3d0.png)

but when i run from Newman command it is working as expected meaning it is reading as empty(null) value. So until they fix the collection runner in postman we can work with newman.
![image](https://user-images.githubusercontent.com/38101846/44312824-3b660e00-a3cc-11e8-82fe-e1fd1c00b9ad.png)


i hope this will help for those who are looking for work around and postman support team.

Thank you!

**Comment by fritzieleo** [comment]
Hey, I'm facing the same issue with Collection Runner on Postman v6.2.5, Any updates on this issue?

**Comment by radityaarya** [comment]
Facing the same issue even when running from newman (data in json format). But if i run newman with csv data, its working. Dunno why.

edit: I'm using Postman 6.3.0 & Newman 4.1.0, Ubuntu 16.04

**Comment by shamasis** [comment]
Note: We need to unify csv-parse for runner and newman.

**Comment by Kal6** [comment]
null values are populating in newman and working fine, issue with runner only. Thank you

**Comment by digital-q** [comment]
I can confirm that null values being replaced by their variable name is still an issue with runner. JP in Postman support has come up with a great workaround, which I'll post here:

**Add the following to the Pre-request script**
`var iterationData = pm.iterationData.toObject();
					var keys = Object.keys(iterationData);
					for(var i = 0; i < keys.length; i++)
					{
					    if(iterationData[keys[i]] === null)
					    {
					        pm.variables.set(keys[i],null);
					    }
					}`

**Add the following to your test script. This ensures the variables that we "forced" in the pre-request script get cleared before we run the next line of the CSV**
`pm.variables.clear();`
	**Note:** `pm.variables.unset('key')` can be used insteadto only clear specific variables, if this is preferred

**If you want to keep track of whether everything is working correctly, add the following to your Tests (above `pm.variables.clear();`) for each variable you want to keep tabs on. Check out the console (Command+Option+C) to see the results**

`console.log(pm.variables.get('variablename'));
`

Of course, would be great to get this issue fixed natively! If this is "Out of Scope" for Runtime Triage and Development, hopefully it can be picked up for fixing somewhere else.

**Comment by vikiCoder** [comment]
Hi everyone,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. This issue is fixed as part of those changes, Postman App now treats null values as empty string while parsing CSV file (same as Newman). It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can check out [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. Suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by vikiCoder** [comment]
The fix that I mentioned in my previous comment is out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.

**Comment by bdmishra08** [comment]
In postman version 7.6.0 and 7.2.2 
I am trying to send null as vriable value in data file such as [{
"name":null,
"job":"team lead"
}]
but it takes as {
    "name": "{{name}}",
    "job": "reat"
}

**Comment by russellg** [comment]
Is there a way to do this via collection runner where it just passes null and not ""? Either of the above options do not appear to work for JSON or CSV.

**Comment by nathanyost15** [comment]
This is still an issue with 7.23.0
{
    "affiliate": "balh",
    "channel": null,
    "affiliateNeg": "blah",
    "channelNeg": "balh"
  }

shows channel as {{channel}} while in runner

**Comment by mt4work** [comment]
Yes i still see the issue in the runner on 7.25

**Comment by russellg** [comment]
Not sure if this will help anyone.

I have some code that I put in pre-request to deal with null values being pulled from a data file.

```
let iterationData = pm.iterationData.toObject();

Object.keys(iterationData).forEach(function (key) {
  if (data[key] === null) {
    pm.variables.set(key, "null");
  } else if (data[key].toString().match(/.+/gm)) {
    pm.variables.set(key, JSON.stringify(data[key]));
  }
});
```
So in my JSON data file I'll have something like:

```
    "countryCode": "11",
    "dateGranted": null,
    "isaType": null
```

And when run via Collection runner or Newman, it will pass the null value successfully.

You can take this a step further and enter this in your pre-request section also:

```
let dataKeys = _.keys(pm.iterationData.toObject());
knownKeys = ["variable1", "variable2", "variable3"];
missingKeys = knownKeys.filter((key) => !dataKeys.includes(key));
_.each(missingKeys, (item) => {
  pm.variables.set(item, "null");
});
```

Basically, if you put the variables that you have in your endpoints in the knownKeys array, if you don't actually include the variable in your data file, it will automatically just pass null.

Hope this helps someone.

**Comment by parulsharmaRFI** [comment]
@russellg This worked for me via postman runner. Thanks for the help.

**Comment by francisguchie** [comment]
@russellg  

Thanks for your pre-request code.

but using Postman v8.3.1 i learnt that i just hard to make all null values appear as "" in my .json file 
then these were later taken as NULL into the Database 
all the other options did not work

I changed the code to look like this 

Object.keys(iterationData).forEach(function (key) {
  if (data[key] === null) {
    pm.variables.set(key, null);
  } else if (data[key].toString().match(/.+/gm)) {
    pm.variables.set(key, data[key]);
  }
});
