### ISSUE TITLE
Exporting without saved response IDs and postman collection ID

### ISSUE THREAD

**Issue by gabipetrovay** [a85/POSTMan-Chrome-Extension#2906]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome app (Chrome 54.0.2807.0)
 3. OS details: OS X / x86-64
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: yes
 6. Expected behaviour: stable saved response ID or having the possibility not to export the IDs of the saved responses at all.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable): N/A

Importing and exporting a collection will export also the following non-stable values:
- `_postman_id`
- for each saved `response` an `id`

For every import-export these values change and therefore this is not source versioning friendly. Hence a Postman collection cleanup step is necessary before committing the exported collection.

It would be nice if the non-stable internal IDs would either:
- not be exported
- removed from the export using an option during the export process

**Comment by macejiko** [comment]
Any progress on this? Really blocks our team from using postman..

**Comment by mccannt** [comment]
I am going to throw a +1 on this issue as its something thats becoming more and more of an issue for my teams when checking changes into VCS.

Can we get some sort of an update as to where this falls on the roadmap?

**Comment by sberczuk** [comment]
Our workflow is to keep the canonical versions of collections in Git, and push then to the cloud in CI, using the IDs as keys. And the Postman Editor _is_ the nicest way to edit collections. So being able to import, edit, export without having to manually revert the ID change would be helpful. So for us "keeping the ID" is useful. Deleting it is not.

**Comment by jackieta1** [comment]
This is huge issue for us too. Please prioritize this.

**Comment by grimsa** [comment]
VCS-friendliness was made worse in 7.23 due to the script ID uniqueness fix. See #4802

**Comment by murven** [comment]
Starting from version 7.23, Postman does not seem to be a viable option for our team due to the replacement of the IDs in hundreds of test cases. We are looking for ways to workaround this issue or moving away from Postman altogether.

**Comment by manoelagonzaga** [comment]
Any updates about this issue? The GUID changes is difficulting a lot the evaluation of real tests changes.

**Comment by luto65** [comment]
I use SMART Json Editor in order to modify postman collections.
Perhaps one could use also Atom or Eclipse.

**Comment by jgalvacky-bt** [comment]
+1 Any update on this? This has become quite the pain point while using any versioning tools.

**Comment by zoranbgd** [comment]
+1 Is this going to be implemented soon? We are considering other options - editing JSON in editor is not good idea if you have a large collection.

**Comment by eraymond-bt** [comment]
Hoping you can please fix this ASAP. Running a diff across versions in source control is so painful with a large collection now. The diff is filled with hundreds of "id" mismatches that I don't care about, making the changes I do care about much harder to see.

![image](https://user-images.githubusercontent.com/66840463/84908307-4fd7c800-b082-11ea-89c5-5f192a5eaaf2.png)

**Comment by ManiacDC** [comment]
@eraymond-bt 

You can fix BC using this, then toggle minor differences as needed:
![image](https://user-images.githubusercontent.com/1823305/84909530-ce813500-b083-11ea-885b-258718de4323.png)
![image](https://user-images.githubusercontent.com/1823305/84909573-da6cf700-b083-11ea-933a-b12f801e877b.png)
![image](https://user-images.githubusercontent.com/1823305/84909593-e2c53200-b083-11ea-8b5e-c9a77f9dfcec.png)
![image](https://user-images.githubusercontent.com/1823305/84909702-fc667980-b083-11ea-960a-77dcb2b1bc81.png)

**Comment by eraymond-bt** [comment]
Thanks @ManiacDC. I'll give that workaround a try. It may work for me on my machine, but the file I commit will still have the "id" changes, which could impact my teammates if they do not have this BC configuration, or if they're using another diff tool. Thank you for the suggestion!

**Comment by ManiacDC** [comment]
@eraymond-bt I work around this by keeping two copies of the file. I import/export my file NOT in the working copy, then I use BC to move the changes to the file in my WC. I move only the IMPORTANT changes. Then I'm not cluttering my commit with IDs. If you want to sync up the two files, you can just copy the file from your WC and overwrite the other copy, or turn minor differences back on and copy all the minor differences over to the other copy.

**Comment by zoranbgd** [comment]
@ManiacDC There are many workarounds, but proper solution is to remove IDs when collection is exported from Postman. This can be optional (checkbox, for example) on export screen.

**Comment by ManiacDC** [comment]
@zoranbgd of course? That's why my post above is a workaround. It's a ton of work that wouldn't be needed if we simply could export without IDs.

**Comment by entimaniac** [comment]
We use postman for integration tests in our staging environment and we keep the collection.json file in our git repo along with our code. Our CICD processes include running a postman collection from jenkins. 
Multiple developers constantly adding new functionality or updating old ones or fixing bugs, we need to have a lot of tests. We need to be able to review these tests before approving Pull Requests. Our current file is 20,000+ lines long with over 1000 tests. Every export (technically import from what I've read) will generate new IDS for every test.  We have to constantly import and export the collection file because we need to be able to work with the latest code in order to add or modify tests.
We are no longer able to load the file in diff viewing tool in a reasonable manner. We'll probably split out each of our workflows into different collections to make things more manageable overall and just iterate over an array of collections during testing, but this shouldn't be necessary. The ID should either be reused on import or not included.

I wrote a node script to remove IDs and it doesn't seem to break functionality so apparently this doesn't particularly affect user features. I'm looking into making it part of our build pipeline but that gets messy, automatically merging code into someone's branch without them knowing. Pre-commit hook would be a nice solution but each developer has to manage it locally. Anyway, this seems to work and for request IDs generated if anyone is interested.
```
const fs = require("fs");

let collection = JSON.parse(fs.readFileSync("postman_collection.json", "utf8"));

for (let workflow of collection.item) {
  for (let request of workflow.item) {
    for (let event of request.event) {
        // console.log(event.script.id)
        delete event.script.id
      }
  }
}

fs.writeFileSync("postman_collection.json", JSON.stringify(collection, null, 2));

console.log("done");
```

**Comment by melissapalmer** [comment]
This is still the same problem on `Version 7.27.0` and causing us much pain. 
To the point where we may not even use postman anymore as its introducing duplication of work and so on.

**Comment by frankoid** [comment]
This is such a problem for us that we've downgraded to version 7.22.1 (from https://dl.pstmn.io/download/version/7.22.1/osx64) and prevented auto updates by adding the following to /etc/hosts:
```
# Prevent Postman auto updates
127.0.0.1       dl.pstmn.io
```

**Comment by ayratn** [comment]
Few months back I've created this bash script which removes all "id" in diff and we use it before committing to repo:

```
#!/bin/bash
export COLLECTION=./src/test/postman/$SERVICE.postman_collection.json
echo "Fixing ids in " $COLLECTION

git diff $COLLECTION | grep -Pzo '\"script\".*\n[-].*\"id\".*\n[+].*\"id\".*' | sed 's/\"script\"\: {//' | sed '/^$/d' | sed 's/[-+].*id\"//; s/[^a-z0-9-]//g' | sed 'N;s/\n/ /' | sed 's/\([0-9a-z-]*\) \([0-9a-z-]*\)/s\/\2\/\1\/;/' | paste -sd "" - | sed 's/\([^;]*;\)\{100\}/&\n/g' | xargs -l bash -c 'sed -i "$0" $COLLECTION'
```

For diff with 300-400 changed ids it works ~1 second.

**Comment by arlemi** [comment]
More feedback from @entimaniac in #8735

 **Describe the bug**
When importing and/or exporting a collection, a new ID is generated for collection elements such as requests even though there is already an ID present in the file.

**To Reproduce**
Steps to reproduce the behavior:
1. Create collection.
2. Create a request (doesn't need to 'work', can be empty pretty much)
3. add any basic test like; 
```
pm.test("test", function() {
    pm.response.to.not.be.error;
});
```
2. Export the collection to json (v2.1). 
3. Delete original collection from postman. 
4. Import collection JSON.
5. Export collection again, pick a different location or name, just don't overwrite the previous json file. 
6. compare IDs for the same request (script/test ID) and see they are different even though nothing changed. 

**Expected behavior**
A collection file that has an ID field already should reuse the ID field on import instead of generated a new one. Or if the issue is on export, then don't generate a new ID on export.



**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] 
native? whatever the recommended download is for mac
 - Postman Version [e.g. 6.0.1]
Version 7.27.0 (7.27.0)
 - OS: [e.g. macOS High Sierra 10.13.2]
macOS Sierra 10.12.6 

**Additional context**
We use Git. Postman tests are how we run integration tests both locally and in our automated staging environment via Jenkins. with a collection of 1100+ tests, we have SOOO many IDs. And they all get regenerated each time. We do code reviews on Github and the browser breaks if you try to load the diff. My IDE breaks if I try to load the diff. Its unmanageable.

**Comment by luisdaglez** [comment]
+1. My team experiences this day in and day out. It's a big source of frustration.

**Comment by zoranbgd** [comment]
Do you have any idea when this issue will be fixed? Is it a month, 6 months, a year? Thank you.

**Comment by Jelly13** [comment]
Hi, this removal would be beneficial for our project as well. Too many unnecessary diff is not great for code review process. :(

**Comment by mojo2012** [comment]
Not even a response from the devs? Damn I guess I will be moving on ...

**Comment by mccannt** [comment]
@mojo2012 We are investigating this issue and it is very much on our radar. We can not commit on a timeline at this time but we will follow up when we have more to share. 

Please appreciate some feature changes are not straight forward and require time and effort to address, so we don't negatively impact other users.

**Comment by byrdman** [comment]
I'll throw my name in the hat as being interested in a solution, reviewing a PR for changing a typo in a test resulting in hundreds of "changes" is painful.

**Comment by jessepina** [comment]
+1 for this.  This is making it difficult to use with our version control system.

**Comment by Allsimon** [comment]
The workaround provided by @entimaniac seems OK for me. It doesn't remove every id though. Here is an updated version that removes all id in my collection:

```js
const fs = require('fs');

// This script deletes the `id` field in postman-collection.json that is changed without reason
// see https://github.com/postmanlabs/postman-app-support/issues/2906
// usage:
// node clean-postman.js
const collection = JSON.parse(fs.readFileSync('postman-collection.json', 'utf8'));

for (const item of collection.item) {
  for (const event of (item.event ?? [])) {
    delete event.script.id;
  }
  for (const request of (item.item ?? [])) {
    for (const event of (request.event ?? [])) {
      delete event.script.id;
    }
  }
}

for (const event of collection.event) {
  delete event.script.id;
}

fs.writeFileSync('postman-collection.json', JSON.stringify(collection, null, 2));

console.log('done');
```

**Comment by danialgoodwin** [comment]
To brainstorm a possible 'easier' fix... instead of automatically changing all IDs on import. Is it possible for Postman to know all IDs in all collections and only change imported IDs if they are the same? Is this something that would fix 95%+ of use cases?

**Comment by vvs11** [comment]
We have this in our roadmap. Will share an update on this soon .

**Comment by lbenedetto** [comment]
Will you also fix the id changing when I export from a fork of the main collection?
We export our fork and then create a pull request, and the diff is really annoying to read.

**Comment by zoranbgd** [comment]
@lbenedetto Isn't that the whole purpose of ID-less export "feature"?

**Comment by lbenedetto** [comment]
@zoranbgd Yes, just wasn't sure if that was the solution you were going with. A possible solution that wouldn't work for me would be to make the IDs consistent when importing an export, but not when forking.

**Comment by ManiacDC** [comment]
@lbenedetto IDs change upon import, not export. Are you sure that's not what's also happening with your fork?

**Comment by lbenedetto** [comment]
Export A to file a.json. Fork A to make B. Export B to file a.json.

All the IDs are now different.

At no point do I import.

**Comment by ManiacDC** [comment]
I guess I was more saying it's possible the fork is doing an implicit import rather than explicitly changing the IDs. Regardless, fork is changing IDs.

**Comment by vvs11** [comment]
@lbenedetto to which component do these ids belong to? I mean the ids that you see in the diff? Also, if you can explain your workflow a bit, it'd be helpful

**Comment by lbenedetto** [comment]
@vvs11 

collection.info._postman_id
collection.item[0]._postman_id (folder)
collection.item[0].item._postman_id (request)

Workflow:
A bunch of tests are stored in Postman. When adding a test, create a fork, and export the fork to the json in your Git branch. Push the changes for review (along side your actual code changes). When accepted, merge the postman fork, and then merge your git branch. During our jenkins builds, we run the json file with newman.

Is how we would like it to go. But to avoid polluting our git history, we have to do a second fetch from the main collection after we merge our postman fork to get a version of the json where the IDs are the same, and then squash and force push that to our git branch before merging.

Export to json is done with
`curl -s -H "X-Api-Key: ${POSTMAN_API_KEY}" https://api.getpostman.com/collections/${COLLECTION_ID} | docker-compose run --rm jq . -M > $COLLECTION_FILE`

**Comment by zoranbgd** [comment]
Are there any updates on this issue? Is it still on the roadmap or it is abandoned?

**Comment by mccannt** [comment]
@zoranbgd Thanks for reaching out. This is very much still something we are looking to tackle. We can not give an estimate at this time but we are hoping it will be in the near feature. 

We will update when we have more information, please hang tight.

**Comment by bowens-zn** [comment]
+1 please fix 😄

**Comment by shauntck** [comment]
would be really helpful. Really screws up the diff in source control.

**Comment by micaelboucard** [comment]
Same hereeeeee

**Comment by atoledo** [comment]
+1 please fix

**Comment by luizpalmieri** [comment]
+1 for it

**Comment by simonjpartridge** [comment]
Try this:

```
jq --indent 2 'walk(del(.id?) | del(.response?) | del(._postman_id?) )' "API_Test.postman_collection.json" > "API_Test.postman_collection.json.tmp" && mv "API_Test.postman_collection.json.tmp" "API_Test.postman_collection.json"
```

You have to run every time you export, but it helps make th diffs more readable

**Comment by lbenedetto** [comment]
@simonjpartridge Nice.
I'm now running that, but with an additional step that adds the fetched collection id to the output json.
```
curl -s -H "X-Api-Key: ${POSTMAN_API_KEY}" https://api.getpostman.com/collections/${COLLECTION_ID} \
  | docker-compose run --rm jq --arg collection_id $COLLECTION_ID '.collection.info += {collectionId: $collection_id}' -M \
  | docker-compose run --rm jq --indent 2 'walk(del(._postman_id?) )' \
  > "$COLLECTION_FILE"
```

 That way we can tell which collection was exported (so we can tell branches apart) but it doesn't pollute the entire diff with _postman_id.

**Comment by zoranbgd** [comment]
I will try it, it is 100% better than never ending "something we are looking to tackle".

**Comment by aowss** [comment]
+1

**Comment by m9abbas** [comment]
+1

**Comment by lusoalex** [comment]
+1

**Comment by mairo744** [comment]
+1

**Comment by RanceJen** [comment]
+one

**Comment by mccannt** [comment]
Thanks, everyone for the input and upvoting, it really helps us understand the needs of our userbase. 
With that being said, we should have something out very shortly to address this. :)

**Comment by arlemi** [comment]
Hey everyone! We've just released Postman 7.36.1 that now strips all IDs from the collection exports. You can update your app or get the latest version from [the downloads page](https://www.postman.com/downloads/).

Thanks for your patience with this issue and let us know if you have any feedback. 🙏

**Comment by lbenedetto** [comment]
Looks like the API is still serving up `_postman_id`

`curl -s -H "X-Api-Key: ${POSTMAN_API_KEY}" https://api.getpostman.com/collections/${COLLECTION_ID}`

Will the API be changed as well? Or is there a v2 I need to switch to?

**Comment by bkaidbb** [comment]
@arlemi when I try it on 7.36.1, I can't export at all anymore.

![image](https://user-images.githubusercontent.com/44074943/102503302-d0c94980-403c-11eb-8d3b-54220417d783.png)
![image](https://user-images.githubusercontent.com/44074943/102503375-e474b000-403c-11eb-9b96-bd5891dc730c.png)

```
Error while exporting an entity {id: "5bbda004-4588-4bdc-8e89-66a02760e073"} {type: "collection", inputVersion: "1.0.0", outputVersion: "2.1.0"}inputVersion: "1.0.0"outputVersion: "2.1.0"type: "collection"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() Error: Unexpected return value from ipcRenderer.sendSync: null
    at EventEmitter../lib/renderer/api/ipc-renderer.js.ipcRenderer.sendSync (ipc-renderer.js:18)
    at child.sendSyncMessage (vendor-shared.js:192585)
    at saveAndOpenFile (vendor-shared.js:429570)
    at postman-converters.js:486
    at new Promise (<anonymous>)
    at postman-converters.js:485
```

**Comment by zoranbgd** [comment]
Thank you @arlemi, this really means a lot.

**Comment by arlemi** [comment]
@lbenedetto Calling that endpoint on the same collection will always give you the same IDs, though seeing your workflow 
 I understand this doesn't solve it for you. Let me ask and see if there are plans and/or if we should create a separate issue for it.

**Comment by micaelboucard** [comment]
Yes, thank you!
Works like a beauty!

**Comment by arlemi** [comment]
@lbenedetto The API will be changed as well, I've created this issue so it can be tracked separately to this one which is now resolved: https://github.com/postmanlabs/postman-app-support/issues/9375 🙂

**Comment by chai2** [comment]
Thanks a lot, @arlemi for the announcement. Just tried and works like a charm!!

**Comment by VV-55** [comment]
This update looks useful in version control in postman. But where could i find export option in version 8.0 postman?

**Comment by mccannt** [comment]
@VV-55 You can find it by opening up the collection in a tab (clicking on the collection name in the left nav) and then clicking on the ellipsis and then Export.

![image](https://user-images.githubusercontent.com/14275144/105857270-84b8df80-5fc0-11eb-978f-4aa3e6a0a013.png)

**Comment by Thommynator** [comment]
I'm wondering if I'm doing something wrong.
My Postman version is **v8.0.6** and I'm exporting to a **v2.1** Collection.
I still have the same issue that all the script id's are different after the export.

Do I need to change a setting or something?
@arlemi do you have a hint? :)

**Comment by arlemi** [comment]
@Thommynator I've tried on the latest v8, and Postman Web, but I'm not seeing the IDs being exported... Is that an old collection that you're trying to export? And do you have this issue with any collection or just this one?

**Comment by Thommynator** [comment]
What I did:
- Create a new collection
- Export collection
- Import collection (replacing the existing one)
- Export collection to a different file
- Compare the two exported files

For me the `_postman_id` changes after every export.
```
"info": {
    "_postman_id": "34eee1be-296a-407a-884c-9a69ba1c5bd1",    <<< this one
    "name": "New Collection",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
}
```

Additionally, all the requests which are using a "Pre-request Script" and/or a "Test Script" had changing ids, too.
```
"event": [
  {
    "listen": "test",
    "script": {
      "id": "f4e200b7-8c80-41c9-807e-ed5efc52a377",  <<< this one
      "exec": [
        ""
      ],
      "type": "text/javascript"
    }
  },
  {
    "listen": "prerequest",
    "script": {
      "id": "b3bbfa55-d48c-41c6-b944-844765325675", <<< this one
      "exec": [
        ""
      ],
      "type": "text/javascript"
    }
  }
]

```

But now I found out that this only happens for already existing requests. New requests will not have this id anymore. 
That's cool! :) What's the best way to do it for all the existing requests as well? Should I remove all the ids from the JSON (manually) or is there an easier way?

**Comment by arlemi** [comment]
So the `_postman_id` will keep being updated whenever you **import** a collection, Postman considers that this is a new collection and therefore assigns a new id to it. If you keep on exporting the same collection, that id shouldn't change. 

Have you tried if duplicating the requests was getting rid of the script ids? Otherwise recreating them, or removing the ids manually are the only things I can think of. 🙁

**Comment by jgalvacky-bt** [comment]
On the latest Postman version (**v8.2.2**) the **Collection Variables** are generating new ID's every time with each export of the collection. Similar problem to what was resolved with this current issue. This type of bug keeps sneaking back in.
- import collection (that contains collection level variables)
- export collection
- the exported collection variables all have **new ID's assigned to them** (not expecting this to happen)

Anyone else seeing this happen? New Bug Issue needed?

**Comment by arlemi** [comment]
@jgalvacky-bt Thank you for reporting, we're looking into it!

**Comment by Lampei** [comment]
@arlemi so how do we go about *keeping* the ids in collections?  I need to run specific folders (via newman) and if they have duplicated names, then the only way to do this is using the "id" of the folder.  If these are being removed each time I export from Postman UI, then I would have to keep adding those ids back in again.

**Comment by na9812** [comment]
Just to add, this also happens when creating a Collections object via Collections SDK. Notice the `_postman_id` field in json and in collections object - https://github.com/postmanlabs/postman-collection/issues/1220

**Comment by helloint** [comment]
This is my experience:
I have one existing collection in maintenance. Usually I update the collection via Postman app. But sometimes I need to do batch operation so I will export the collection to a JSON file and use text editor to finish the work, and then Import again. I will also have a copy in my Version Control so Jenkins will check it out to do automation works.
So, after the Export -> Import -> Export I noticed the `info._postman_id` will change, and I can't find a way to avoid this, even I remove the `_postman_id` before Import.
I tried the App with Version 9.14.14 and also the web app, same results.
Is this the issue @arlemi is looking into? If yes, any updates?

**Comment by Smitzel** [comment]
Any updates? This goes on for years... Must not so hard to fix permanently

**Comment by sprive** [comment]
This is still an issue on Postman 10.12.0.

1. I imported an existing collection. It has existing _postman_id IDs.
2. . When I export that collection (making no changes to it), it now has a _different_ set of IDs. 
3. (Probably user-specific IDs, yeah?)
4. Now... I can manually scrub these from PRs... 


Can we get a documentation word on what the argument was to include personal IDs in an export? 
ie What value gets lost if we delete them? In other applications, when we export something, we completely expect some metadata to be excluded from the export instance.
