### ISSUE TITLE
Prevent desktop icon creation

### ISSUE THREAD

**Issue by butlnor** [a85/POSTMan-Chrome-Extension#2942]
How can I disable creating desktop shortcut everytime Postman is upgraded? This is a serious bug, as no program should create desktop shortcuts without asking a user first. Please either remove the desktop shortcut creation, or add a setting where this can be prevented.

**Comment by numaanashraf** [comment]
Thanks for reporting this @butlnor. We are looking into this.

**Comment by euroclydon37** [comment]
Any update on this? It bugs me to death.

**Comment by asmarkis** [comment]
Requesting this feature as well.

I only use the desktop for shortcuts to files I am currently working on. No apps have shortcuts on my desktop unless programs annoyingly add them every update!

**Comment by hammhacks** [comment]
Requesting as well.

**Comment by SamvelRaja** [comment]
@all 
We have fixed this issue in our latest canary version. Soon will land in the stable version also. 
You can download the canary version from https://www.getpostman.com/canary

**Comment by prashantagarwal** [comment]
Hey Everyone, we have released the fix for this with Postman v6.1.2

**Comment by marie-schmidt** [comment]
Supposed fix released with Postman v6.1.2 but still experiencing same behavior.

**Comment by FriedrichWeinmann** [comment]
Seeing the same behavior here.
Don't use it too frequently, so I suppose it's uninstall time for now.

**Comment by Excellund** [comment]
The desktop shortcut is still appearing periodically for me after deletion.

**Comment by netd-bfry** [comment]
It's 2026 and still happening. Is this no longer a concern for the team? Is there a setting or something we can change to stop this behavior?  I have Postman desktop installed on an external drive and my company's settings do not allow for desktop links for programs on external drives. Now each time it recreates the link I have to go and delete it after getting the violation notice.
