### ISSUE TITLE
No longer remembers open tabs after upgrade to 5.3.1

### ISSUE THREAD

**Issue by lokirangers** [a85/POSTMan-Chrome-Extension#3650]
## App Details:
Postman for Windows
Version 5.3.1
win32 10.0.14393 / x64

## Issue Report:
Since upgrading to version 5.3.1 postman no longer remembers my list of open tabs when I close and re-open postman, and it defaults to a blank list of tabs.   It also displays a blank page as the icon in the task bar.

**Comment by SamvelRaja** [comment]
@lokirangers We are investigating it right away as we speak. will update the thread once we find the root cause.

**Comment by eexit** [comment]
Issue confirmed on macOS Sierra with same Postman version.
This is very annoying :(

**Comment by rkolias** [comment]
Just so you guys are aware of the magnitude, this nasty v5.3.1 version is killing our team. Every day we have tons of tabs open, each developer on their desktop to all various endpoints. And now version v5.3.1 does not remember the last open tabs you had open when you restart it.

Please, please, please I implore you: Make this your highest priority to fix this issue. It is costing time, money, and frustration among our entire team.
Thank you.

**Comment by sdnts** [comment]
@lokirangers @eexit @rkolias We pushed out 5.3.2 which has a fix for this. Can you guys try updating and confirm that it works correctly now?

**Comment by eexit** [comment]
Problem solved!
Thanks!

**Comment by prasadpnair** [comment]
This is happening even in 5.3.2 linux version

**Comment by ltn100** [comment]
Yes, I have v5.3.2 on Ubuntu Linux (16.04LTS), and this is still happening for me.

**Comment by DanielPetatCes** [comment]
This bug is back in Windows x64 Version 5.4.1.
