### ISSUE TITLE
No longer remembers open tabs after upgrade to 5.4.1

### ISSUE THREAD

**Issue by DanielPetatCes** [a85/POSTMan-Chrome-Extension#3902]
## App Details:
Postman for Windows
Version 5.4.1
win32 10.0.16299 / x64

## Issue Report:
Today I updated from version ~~5.4.0~~ 5.3.2 to 5.4.1 and the bug from #3650 is back in Version 5.4.1.

Steps to reproduce:
* Open a tab with any request
* Close postman
* Start it again -> The tab is gone

**Comment by SamvelRaja** [comment]
@DanielPetatCes We were able to reproduce this regression in the windows application. We will patch it up and update the thread.

**Comment by SamvelRaja** [comment]
@DanielPetatCes The issue has been resolved in our canary channel can you try that out and confirm the same from your end?
https://www.getpostman.com/canary

**Comment by prashantagarwal** [comment]
@DanielPetatCes We have fixed this in 5.5.0 release. Feel free to reopen this issue if you are still seeing this.

**Comment by DanielPetatCes** [comment]
Works again, thank you. :)

**Comment by Goltergaul** [comment]
This does not work for me on 5.5.0 on ubuntu. tabs are still not remembered :(

**Comment by harishKD** [comment]
Still happening on Ubuntu(16.04) 
App Version - 5.5.0
