### ISSUE TITLE
[SOLVED] Collection variables not working

### ISSUE THREAD

**Issue by Amer21214** [a85/POSTMan-Chrome-Extension#4105]
## App Details:
Postman for Mac
Version 5.5.2
OS X 15.6.0 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always
 2. Expected behaviour: When using {{_variableName_}} in a request where the _variableName_ is set in the **Collection Variables** section, it is not being recognized in the request which is trying to use it.

![scrsh1](https://user-images.githubusercontent.com/33663710/35389452-0aec447e-01d8-11e8-8a02-17250717e05f.png)
![scrsh2](https://user-images.githubusercontent.com/33663710/35389453-0b061b92-01d8-11e8-96e3-f6bc656f234f.png)

**Comment by vdespa** [comment]
That is a known issue that will be fixed probably in the next release.
You can still use the variables in the request builder, even if they are marked as unresolved.

**Comment by Amer21214** [comment]
Oh, awesome then! :)

**Comment by sdnts** [comment]
@Amer21214 As @vdespa said, these variables are not being populated in the autocomplete menus, but they do work. This has been fixed internally, and it will be out in the next release.

**Comment by geoffatcircle** [comment]
Not sure if this is solved. I realize this doesn't appear correctly in the UI, but it also doesn't work with shared collections or shared documentation

**Comment by afilp** [comment]
Kind of different issue, can you please allow for a combo box in Collection Variables?

See here:

![image](https://user-images.githubusercontent.com/7850073/36587524-19c97044-188e-11e8-85d7-1d98e9d1a59a.png)

I would like to choose just **one** `basse_url` or `token`, so the values should be inside a combo box (needs some changes in the interface)

**Comment by Amer21214** [comment]
Yeah, a new version came out and it still isn't solved. It isn't a "biggy" since the Collection variables do indeed work, it's just that people who start using it will be confused (like me) and think that these variables are not being recognized.

**Comment by prashantagarwal** [comment]
@Amer21214 What is the app version you are using ?

**Comment by prashantagarwal** [comment]
We have fixed these issues in our Canary channel. (https://www.getpostman.com/canary).

**Comment by Amer21214** [comment]
Aaa, it seems to be working now in the "newest new" version. Awesome!!! 👍 :)

**Comment by sivcan** [comment]
Awesome.

**Comment by adenix** [comment]
This does not appear to be working in v6.0.10

![screen shot 2018-03-19 at 9 38 50 am](https://user-images.githubusercontent.com/8764760/37598776-8075c99a-2b59-11e8-9985-746e8d872d5e.png)

![screen shot 2018-03-19 at 9 38 18 am](https://user-images.githubusercontent.com/8764760/37598783-858a95fa-2b59-11e8-8bc2-4fee5495f5c9.png)

![screen shot 2018-03-19 at 9 39 11 am](https://user-images.githubusercontent.com/8764760/37598790-8bf63d7c-2b59-11e8-9a09-290c05a9eac0.png)

**Comment by adenix** [comment]
Nevermind. I have to save the request in the collection, close the request, and then re-open it.

**Comment by MikeNicholsPoints** [comment]
This is not working in 6.2.5 . If I create a collection variable firstName and try to use it in a body as {{firstName}} postman will hang for a moment and then throw the error 

```
Error: Script execution timed out.↵    at 
ContextifyScript.Script.runInContext (vm.js:53:29)
```

**Comment by m3dbedb** [comment]
Same issue in Postman 6.5.2 for windows 7 x86.
I have initial collection variable named "serviceid". Initially I used environment variables and everything worked. Now I'm trying to use collection variables.
I can access it via

    console.log(pm.variables.get("serviceid"));

but setting collection variable fails:

    pm.variables.set("serviceid", jsonData.data[0].iname);

    pm.variables.set("serviceid", "19");
**Update**
I works, but the app does't update values in collection variables editor (look at attached picture)

If you press *update* postman will reset current values with shown on screen
![default](https://user-images.githubusercontent.com/25632818/48772081-5d757200-ecd4-11e8-809e-55d3d9b85ef2.png)
.

**Comment by sivcan** [comment]
@MikeNicholsPoints Apologies for the late reply, can you provide us with more information and possibly the code snippet?
It probably looks like a different issue. Also, read further below in case you're facing the same thing.

@m3dbedb 
Collection variables are read-only in the scripts.
You can only define (or edit) them only when you're manually editing the collection.
That's why 'get' works and 'set' for them doesn't work.

Docs: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#defining-collection-variables

**Comment by m3dbedb** [comment]
It's not stated crear, may I ask you to change the documentation, or where I may ask for it? 

> Note that defining a collection variable is a little different and can be done by editing the collection details.

> Note that defining a collection variable is a little different and can be done by editing the collection details **only**.

**Comment by MikeNicholsPoints** [comment]
@m3dbedb My issue was unrelated. I had a pre-request script that was trying to generate a nonce token based on the body of the POST, but it was hanging when trying to deal with the collection variables. It was user error.

**Comment by sivcan** [comment]
@m3dbedb Yes, we're currently actively working on improving our docs around this and I'd appreciate any feedback you have for us!

We already have a ticket around improving docs for variables which you can follow here: https://github.com/postmanlabs/postman-docs/issues/1442 

Thanks!

**Comment by TheOneDaveYoung** [comment]
Why are collection variables read-only? Let's say I have a collection of related API calls that all need an auth token. I have one API call that collections a new auth token and a test script that grabs that value and stores it (globally or in the environment).

That's a problem for a couple of reasons. First, saving it globally is not good because often times variables like auth tokens will end up using the same name. Plus saving it globally kills the connection to the collection of related API calls.

The second issue, if saving to an environment, is that I have to remember which environment goes with which collection and I have to manually select the environment each time I switch collections and workspaces.

So, a couple of humble suggestions. 
* Make collection variables read/write
* Add the ability to attach an environment to a collection

Thanks so much!

**Comment by nestorvanz** [comment]
I have the next issue for collection variables:

1. Send request for generate token.
2. Read response from request and save token into `token`. (To be used in other request)
3. Send request using `token` generated in the past request. (Not working, the value is missing)

```javascript
pm.variables.set("token", pm.response.json().token);
console.log(pm.variables.get("token"));
```

**Comment by m3dbedb** [comment]
Here is stated that `pm.variables.set("token", pm.response.json().token);` defines local variable, console.log(pm.variables.get("token")); get first existnig variable according to priority https://medium.com/@vdespa/demystifying-postman-variables-how-and-when-to-use-different-variable-scopes-66ad8dc11200

**Comment by alanamircruz** [comment]
In my case I just forgot to select my defined Environment (Development) on the Collection Runner, now I can see the variables working ok inside the tests. If it is useful for someone out there. Anyway, regards.

![image](https://user-images.githubusercontent.com/14240398/55248200-90fb7680-5249-11e9-9f2e-d251673b3334.png)

**Comment by axa88** [comment]
>     * dd the ability to attach an environment to a coll

This should be made its own new issue. i tried doing this until i uninstalled postman thinking it was just flaky

**Comment by axa88** [comment]
> 
> 
> Why are collection variables read-only? Let's say I have a collection of related API calls that all need an auth token. I have one API call that collections a new auth token and a test script that grabs that value and stores it (globally or in the environment).
> 
> That's a problem for a couple of reasons. First, saving it globally is not good because often times variables like auth tokens will end up using the same name. Plus saving it globally kills the connection to the collection of related API calls.
> 
> The second issue, if saving to an environment, is that I have to remember which environment goes with which collection and I have to manually select the environment each time I switch collections and workspaces.
> 
> So, a couple of humble suggestions.
> 
>     * Make collection variables read/write
> 
>     * Add the ability to attach an environment to a collection
> 
> 
> Thanks so much!

This should be made its own new issue. I kept trying to change a collection variable until i thought postman was flaky, uninstalled and just wrote an application.

**Comment by rcdailey** [comment]
I'm still seeing this issue on v7.2.2. This isn't fixed at all. Unless I'm missing something, but this should be really straightforward. I define a variable called `url` in my collection. I do `{{url}}/my/api/call` in the URL field for my request. The `{{url}}` shows as unresolved by Postman.

**Comment by alanamircruz** [comment]
Try removing (refreshing) your environment variables. It happened to me:
double check the declaration and using the proper settings (needed to
remove them then re add the environment.json file)

**Comment by rcdailey** [comment]
What do you mean "removing/refreshing environment variables"? These are collection variables, I do not have an environment set. I'm new to Postman so if I'm missing something please let me know.

**Comment by alanamircruz** [comment]
So as me Robert, none an issue.

I wish I could show how we manage this stuff but reading a little bit of
this helped us in the past.

https://blog.getpostman.com/2017/12/29/10-tips-for-working-with-postman-variables/

Let me know if you want we can check the issue/situation directly.

Regards,
Alan

**Comment by rcdailey** [comment]
I have already read that article. Again I think this should be pretty straightforward. Variables work if I set them in an environment. But if I set the environment to empty/none and then set them in the Collection, it doesn't resolve the variables.

**Comment by ajdriver** [comment]
> I'm still seeing this issue on v7.2.2. This isn't fixed at all. Unless I'm missing something, but this should be really straightforward. I define a variable called `url` in my collection. I do `{{url}}/my/api/call` in the URL field for my request. The `{{url}}` shows as unresolved by Postman.

@rcdailey I had the same issue `7.3.1.`, was a simple case of not saving the request.  Once I saved it, the collection variables were recognised

**Comment by kjnz** [comment]
I'm on `Postman v7.3.2 ` which I gather is the latest version.  This issue still persists.. 
Cannot use collection variables in the requests. 
I define  a variable `HomeUrl` in my collection.  When using the variable is shows as Unresolved. 

Interestingly, on the postman console, it shows an invalid URI...
`Error: Invalid URI "http:///%7B%7BHomeUrl%7D%7D/api/users/2"`

How a https is resolving into http in beyond me at the moment!!

**Comment by arrk-shch** [comment]
I am using v7.3.3. I am facing same issue. Not able to set "token" variable in collection. It works in environment and global variable.

**Comment by coditva** [comment]
Hey @rcdailey @arrk-shch 

Unfortunately, I have been unable to reproduce this issue. Can you provide me with some more info:
1. Is the request in which you're accessing the collection variable saved in the same collection? (It should be listed in the sidebar under the name of the collection).
2. Does the issue still persist after closing the request tab and re-opening it from the Collections sidebar?
2. If there is an environment variable of the same name as the collection variable? (Environment variables take precedence over collection variables. Ref: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#variable-scopes)

Also, if you can relate your steps to reproduce this issue, it would really help accelerate the process.

**Comment by arrk-shch** [comment]
Thanks @coditva for quick response.
I am trying simple scenario in postman. I have created a "token" variable in collection. First, I am executing Login API where I get the token in the header. This received token, I am trying to set it in collection variable. And then using the collection variable "token" in my next script under authentication tab as BearerToken selected in Type dropdown box and {["token"}} in Token textbox. But its not working as the variable is not getting set in collection.
Here is reply to you points
1.  Yes 
2. It simply doesn't get set. Tried restarting the postman as well.
3. There is no duplicate variable in my environment, global & collection variable. When I hover the {{token}} then it shows me the scope of the variable as collection
 Let me know if you need more info.
Thanks

**Comment by coditva** [comment]
@arrk-shch I see. The problem lies in the fact that Postman does not allow collection variables to be set with scripts.
Ref: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#accessing-variables-through-scripts

A feature request to allow this can be found here: https://github.com/postmanlabs/postman-app-support/issues/5053.

A quick solution would be to remove the token from the collection variables and set it as a global/environment variable.

**Comment by tomshy** [comment]
> Not sure if this is solved. I realize this doesn't appear correctly in the UI, but it also doesn't work with shared collections or shared documentation

having same issue? has it been solved?

**Comment by PeterStaev** [comment]
I'm also experiencing this problem. I have defined variables in the collection. Not even modifying in Tests. And they are not recognized nor they are sent correctly. Here is a sample collection json:
```json
{
  "info": {
    "_postman_id": "5e697462-e318-411a-b0e0-71174f51365e",
    "name": "Sample",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "Test",
      "event": [
        {
          "listen": "prerequest",
          "script": {
            "id": "fc300f35-f3de-433d-be6d-72ac086a6335",
            "exec": [
              "console.log(pm.collectionVariables.get(\"SomeVar\"))"
            ],
            "type": "text/javascript"
          }
        }
      ],
      "request": {
        "method": "GET",
        "header": [
          {
            "key": "Var",
            "value": "{{ SomeVar }}",
            "type": "text"
          }
        ],
        "url": {
          "raw": "https://localhost/test?var={{ SomeVar }}",
          "protocol": "https",
          "host": [
            "localhost"
          ],
          "path": [
            "test"
          ],
          "query": [
            {
              "key": "var",
              "value": "{{ SomeVar }}"
            }
          ]
        }
      },
      "response": []
    }
  ],
  "variable": [
    {
      "id": "73a9a812-d9a4-4e85-aeae-450f66e8cee2",
      "key": "SomeVar",
      "value": "Test",
      "type": "string"
    }
  ],
  "protocolProfileBehavior": {}
}
```

**EDIT**
Fixed. Problem was that I had spaces around the variable...

**Comment by MuhammadimYusoff** [comment]
I have the same problem and this is year 2020 guys, this issue not fixed on macOS release v7.

*Workaround at the end of this post

Below is my version screenshot if you wanted:-
<img width="720" alt="Screenshot 2020-02-04 at 3 28 38 PM" src="https://user-images.githubusercontent.com/43903543/73723898-194d8080-4765-11ea-989f-fb11fe26e85c.png">


My problem goes back beyond 2018 it seems because someone appoint me the issue to this tread, "Unresolved Variable (not environment)".

1) I created my variable in my collection, updated or saved it:
<img width="639" alt="Screenshot 2020-02-04 at 3 28 15 PM" src="https://user-images.githubusercontent.com/43903543/73723789-de4b4d00-4764-11ea-9575-f0ab36ff3bb1.png">


2) I tried to use it after I have update it but "Unresolved Variables" appear:
<img width="416" alt="Screenshot 2020-02-04 at 3 31 06 PM" src="https://user-images.githubusercontent.com/43903543/73723862-05098380-4765-11ea-9a96-16b2ea0a31ff.png">



Workaround by @adenix:
> I have to save the request in the collection, close the request, and then re-open it.


But cant Postman just 'Update' it and Users can use it on-the-fly?
Kinda tedious to closed a tab about 10 times and re-open it again for a new variable added.

**Comment by greatromul** [comment]
I got the same problem in 7.22.1. Downgrading to 7.21.2 fixed the problem.

**Comment by wildfrontend** [comment]
maybe some issue just remove empty word could be work 
check whether the variable have Enter keyword behind

<img width="692" alt="截圖 2020-05-13 下午11 15 54" src="https://user-images.githubusercontent.com/20965813/81831242-b479a180-956f-11ea-9816-27381ce05b42.png">

**Comment by kidstell** [comment]
v7.29.0 collection variables not working. It picks environment variables correctly but it wont even detect the collection variables.

**Comment by coditva** [comment]
@kidstell I haven't been able to reproduce this. Can you elaborate on the exact steps you took (e.g. create collection, go to edit collection, add variable, etc.)? It would also help if you can tell us the expected outcome and actual outcome that you saw.

**Comment by willbt** [comment]
> v7.29.0 collection variables not working. It picks environment variables correctly but it wont even detect the collection variables.

I am seeing the same thing. Collection Variables set in the Tests as pm.collectionVariables.set("key", "value") are null when you reference them as {{key}} in the headers or other tests.

**Comment by kidstell** [comment]
It now works fine after restarting the Application.

**Comment by jagruuti** [comment]
I have defined a variable as a global variable and trying to use it in another request. I'm getting the same error as below:
![image](https://user-images.githubusercontent.com/45683782/114690028-f2f57e80-9d33-11eb-8cf6-d8a3f2e74c15.png)
Version used v8.1.0

**Comment by jagruuti** [comment]
> I have defined a variable as a global variable and trying to use it in another request. I'm getting the same error as below:
> ![image](https://user-images.githubusercontent.com/45683782/114690028-f2f57e80-9d33-11eb-8cf6-d8a3f2e74c15.png)
> Version used v8.1.0

It is working now. Strange!

**Comment by j1mmie** [comment]
For any Googlers who arrive here - **make sure you click the Save button** after adding / changing variables.

Variables will not be recognized until they are saved. This is true both for Collections AND Environments.
