### ISSUE TITLE
Request name (pm.request.name) is undefined in Tests

### ISSUE THREAD

**Issue by gjnk** [a85/POSTMan-Chrome-Extension#4124]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **First time trying this**
 2. Expected behaviour: **Expected pm.request.name to return the name of the Request**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **See below**
 4. Screenshots (if applicable) **N/A**

pm.request.name

I am trying to get the name of the request in a Test using pm.request.name.
For example I have a request called Request1 (it also has a description 'Request 1 description')
If I put the following code 
```
console.log(`Request Name: ${pm.request.name}`); //expecting "Request1"
console.log(`Request Description: ${pm.request.description}`); //expecting "Request1 description"
```

On the console then I see the following:

> Request Name: undefined
> Request Description: Request1 description

**Comment by gjnk** [comment]
Actually I found a workaround: rather than using pm.request.name I can use request.name which works.
FYI, as for the description attribute it works both ways: pm.request.description and request.description

**Comment by sdnts** [comment]
Hi @gjnk, I was able to reproduce this, `pm.request.name` should have been resolved correctly. We'll look into this.

**Comment by codenirvana** [comment]
@gjnk Request name can be fetched via `pm.info.requestName` or using the workaround you suggested.

**Comment by abhijitkane** [comment]
@codenirvana Why do we have different behavior for name and description?

**Comment by codenirvana** [comment]
`pm.request.description` is inherited from the `PostmanItem`.
This is because of a bug in SDK, where the description will be added to all the child class which extends `PostmanProperty`.

**Comment by mberdev** [comment]
the issue is still there in May 2024, 6 years later.
pm.request.name is undefined.
Someone wrote that the correct field is `pm.info.requestName` , but `pm.request.name` is still the field suggested by the **autocomplete** in Postman's script editor.

**Comment by orhunerd** [comment]
as @mberdev put it with the new version postman.request format is depreciated because of this users are trying to update the expected way of doing this.
Since pm.request.name is returning undefined, I had to use the workaround pm.info.requestName

**Comment by humbienri** [comment]
Deprecated not depreciated.

**Comment by alexturkovic** [comment]
> the issue is still there in May 2024, 6 years later. pm.request.name is undefined. Someone wrote that the correct field is `pm.info.requestName` , but `pm.request.name` is still the field suggested by the **autocomplete** in Postman's script editor.

Even Postbot returns pm.request.name, ask "log the name of the current request" and it returns:

pm.test("Log the name of the current request", function () {
    console.log("Current request name: " + **pm.request.name**);
});

Can't believe something so simple hasn't been resolved.

**Comment by andymaycoates** [comment]
Why is this bug closed? In the very least the code editor should remove pm.request.name as a suggestion if this will never be fixed.

**Comment by crifdc20250224** [comment]
At least nowadays, Postbot suggests to use `pm.execution.location`; editor still suggests `pm.request.name`.
