### ISSUE TITLE
Postman starts very slow in Windows

### ISSUE THREAD

**Issue by cr2121** [a85/POSTMan-Chrome-Extension#4262]
## App Details:

```
Postman for Mac
Version 6.0.7
OS X 10.13.3
```

**Comment by kamalaknn** [comment]
Hi @cr2121 

Can you give us more details for us to investigate this better? Please drop us a mail with the following info to `help[at]getpostman.com` from your registered email address.

1. A screencast of your startup experience.
2. Logs for the common process,  `View -> Developer -> Show DevTools(Shared)` and `Right Click -> Save As`. Please forward the logs through email as this might contain sensitive data.

**Comment by kamalaknn** [comment]
Closing this due to inactivity. Please reopen if you still find the issue on our latest version.

**Comment by duyn9uyen** [comment]
This is still an issue for me.  Startup is very slow.
Postman v6.0.10 
Windows 7 64-bit

**Comment by kamalaknn** [comment]
@duyn9uyen we've made some performance improvements to startup time in the latest version of Postman. Could you update to the latest version `6.1.2` or higher and give it a try?

**Comment by cesardl** [comment]
I have the same problem right now with Postman `6.1.2` 64 bits on Windows 8.1. I saw that 3 windows process launched on postman startup and mouse cursor show an loader as if to my machine is making a job on background and the app never starts.

**Comment by Xoloitzcuintli** [comment]
Same here, was working just fine til I clicked on the update button.  Now startup is very slow to no startup at all.

**Comment by prashantagarwal** [comment]
@Xoloitzcuintli if you are on windows, it could be issue with GPUs that we are facing currently. Can you try the workaround mentioned here https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by greenais** [comment]
The same here:
- busy mouse pointer blinking repeatedly
- several postman instances running according to Task manager (the most hungry one consumes about 30% of CPU)
- empty pale main window for more than 180 seconds (menu is resposible though)

Started after recent update from app itself. 
Tried to wipe it out (from .../AppData/...) and reinstall - no better.

Postman: 6.1.3
Windows 8.1/64 

UPD: 
POSTMAN_DISABLE_GPU=true 
workaround helped, no issues now.

**Comment by FixMaestro** [comment]
Having issues also. Using Process Explorer, while installing Postman, it churns up 7-8 threads, then after a bit, settles down to 4 running threads with a new thread being started and killed off about every second. I've been waiting over 5 mins and it's still starting/killing a 5th thread over and over. I'm using Win Svr 2012 R2 box inside VMWare Workstation to run this on

**Comment by tpopov94** [comment]
I have the same issue with latest version of Postman on Mac OS X 10.13.3. It took around ~5 minutes to start which is unbearable.

**Comment by harleydk** [comment]
Same issue here on Windows 8.1. Blinking, threading, menu working though no functionality available. Version 6.1.3, win 64.

Have no GPU, running HP probook with integrated graphics (if any). 
Added the environment-variable described in #4594.
Then went to C:\Users\<myuser>\AppData\Local\Postman\app-6.1.3, right-clicked Postman.exe and set to Windows Vista compatibility. Now it starts up OK. Not sure the environment-variable thing was necessary.

**Comment by jedrennen** [comment]
This should be reopened...I am having the issue as well on Windows 8.1, Postman v6.1.4.  The chrome of the application shows up, but all black otherwise. CPU usage spikes (so CPU fan on my X1 carbon ramps up), mouse cursor blinking and choppy.  If I am very patient (waiting 5 or more minutes) it seems to open up.  I tried removing Postman everywhere and doing as clean of an install as possible and no change.  Finally used @harleydk suggestion to set to Windows Vista compatibility and it opened right up!

**Comment by jonathan-techtwo** [comment]
The same symptoms as greenais

* boot time ~5 minutes
* busy mouse pointer blinking repeatedly
* several postman instances running according to Task manager (the most hungry one consumes about 30% of CPU)
* empty pale main window for more than 180 seconds (menu is responsive though)

Version : v6.1.4
Windows : 8.1 Pro
Collection size: 150 requests

I already discarded the %user%AppData\Roaming\Postman\requester.json the have it refreshed. Cleared the cache folder but no luck. I found myself writing a curl request instead of opening, which was a lot faster.

**@harleydk suggestion to set Windows Vista ( I set Windows 7 ) worked !**

**Comment by 0xlsca** [comment]
Can add to that, ludicrous startup time.

Setting compat mode to Win Vista solved the problem.

Win 7 Prof 64
HD 6950
24GB 1600 DDR3
FX 8320E

**Comment by libasoles** [comment]
Same here using Linux (latest Manjaro KDE).
5minutes and still seeing the splash with "Preparing your workspaces... This might take a few minutes".

I wonder why. I'm using it since 2 months already. 

UPDATE: solution for Manjero/Arch linux is reinstalling using postman-bin instead. 
https://github.com/postmanlabs/postman-app-support/issues/4374

**Comment by rahul202** [comment]
Same here on MAC...
Where is the most time spent? Fetching what details? it was supposed to be very weight app....
if it can used as chrome app, then why it is so heavy to launch.

**Comment by nejcr** [comment]
Please fix it, its a great much-needed software, but it has really become to slow to work with, as described in the comments above.

**Comment by duyn9uyen** [comment]
With so many people reporting this is still an issue, can an admin of this thread reopen this?

**Comment by prashantagarwal** [comment]
Hey guys, some people have reported that this issue is also caused by the GPU issue for which we have proposed a workaround here https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621 . Please do let us know if this workaround doesn't solve the issue. In the meantime we are also actively working to find the solution for this.

**Comment by jonathan-techtwo** [comment]
Hi @prashantagarwal , I've checked it again. Using the workaround of #4594 does fix it. I have multiple times deleted and added the work-around. I'm pretty sure it fixes the issue for me without using the backwardscompatible option.

I am using the internal INTEL GPU, I don't have a graphics card installed.

**Comment by winzig** [comment]
I'm on a 2017 MacBook Pro, macOS High Sierra 10.13.6, and in general Postman is very, very sluggish. 

I'm running Postman 6.2.2 right now. Are you saying there are GPU issues in my environment as well, or only on Windows?

My experience is that when I start up Postman, it takes about 5-10 seconds before the UI responds to my click to switch to the "Collections" panel, and then another 5-10 seconds or so before that panel actually loads any collection data. In general, clicking on things in the UI is sluggish even after startup has finished. And if I've been running Postman for a while in the background, when I switch over to it, it seems quite sluggish while warming back up.

**Comment by nejcr** [comment]
Switched to postman canary , works as expected

**Comment by Ameer499** [comment]
Same issue with me.

**Comment by winzig** [comment]
I concur with @nejcr, switching to [canary build](https://www.getpostman.com/canary) also seems to have resolved my performance/startup issues on macOS! Wonder what changed.

**Comment by Coffee-Boyy** [comment]
Setting POSTMAN_DISABLE_GPU=true worked for me

**Comment by johanroug** [comment]
C:\Users\xroug\AppData\Local\Postman\app-6.2.5\Postman.exe --disable-gpu

Worked for me

**Comment by maccurt** [comment]
This is also happening to me, I get a blinking cursor and it take forever for postman to load I see several postman processes. I will try some of the fixed above and try to update

**Comment by maccurt** [comment]
I used C:\Users\[MYNAME]\AppData\Local\Postman\app-6.3.0\Postman.exe --disable-gpu and all I now get is the planets orbiting a bigger planet (or sun), and it just hangs there.. As a Software developer I understand things break, so I will be patience..

**Comment by FrenchMigVaz** [comment]
When it happens to me, I kill every PostMan process and restart, usually the app then opens instantly.

**Comment by ntodorov** [comment]
I have v6.6.0 for windows and the slow startup showed up today - not as bad as in older versions that I've tried (at the time took more than a minute to start up) but still waiting 20-30s is very annoying compared with the instant opening of the Postman chrome extension.
Adding POSTMAN_DISABLE_GPU true as System Environment variable actually helped, but I waned to tell you that it is still not fixed in 6.6. 
In the documentation the POSTMAN_DISABLE_GPU was for 6.1

Great tool though! Keep up the good work!

**Comment by manish-kevre** [comment]
> When it happens to me, I kill every PostMan process and restart, usually the app then opens instantly.

This Solved my problem.

**Comment by cameliag90** [comment]
Hei, I still have this problem. Just downloaded the latest version of postman 6.7.3, set also the POSTMAN_DISABLE_GPU variable to true but no enhancement. Opened the app 5 minutes ago and I still have a black screen.

**Comment by damireddye** [comment]
I'm still having this issue. It takes ages for the postman to load. Sometimes 1 or 2 hours.
I've used this version to install Postman-win64-6.7.4-Setup
![image](https://user-images.githubusercontent.com/24477793/53491634-c9633580-3a8e-11e9-9bf0-6b2646a8e689.png)

**Comment by Medy111** [comment]
this issue is the reason im still using the chrome plugin which is depracated... still not fixed with latest install...

**Comment by highlyunavailable** [comment]
Same issue, Postman-win64-7.0.5. Disabling GPU fixed? it.

**Comment by DHOTRAMP** [comment]
Post man 6.0 + version works setting environment variable  -  POSTMAN_DISABLE_GPU : true. 
But latest update (7.0 +) breaks and taking long to launch.

**Comment by a-gonzalez** [comment]
Been having this issue for months. Any updates / fixes? We should just write our own open-source API tester.

Version 7.6

**Comment by JackAllread** [comment]
I used the POSTMAN_DISABLE_GPU=ture to handle the slow start up on server 2012 I remote into with Postman version v7.0.7. It started right up after setting the environ variable.

**Comment by a85** [comment]
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4594. We will be publishing an update soon on the related thread.
