### ISSUE TITLE
Postman Not Displaying Full Request Response Body On Startup

### ISSUE THREAD

**Issue by jwbats** [a85/POSTMan-Chrome-Extension#4407]
Whenever I open up Postman, it will show me the request I had last selected when I closed it, and it will also show me the response that it sent back the last time I fired off this request.

The problem is that the response text area isn't showing enough lines, obfuscating the response. It will only show 2 lines of my 3 line response. When I click it, it'll show me only the last line of my response.

See screenshots.

My response is supposed to display as:

```
{
    "id" : "something something"
}
```

But on startup it displays:

```
{
"id" : "something something"
```

And on click (or downscroll) it'll display:

```
}
```

Scrolling up and down won't fix it. I have to explicitly select another request to make PostMan properly display the response body with the proper amount of lines.

**Comment by DanielPetatCes** [comment]
I've got the same issue.
Windows 10 1709 x64
Postman 6.0.10 x64

I noticed, that the window is not maximized after startup. When I maximize it, the display is correct. So it seems to be a rendering or alignment issue of the textbox after startup.

**Comment by harryi3t** [comment]
@jwbats @DanielPetatCes This is known issue and we are fixing this. Will update this thread once the fix is released.

**Comment by codenirvana** [comment]
This issue is fixed in the latest version of the Postman app. Feel free to reopen if the issue persists.

**Comment by ajeets1978** [comment]
This still seems to be an issue, I have more than 20 records in my database returning in one of the api, but postman doesn't show all of them. it only shows around array of 20 records.

**Comment by ajeets1978** [comment]
> This still seems to be an issue, I have more than 20 records in my database returning in one of the api, but postman doesn't show all of them. it only shows around array of 20 records.

--- Seems like that was mistake at my end, didn't realize that the api's, I am using automatically does the pagination, realized when checked the response headers.

**Comment by jessewriter** [comment]
win 11, postman 10.7.0
i was only seeing about half of my results and wasted time debugging my code when it was a darn postman issue.  resizing postman response window larger magically brought all my responses :(  updating to 10.8 does not fix.  THIS IS A CRITICAL ISSUE for developers!

**Comment by MarkCay** [comment]
This still occurs whenever we're using Postman Web. The response is not displaying the full JSON response body.

```
MacBook Pro macOS Sonoma 14.0, Apple M1
```

<img width="862" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44314383/c6c84055-16cf-4aee-94cb-ff4e1d4a279e">
