### ISSUE TITLE
Postman stuck on splash screen after update

### ISSUE THREAD

**Issue by alanatkinson** [a85/POSTMan-Chrome-Extension#4642]
After self-upgrading to 6.1.3 on a Mac running High Sierra 10.13.4 the postman app fails to get past the launch screen regardless of how long one waits. 

The last thing you see is "Preparing your workspaces... This may take a few minutes"

The log from devtools shows the following:

Uncaught (in promise) Error: Callback was already called.
    at vendor-shared.js:100559
    at vendor-shared.js:125393
    at initializeServices.then.catch.e (shared.js:8747)
    at <anonymous>

Trying it with Canary, it at least launches, but then you lose all your local saved calls. Which is problematic.

**Comment by dannoso** [comment]
Same here, the problem seems incompatibility with the old database. you can delete the postman dir in Application Support. It launches but of course is empty. This is very annoying as i lost al my data.

**Comment by SamvelRaja** [comment]
@alanatkinson  can you share the complete logs from devtools? 

You can `right-click -> Save As` in the console.  

This will give us a complete picture of what goes wrong.

**Comment by suur** [comment]
Same thing happening on Arch Linux with https://aur.archlinux.org/packages/postman/ after upgrading to 6.1.3
The problem won't go away even after deleting ~/.config/Postman, although I can then see the login page and open developer tools. There is an `Uncaught ReferenceError: require is not defined` error already at the login page, and the splash screen does not produce further errors. I have posted the full log here https://pastebin.com/ac9TkvUx

**Comment by lukasz-gosiewski** [comment]
Same on ArchLinux. Even after deleting config, reinstalling the app. Sudo also not working.

**Comment by WurstCommander** [comment]
Same under Windows as well, I'm stuck on the splash screen.

**Comment by SamvelRaja** [comment]
@suur @lukasz-gosiewski  The link you provided is not officially supported by Postman. We support the platforms listed [here](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#supported-platforms)

And  @WurstCommander  Kindly provide me more information on this.
Open the app via cmd, `C:\users\[USER]\AppData\Postman\app-6.1.4\Postman.exe` and show the logs you have. Additionally, it would be helpful if you can provide me the version from which you are upgrading to.

**Comment by SamvelRaja** [comment]
@alanatkinson can you confirm that this issue still persists in the latest version 6.1.4 version of the app.

**Comment by alanatkinson** [comment]
No I can't. 
I had to throw the whole thing away and start over with a new set of requests that I created in Canary to do what I actually wanted to do.  
Four hours of my life I won't get back. If I'd known it was a breaking change I would never have taken it.
I already posted the relevant part of the log.

**Comment by suur** [comment]
@SamvelRaja The link I provided is a basically a repackaging script for the official binaries. I can confirm 6.1.4 works again on Arch Linux, although I have deleted my config. 6.1.3 did not work even with a fresh config.

**Comment by wiggisser** [comment]
Postman 6.0.10 was running fine until today I clicked update to 6.1.4. Postman wouldn't start.

Symptoms:

1. The splashscreen wouldn't show the orbit animation and just stay orange-yellow. After a few seconds it closes and a postman window comes up. A few seconds later the menu appears. But then it's stuck at this stage. Waited for several minutes, no change. I can click menu items, but nothing happens. Tried to show developer console. The window opens but stays black.

2. There is high cpu usage for multiple postman processes. And even the `System` process uses up to 30% CPU while I try to start postman. Waited for several minutes. CPU usage didn't go down.

3. Immediately after I kill all postman processes with `taskkill /im postman.exe /f` also the CPU usage of the `System` process goes down. 

4. Uninstalled Postman 6.1.4 and installed 6.1.3. Same symptoms. When I look in the `C:\Users\karl\AppData\Local\Postman`  folder I see also a `app-6.1.4` folder, eventhough I installed 6.1.3 and never even had a chance to click on update, because the GUI wouldn't start.

5. Uninstalled again and deleted the remaining Postman folders `C:\Users\karl\AppData\Local\Postman` and `C:\Users\karl\AppData\Local\Postman`. Installed Postman 6.1.3 -> same as in 4)

6. Uninstalled again and downloaded 6.0.10 (why did you remove the downloadlink???). This version works fine.

Somewhere in this process, I also started postman 6.1.4 from the CMD. I Attached the console output. 

My environment: Windows 8.1x64 with latest updates, GPU NVIDIA GeForce 940M


[postlog.txt](https://github.com/postmanlabs/postman-app-support/files/2179939/postlog.txt)


**EDIT**

I just now found issue #4594 and can confirm, the workaround using the environmen variable solves the issue for me and Postman 6.1.4 is now working.

**Comment by Postman-Gabriel** [comment]
This issue is still present on update 6.1.4. My user is using windows 7 x64 with 6.1.4 and they can't open the app at all. It happened all of the sudden after updating from 6.1.3.

This is the screen they are stuck on.

![error](https://user-images.githubusercontent.com/40899145/42961833-d729b468-8b44-11e8-813e-062e014fa929.png)

**Comment by ssjena** [comment]
Hi All,
          My postman version 6.1.4 is not opening after upgrade. can someone help . Below screen is coming.
![42961833-d729b468-8b44-11e8-813e-062e014fa929](https://user-images.githubusercontent.com/41780565/43311773-9769aa8e-918b-11e8-9c91-5e95a19eea60.png)

**Comment by SamvelRaja** [comment]
@ssjena @gabriel-bronfman-postman  Could you open the app via `cmd`  from `C:\users\[USER]\AppData\Postman\app-6.1.4\Postman.exe`

**Comment by ssjena** [comment]
Hi @SamvelRaja ,

                             I have tried from CMD as well but its all same. Do you have any solution to this issue.

**Comment by SamvelRaja** [comment]
@ssjena  Can you show the logs generated in cmd when you open the app.

**Comment by ssjena** [comment]
i got it resolved now . I have deleted all postman stuff from local,roaming folder in C drive and reinstalled it and worked.

Thanks

**Comment by WurstCommander** [comment]
Yesterday the bug was back, I had the close the postman.exe with taskmanager and at last postman started.

**Comment by Prussia** [comment]
I am suffering from the issue too. Version 6.5.2 (6.5.2) on mac
![image](https://user-images.githubusercontent.com/3626983/48764776-9836d480-eceb-11e8-9619-c6d7a2e227d6.png)

**Comment by blowsie** [comment]
A year has passed and I still have this issue.

related: https://github.com/postmanlabs/postman-app-support/issues/4605

**Comment by Prussia** [comment]
Should be something wrong with workspace data. After i clean up the workspace, it looks fine.

**Comment by kamalaknn** [comment]
Hey @blowsie 

Sorry for the delayed response. We'd like some more information to debug this issue better.

1. Can you download the latest version of Postman v7 from (https://www.getpostman.com/downloads/) and see if the issue still persists?
2. If you are seeing the issue on the latest version, can you try the workaround for turning off GPU acceleration mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621)
3. If you are still seeing the issue, can you send the logs to `help@getpostman.com` for us to take a better look?

You can find the logs using `View -> Developer -> View logs in explorer`. If you are not able to see the menu bar, you can find the logs in the director under

```

MacOS:
"~/Library/Application Support/Postman" 

Windows:
"C:\Users\<user>\AppData\Roaming\Postman" 
"C:\Users\<user>\AppData\Local\Postman"

Linux:
"~/.config/Postman"
```

**Comment by blowsie** [comment]
@kamalaknn  thanks for the response.

I fixed it by deleting
`C:\users\[USER]\AppData\Roaming\Postman` 
`C:\users\[USER]\AppData\Local\Postman` 

+ Reinstalling

**Comment by kamalaknn** [comment]
@blowsie Thanks for getting back to us with the info. 

I think the issue you have been seeing might be related to https://github.com/postmanlabs/postman-app-support/issues/5591

I'm closing this since the original issue seems to be related to GPU and that has been fixed in the recent version of Postman.
