### ISSUE TITLE
Integrations > Github repository dropdown only shows 100 repos

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4861]
Seen for Pro/Enterprise users:

While trying to add Github Integration to my company Postman account, but I wasn't able to select the proper repository from the dropdown, because it wasn't returned in the list. I looked at the request and it had `?top100` as a parameter, so only 100 repositories were returned. Since my company has over 200 repositories and the one I wanted began with a 'V', I was not able to select the repository I needed.

**Comment by godfrzero** [comment]
@ankitjaggi This is resolved now, yes?

**Comment by ankitjaggi** [comment]
@godfrzero Yes

**Comment by ankit-m** [comment]
@abhijitkane Can we close this issue?

**Comment by dvdoliveira** [comment]
I've just created a support ticket for this issue and got a message from Chris (Postman support) pointing to this GH issue. I have the same problem reported by @abhijitkane so it isn't fixed yet. @ankitjaggi Could you please take a look?

**Comment by chrisdeso** [comment]
![image](https://user-images.githubusercontent.com/4734306/45982852-49343200-c00f-11e8-8870-c4e55ab6017f.png)

Here's a screenshot from @dvdoliveira 😄

**Comment by chrisdeso** [comment]
![image](https://user-images.githubusercontent.com/4734306/45982947-93b5ae80-c00f-11e8-8ec3-396b9fceb975.png)

Here's a screenshot from @dvdoliveira 😄

**Comment by abhijitkane** [comment]
@dvdoliveira Can you check if this works correctly for you now?

**Comment by abhijitkane** [comment]
Closing due to inactivity
