### ISSUE TITLE
Postman Echo converts decimals to integers

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5246]
**Describe the bug**
Decimals – more specifically, trailing zeros in a `POST` body i.e. `.0` – are displayed as integers in pretty view (json).

**To Reproduce**
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/8a4af0ced06ac965c606)

Send `POST` request to Postman echo service with JSON key-value pair that has an integer with trailing zeros (after decimal).

**Expected behavior**
Not removing zeros to the right of the decimal :)

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/46036163-b0a6bc00-c0b9-11e8-9396-2423051b77c2.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: `6.3.0`
 - OS: MacOS

**Comment by numaanashraf** [comment]
@chrisdeso Do we have an example without echo service? Echo seems to be stripping the 0 by itself. I tried replicating this with http://4342283e-0eaa-4ab6-bdf0-bb45224e7bd1.mock.pstmn.io/get and it worked as expected.

/cc @kunagpal

**Comment by garychapman** [comment]
+10000000000000 I just wasted 2 hours because of this bug, PLEASE FIX IT

**Comment by numaanashraf** [comment]
@garychapman Could you elaborate on your issue? This specific issue seems to be on the Postman Echo service.

**Comment by garychapman** [comment]
@numaanashraf I'm seeing it on Postman v6.7.1 in Pretty view only (Raw and Preview are ok).

I've highlighted the _AvgCost_ value where Postman has removed the trailing decimal zero.

![image](https://user-images.githubusercontent.com/2315465/50942641-797bdf80-14dd-11e9-82d4-3177c946e8ab.png)

**Comment by ArjanKranenburg** [comment]
Is there any progress on this?
Just found out that the 'Beautify'-button does the same with the input. Perhaps the 'Pretty' tab from the output re-uses the same code, then the Beautify button is easier to reproduce.
It's also annoying because it took me a while that it had actually changed the values, not just indentations and such.

**Comment by DannyDainton** [comment]
Hey @ArjanKranenburg 

Would you be able to provide an example of what you're seeing in the latest version for that beautify issue, please?

**Comment by ArjanKranenburg** [comment]
I cannot reproduce this anymore. Perhaps it was solved in the latest version?

**Comment by DannyDainton** [comment]
Thanks for getting back to me - I'm going to close this one out for now but if the issue reappears for other users, we can open the issue again.

**Comment by ramprakash-CA** [comment]
<img width="907" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/124230741/6e55cabe-cb5a-4f12-ba4f-eb267fbbaa98">

Decimals – more specifically, trailing zeros in a POST body i.e. .0 – are displayed as integers in pretty view (json).

This Issue Is still persistent! @DannyDainton @ArjanKranenburg 

U can reproduce the same by providing any Value with trailing zeros after decimal . 


Expected behavior
Not removing zeros to the right of the decimal :)
