### ISSUE TITLE
Run in Postman button doesn't open app on Linux

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5273]
**Describe the bug**
Using the Run in Postman button on Linux doesn't launch the native app

**To Reproduce**
1. Fire up Ubuntu 17.10
2. Navigate to `https://docs.api.getpostman.com/`
3. Click on the Run in Postman button on the top right
4. Select `Open with...` > `Postman for Linux`
5. Select `Open xdg-open` on the modal that appears
5. Notice that nothing happens

**Expected behavior**
The native Linux app is expected to open and the collection/environment to be imported should be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/46175804-103fcb80-c262-11e8-9268-960dd4636b3b.png)

**App information (please complete the following information):**
 - App Type: Native app 
 - Postman Version: `6.3.0`
 - OS: Ubuntu 17.10

**Comment by SamvelRaja** [comment]
@chrisdeso 
Could you send the Postman.desktop file you have?

**Comment by Ativerc** [comment]
I have Ubuntu 16.04 and the tarball for the latest version of Postman (Postman-linux-x64-6.3.0.tar.gz) doesn't contain any makefile and it just extracts the files and we have to run from there. There's no `.desktop` file. 

Is it possible to automate the creation of `.desktop` file for Postman on Linux?

Also could someone explain how "Run in Postman" depends on the `.desktop` file?

**Comment by danie16arrido** [comment]
I fixed it on Ubuntu 17.10 by adding postman protocol to   `~/.local/share/applications/mimeapps.list`

`x-scheme-handler/postman=postman.desktop`

**Comment by chrisdeso** [comment]
@SamvelRaja 
> @chrisdeso
> Could you send the Postman.desktop file you have?

Here's the information I received:

[Desktop Entry] 
Encoding=UTF-8 
Name=Postman 
Exec=postman 
Icon=/opt/Postman/resources/app/assets/icon.png 
Terminal=false 
Type=Application 
Categories=Development; 
EOL

**Comment by chrisdeso** [comment]
> I fixed it on Ubuntu 17.10 by adding postman protocol to `~/.local/share/applications/mimeapps.list`
> 
> `x-scheme-handler/postman=postman.desktop`

Closing as the comment above resolved the issue.

**Comment by labifrancis** [comment]
This issue persists on Ubuntu and we were able to replicate it. 

App version: '7.10.0-linux-x64'

Adding Postman protocol from the above comment didn't resolve the issue.

**Comment by cyrielle-hada** [comment]
Product Support has been able to replicate the issue. 

This is what the logs seem to indicate.

File: `/var/log/syslog` 
`gio: postman://app/collections/import/<collectionID>?referrer=_ga%3D2.180687047.1170469762.157312777-195411145.157226231#?: The specified location is not supported`

Google Chrome does not have any "postman://" handler set
```
# grep "protocol_handler" ~/.config/google-chrome/Default/Preferences
﻿"protocol_handler":{}
```

No desktop handler is set either, following returns nothing
`# xdg-mime query default application/postman`

Creating a `xdg-mime` handler manually can't be used as a workaround.
Creating a handler by copying existing *.desktop files for other apps wasn't successful.

<img width="1157" alt="Screen Shot 2019-11-18 at 16 45 31" src="https://user-images.githubusercontent.com/47351631/69072206-2fc82380-0a23-11ea-9350-aa03ec4da65d.png">

**Comment by labifrancis** [comment]
Our Engineering team was able to find a workaround for using the _Run In Postman_ on Ubuntu. For _Run In Postman_ to work, the `.desktop` file must be present. This file is not automatically created when you do a fresh install of the app. You'll need to follow the instructions in the guide below to create the file:

https://learning.getpostman.com/docs/postman/launching-postman/installation-and-updates/#installing-postman-on-linux 


New users are not aware of this when they do a fresh install, and so to bridge this gap we have created the GitHub issue below to further instruct users on what next to do after a fresh installation:

  https://github.com/postmanlabs/postman-docs/issues/1960

Also, since the snap variant comes with a _.desktop file_, the issue is not seen on them

**Comment by chrisdeso** [comment]
Thanks for updating this @labifrancis – closing this out.

**Comment by theoden-dd** [comment]
It does not work at least with **snap**. Tested today on **Ubuntu 18.04** and **20.04** with fresh installs _without signing in_.

1. The button perfectly generates postman://app/collections/import/... link.
2. _Firefox_ browser shows a window to choose a program, with Postman selected by default.
3. User presses "OK" and... nothing. Tested with Postman launched before and without one. The same result.

Bonus: _chromium_ isn't aware of "postman://" URL scheme. It *searches* that link in a default search engine. Tested both, in double quotes and without.

I can provide the import link in pm, but see no reason: it perfectly worked with a MacOS Postman.

**Comment by sanchezcarlosjr** [comment]
**For Ubuntu 18.04 or 20.4 users.** 
When a browser sends a command to xdg-open fails by "?" character.
Thus, you can [test](https://documenter.getpostman.com/view/631643/JsLs/?version=latest)  this in your terminal

1. The browser sends a raw request to xdg-open
```
xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#
```
2. xdg-open command doesn't wait "?", then "'\?"
```
xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs\?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#\?
```

I don't know why this work. But it works for me.

**Comment by sanchezcarlosjr** [comment]
**Users on Ubuntu 20.4**
When a browser sends a command to xdg-open fails by "?" character.
Thus, you can [test](https://documenter.getpostman.com/view/631643/JsLs/?version=latest)  this in your terminal

1. (This happens) The browser sends a raw request to xdg-open
```
xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#
```
2. (This should happens)  xdg-open command expects escape character with "?". 
```
xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs\?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#\?
```

I don't know why this works. But it works for me.

**Comment by rcnascimento** [comment]
> **For Ubuntu 18.04 or 20.4 users.**
> When a browser sends a command to xdg-open fails by "?" character.
> Thus, you can [test](https://documenter.getpostman.com/view/631643/JsLs/?version=latest) this in your terminal
> 
> 1. (This happens) The browser sends a raw request to xdg-open
> 
> ```
> xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#
> ```
> 
> 1. (This should happens)  xdg-open command doesn't wait "?", then "'\?"
> 
> ```
> xdg-open postman://app/collections/import/631643-dac5eac9-148d-a32e-b76b-3edee9da28f7-JsLs\?referrer=https%3A%2F%2Fdocumenter.getpostman.com%2Fview%2F631643%2FJsLs%2F%3Fversion%3Dlatest&versionTag=latest#\?
> ```
> 
> I don't know why this works. But it works for me.

Same behavior here.
Escaping the URL's "?" bypass the issue.

That's the only solution for me.

Setup: **Ubuntu 18.04**. snap installed Postman

**Comment by nelson-k-808** [comment]
I ran these commands after creating postman.desktop file and it worked

`xdg-mime default Postman.desktop x-scheme-handler/postman`
`xdg-settings check default-url-scheme-handler postman Postman.desktop`

**Comment by GrantDaly** [comment]
The key for me was adding the "%U" parameter placeholder in the .desktop file exec field. Allows URL's to be passed.

https://blog.postman.com/run-in-postman-is-now-available-for-linux/

**Comment by antonio-petricca** [comment]
I have the same issue for this scenario:

- Linux Mint 19.3 (Ubuntu 18.04)
- Latest postman installed by SNAP

I tried all the above workarounds but Postman does not fire up after authorizing it by the browser.

**Comment by pwaterz** [comment]
I believe the issue in Ubuntu when installed via a snap is that apparmour is blocking it
```
Jan 21 10:16:30 xps15 audit[628525]: AVC apparmor="DENIED" operation="open" profile="snap.postman.postman" name="/proc/628525/setgroups" pid=628525 comm="_Postman" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
```
I believe the snap needs to include an apparmor configuration file. I just disable apparmor.

**Comment by pwaterz** [comment]
Update I reinstalled not using snap store and apparmor no longer block the xdg link.
