### ISSUE TITLE
OAuth2 (with self signed certificates) no longer works since 6.7.2

### ISSUE THREAD

**Issue by jeff-goddard** [a85/POSTMan-Chrome-Extension#5819]
**Describe the bug**
After upgrading to 6.7.2 OAuth no longer works with self signed certificates

**To Reproduce**
* Set up OAuth 2.0 using a self signed certificate for a request (We are using the Authentication Code flow)
* Ensure that SSL certificate validation is disabled
* Click on Request Token

See this error: 

Could not complete OAuth 2.0 login. 
Check Postman Console for more details.

Postman console contains the error:

unable to verify the first certificate

**Expected behavior**
The login token shoudl be retrieved as in older versions of postman

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.2
 - OS: macOS High Sierra 10.13.6

**Comment by DanielPetatCes** [comment]
Same problem here.
I can send "normal" requests to the server, but OAuth 2.0 does not work anymore.

SSL certificate validation is disabled.

**Comment by msjonathan** [comment]
We have the same issue with SSL certificate validation disabled. 

When we browse to the identity server url with edge it states the certificate is valid, When we do the same test with chrome and browse to the it states that the certificate is invalid.

- Postman: 6.7.2
- OS: Windows:  17134.523

**Comment by lawrencek76** [comment]
Same issue here after upgrade to 6.7.2.
Reinstalling 6.7.1 the issue goes away.

**Comment by numaanashraf** [comment]
Related to #2918

**Comment by numaanashraf** [comment]
@jedigo @DanielPetatCes @msjonathan @lawrencek76 Thanks for reporting this. We fixed an issue in how SSL certificates were validated in Postman in 6.7.2 and this seems to have had a side-effect in the OAuth2.0 flow. This was not caught in our testing as self-signed certs is not officially supported in the OAuth2.0 flow (the SSL cert verification setting only affects normal request sending flow via tabs or runner and not OAuth2.0 flow - https://github.com/postmanlabs/postman-app-support/issues/2918#issuecomment-292528159). We are looking into how we can support self-signed certs or extend the SSL verification setting to the OAuth2 flow. Thanks for your patience.

**Comment by JC5** [comment]
FYI, I am also experiencing this issue with certificates issued under a internal CA. A root CA that's not found elsewhere.

**Comment by thomas-lucas1985** [comment]
FYI, we are also experiencing this issue with certificates issued by Let's Encrypt.

**Comment by ElijahKuranets** [comment]
The answer is to ADD SELF-SIGNED SSL certificate to POSTMAN. 
1.Open Git Bash and add next: 
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privatekey.key -out certificate.crt 
2.Then fill all text in console that are required.
3.Close Git Bash.
4.Next find your certificate.crt. (my was in C:\Users\User)
5.Open Postman -> Settings -> Certificates -> Add Certificate.
I added only host and crt file. Then all requests and token generator start working.

**Comment by numaanashraf** [comment]
@ElijahKuranets That's odd. Settings > Certificates > Add Certificate is for configuring client certificates. They would ideally not impact verification of self-signed server certificates.

**Comment by arashberlin** [comment]
I have the same problem with SSL certificate validation disabled.

I also tried and added the certificate in Settings > Certificates > Add Certificate 
With host, CRT & Key and host and CRT and also only host

RESULT: 
Error: unable to verify the first certificate

Can't use Postman anymore.



CERT is installed in cert store local computer (My and trusted cert auth)

With chrome and firefox there is now Cert warnings.  This issue start after upgrading to Postman v6.7.2 


OS: Win10 64 latest version


This only happens when I use the oAuth 2.0 methode to get an AccessToken

![image](https://user-images.githubusercontent.com/12381397/51844557-d23cdc00-2315-11e9-9128-b33cc662f7bf.png)

**Comment by DanielPetatCes** [comment]
In my case, Google Chrome accepts the certificate, because it is signed by our companies CA. This root CA is installed on all computers per group policy.
I am not sure, why Postman says, it is invalid?  But this may be another problem.

**Comment by JP-from-Postman** [comment]
[From related Support request]

_...upon further research it appears that this problem is limited to OAuth token requests._

_...I determined that if I use a (non-integrated) collection request I defined for OAuth testing to obtain the token it succeeds, and I can then use the returned bearer token to perform other OAuth requests._

**Comment by mancave** [comment]
Any progress on this issue? its blocking our developments. If not how can we restore a previous version of postman

**Comment by DanielPetatCes** [comment]
@mancave you can download the previous version from here:  https://www.getpostman.com/downloads/release-notes
There is a download link next to each version.

**Comment by CraigEaston** [comment]
> @mancave you can download the previous version from here: https://www.getpostman.com/downloads/release-notes
> There is a download link next to each version.

I tried that and it worked for a little while..

Problem is, even with "Automatic Updates" disabled as soon as you restart PostMan.. it gets upgraded to 6.7.2 and you are in the same boat.

**Comment by mshindal** [comment]
I've been using the Chrome app in the meantime: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop//%40

**Comment by CraigEaston** [comment]
> > @mancave you can download the previous version from here: https://www.getpostman.com/downloads/release-notes
> > There is a download link next to each version.
> 
> I tried that and it worked for a little while..
> 
> Problem is, even with "Automatic Updates" disabled as soon as you restart PostMan.. it gets upgraded to 6.7.2 and you are in the same boat.

OK, found a workaround for this...
Install 6.7.1
Find the postman.exe in that folder and create a shortcut directly to that.
The shortcut that the install created points to the "updates.exe" or something, that runs the updates.  But if you make your own short cut that points directly to 6.7.1 it won't auto-update on you

**Comment by JC5** [comment]
Unfortunately there is no link to 6.7.1 for the Mac.

**Comment by DanielPetatCes** [comment]
> Unfortunately there is no link to 6.7.1 for the Mac.

There is no link, but the file still seems to remain on the server, so you can take an existing link and just need to modify the version number.
https://dl.pstmn.io/download/version/6.7.1/osx64

**Comment by JC5** [comment]
Thanks for the pointer!

**Comment by JohnAdebiyi** [comment]
When trying to get a new Access Token in version 6.7.2 and 6.7.3,  I get the following error message:

"Could not complete OAuth 2.0 login.
Check Postman Console for more details."

Postman Console:
Error: self signed certificate in certificate chain

Every version before 6.7.2 works perfectly.

**Comment by PilotBob** [comment]
This issue is affecting us too. But, I can't seem to d/l 6.7.1 from the page referenced. Is there a direct link to d/l 6.7.1?

**Comment by mshindal** [comment]
@PilotBob 

https://dl.pstmn.io/download/version/6.7.1/windows64
https://dl.pstmn.io/download/version/6.7.1/osx64
https://dl.pstmn.io/download/version/6.7.1/linux64

**Comment by arashberlin** [comment]
Yes with version 6.7.1 I can now get the Access Token :)

**Comment by psimoneau22** [comment]
we are having the same issue. 

Opening Fiddler, I can see the request being logged to connect/authorize (Auth URL) with the 302 redirect to our application server sign in path (Callback URL) with a valid access-code.  

This was not an issue immediately before upgrading postman

**Comment by Hrafnkellos** [comment]
Same issue, using version 6.7.1. works

**Comment by edouardhue** [comment]
Same issue here with Postman for Linux Version 6.7.3 on linux 4.20.6-arch1-1-ARCH / x64. Grabbing OAuth 2.0 tokens through Authorization feature stopped working after the upgrade, while the same requests issued through classical Requests still work. SSL certificate verification is off in Postman settings, and was already off before.
My API uses certificates signed by an internal enterprise authority. Root CA certificates are installed system-wide (in /etc/ssl/certs).

**Comment by proshin-roman** [comment]
Version 6.7.1 works perfectly But! As soon as I start 6.7.1 on my Mac, it downloads an update (6.7.3) and installs it - a vicious cycle. Could anybody fix that issue? Can I somehow disable update at all?

**Comment by iamsuneeth** [comment]
Is it possible to get the update server URL, so it can be disabled from the proxy server to prevent auto updates ??

**Comment by arashberlin** [comment]
Yeah the idea with the blocking is good. 
Need to sniff the network traffic. 

I always need to install the 6.7.1 to use the tool to get accessToken. Really fun 😂😂😂

**Comment by numaanashraf** [comment]
UPDATE: This issue is addressed in our upcoming version (Postman v6.7.4) that would be available in the coming week.

**Comment by arashberlin** [comment]
Thanks with v6.7.4 issue is fixed. I can get my localhost AccessTokens 👍

**Comment by numaanashraf** [comment]
UPDATE: Postman v6.7.4, which includes a fix for this, is rolling out at the moment. Please update if you are impacted by this issue.

**Comment by numaanashraf** [comment]
@arashberlin Glad to hear that. :)

**Comment by fc7** [comment]
I just installed 7.0.3 and the bug is no longer there. I guess this ticket can be closed. Thanks!

**Comment by zinov** [comment]
I just updated to the version 7.0.7 and still having this issue

**Comment by curiouscod3** [comment]
still having this issue in 7.0.9

**Comment by numaanashraf** [comment]
@curiouscod3 @zinov Could you elaborate more on the issue you are facing? Self-signed certificates need to be added explicitly under `Settings > Certificates > CA Certificates`. Or alternatively you can disable SSL verification under `Settings > General` if you are working with self-signed certificates.

**Comment by aspoehrer** [comment]
You gave both examples for adding Self Signed Certificates. Are you saying you add Self Signed under CA Certificates?

**Comment by jafar-mirzaei** [comment]
still having this issue in 7.2.2 ( OAuth2.0 withe page)!!!
![image](https://user-images.githubusercontent.com/32808675/61293774-ae008900-a7e9-11e9-991b-857b0463ac9b.png)

**Comment by neilpalima** [comment]
@numaanashraf  I am experiencing this issue. A subdomain is using a wild card ssl from namecheap. Why do I need to disable SSL certificate validation in order to access the subdomain? The subdomain can be accessed smoothly on chrome though but not in postman. I am using Version 7.20.0 for Windows.

**Comment by maxhopei** [comment]
The issue is still there in v7.36.1

**Comment by m-kratochvil** [comment]
> @curiouscod3 @zinov Could you elaborate more on the issue you are facing? Self-signed certificates need to be added explicitly under `Settings > Certificates > CA Certificates`. Or alternatively you can disable SSL verification under `Settings > General` if you are working with self-signed certificates.

On the current version 7.36.1 the error `Warning: Unable to verify the first certificate` is still there even with SSL verification under `Settings > General` disabled.

**Comment by dotcom9** [comment]
Still getting this issue with Bearer token, self-signed certificate (for IIS Express) in v8.0.7
