### ISSUE TITLE
Local collections disappeared after sign-in with team account

### ISSUE THREAD

**Issue by zaro** [a85/POSTMan-Chrome-Extension#6323]
**Describe the bug**
Had postman installation w/o begin signed in. Joined a team , and my workspace is empty now , Signed out, still empty. Old collections are completely gone.

**To Reproduce**
1. Start Postman w/o sign in
2. Create some collections
3. Sign-in with team account
4. Signed in or out, the collections before the team signin are nowhere to be found.

**Expected behavior**
I expect, that my local data wouldn't disappear because I signed in with team account.

**Screenshots**
-

**App information (please complete the following information):**
 - Native App, installed from flathub
 - Version 7.0.6
 - Fedora 29

**Additional context**
.

**Comment by preethammavin** [comment]
@zaro can you check the https://go.postman.co/me/collections. It takes few seconds to sync the collections which were created before signing in to sync the collections in. We are creating an experience where we warn the users if they try to sign-out before the collections are synced. 

I would suggest that if you do not find any collections after you signin in, please DO NOT signout as that would erase the data. Wait for few seconds and you shall see them sync in, can be seen in the above mentioned link/going to the browse mode in the application.

**Comment by zaro** [comment]
> I would suggest that if you do not find any collections after you signin in, please DO NOT signout as that would erase the data. Wait for few seconds and you shall see them sync in, can be seen in the above mentioned link/going to the browse mode in the application.

This is good suggestion but a bit too late.  Of course I did signup out after clicking around and not finding them, to see if I will get my local collections back. What would you expect ?

Also I don't understand also, why would they disappear while being synced, and then magically re-appear when sync is complete.

**Comment by numaanashraf** [comment]
@zaro Could you write to us at help@getpostman.com? We'll do our best to recover any data from your device. 

> Also I don't understand also, why would they disappear while being synced, and then magically re-appear when sync is complete.

We have identified a performance issue in Postman whether the UI doesn't show all your data immediately after account creation/sign-in. This has been resolved in Postman v7.0.9.

**Comment by zaro** [comment]
I don't need old data that much, it was mostly about reporting the issue.

**Comment by haayman-imagem** [comment]
This just happened to me too. Great

**Comment by kartikjuneja** [comment]
Issue still not solved. I lost all important data created in days. Never know such a great feature of Postman. Not shown up since half the day and not even I logged out. Salute to Postman.

**Comment by octocat-mona** [comment]
> I would suggest that if you do not find any collections after you signin in, please DO NOT signout as that would erase the data. Wait for few seconds and you shall see them sync in, can be seen in the above mentioned link/going to the browse mode in the application.

@preethammavin Had quite some collections stored but got so annoyed by the banner that says that you need to sign in that I finally did that.
But after signing in all my collections are gone, and they are not coming back even after the sync completed.

![image](https://user-images.githubusercontent.com/538170/122578915-a3457300-d054-11eb-9a2e-9caa74e2d9f3.png)

Luckily enough I was able to restore a recent [backup](https://support.postman.com/hc/en-us/articles/360035071313-How-to-recover-my-data-) recovering some of my data, but it is still frustrating that this issue has not been fixed yet.

**Comment by temaput** [comment]
+1
Lost everything

**Comment by myahl-uncomn** [comment]
I had the same situation, but I found my stuff in the scratchpad, per the solution here https://community.postman.com/t/lost-all-collections-when-i-created-an-account/5138/21
I hope it helps someone.

**Comment by ray-moncada** [comment]
> I had the same situation, but I found my stuff in the scratchpad, per the solution here https://community.postman.com/t/lost-all-collections-when-i-created-an-account/5138/21 I hope it helps someone.

Pasted the solution from the link here for convenience. 

I did exactly what [@haayman](https://community.postman.com/u/haayman) did and was also able to recover my data. In summary, this was the cause of the problem:

I had an existing instance of Postman without a logged in account and existing collections.
I created a Postman account via clicking a prompt in the Postman UI
Upon creating the new account, I picked the setting to have postman store the new workspace it was creating locally and not backup to the cloud (big no-no without prior approval by our security team)
The previously existing collections were not there and the settings were restored to default.
To restore:

Create a new workspace (if not already) and click the “Import” button (near the upper left, by My Workspace)
Look in \AppData\Roaming\Postman, find the latest file named backup-<ISO Datetime>.json
If you are on Mac or Linux the path to the dir with the backup files is ~/Library/Application Support/Postman or ~/.config/Postman/ (see [this link 47](https://support.postman.com/hc/en-us/articles/360035071313-How-to-recover-my-data-))
Tada. This restored the collections but it does not restore the settings. For my case this was only dark mode :wink: but if you have a richer set of custom settings I’m not sure if those are also backed up anywhere?

**Comment by jmaslibre-pp** [comment]
> I had the same situation, but I found my stuff in the scratchpad, per the solution here https://community.postman.com/t/lost-all-collections-when-i-created-an-account/5138/21 I hope it helps someone.

From the link:
> I wasn’t logged in as anyone on my previous version of Postman and the new version defaults to asking for login. I was able > to retrieve my collections by going to the gears icon (Settings) and selecting “Scratch Pad”. Hope that helps.

Thanks Pham and @myahl-uncomn

**Comment by jkbrookes2** [comment]
I switched over to a new computer and didn't sign into Postman right away.  I was doing some work and realized I needed some features and needed to sign in and, bam, lost all my work.  I've been following the different instructions in this thread, but it has been an absolute mess.

**Comment by preethammavin** [comment]
@jkbrookes2 ,since you signed in to the app, your data which was created before sign-in should be in scratchpad will still be available in the scratchpad. You can go to the scratchpad from the setting section at the top right section of the app 

<img width="1512" alt="Screenshot 2023-01-28 at 12 34 35 PM" src="https://user-images.githubusercontent.com/34742239/215252237-1e85505e-2cae-4c5b-9e82-68d1bdc244e2.png">
