### ISSUE TITLE
Request goes in conflicted state when editing request name/description

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#6383]
**Describe the bug**
Request goes in conflicted state when editing the name, even when no one else is working on it.

**To Reproduce**
1. Create a new request
2. Send a request to getpostman.com
3. Add tests
4. Save request
5. Send request
6. Edit request name
7. Save
8. Observe conflicted state 👀

**Expected behavior**
To not be conflicted

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0.9
 - OS: macOS Mojave

**Comment by VicKetchup** [comment]
For https://github.com/postmanlabs/postman-app-support/issues/6848 the conflict state happens without any edits, nobody has touched those requests we have issues with for a very long time (over a year).

**Comment by sujayvenaik** [comment]
Hey @ankit-m @VicKetchup 
We have addressed this in the latest version (v7.3.6).
Closing this issue, feel free to reply on the thread if you face it again.

**Comment by jyadavd2** [comment]
I still get this issue! On version: Version 10.13.0
Random opened tab goes to conflict state and the HTTP URL automatically changes to some other request URL out of blue! It's a very strange behaviour!

**Comment by giridharvc7** [comment]
@jyadavd2 Does this happen in a team workspace?

**Comment by jyadavd2** [comment]
> @jyadavd2 Does this happen in a team workspace?

No, I'm not using Teams workspace. To give example, I have a collection of requests organized in multiple folders, so in case I have multiple tabs opened for long, I noticed that some random old tab shows [CONFLICT] and the URL changes to some to other request URL (no relation as such, could be from any folder/request in my collection)

![image](https://github.com/postmanlabs/postman-app-support/assets/107102949/73dfe420-663e-4116-a23a-f24759fa5f58)


Here you can see that, this GET request from my collection showed me CONFLICT. It automatically, don't know how, took the Request (HTTP METHOD and URL both) from other request in the collection. Don't know how!! And this happens with me very frequently, for may be around a year, ever since I noticed this.

**Comment by cj-scott-prive** [comment]
This still happens on `Version 10.13.6 (10.13.6)`, and macOS `13.4 (22F66)`
I  am definitely _not_ editing any tabs. I do not (and can not) use Workspaces. 

Whenever there's a new build that _might_ have fixed an Issue, the issue is promptly closed.
This is done without even trying to get the reporter to validate the fix, first..
 
There's _so many duplicates_ of this problem (all closed), and unresolved reports in the forum.
