### ISSUE TITLE
Collections transferred to a different user are still referenced by workspaces

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#6520]
**Describe the bug**
When a collection gets transferred from one user to a different user the old collection id is still referenced in all the existing workspaces. This causes the app to try syncing these deleted collections and fail.

**Comment by preethammavin** [comment]
@kamalaknn does it happen post RBAC as well?

**Comment by kamalaknn** [comment]
@ankitjaggi can give more context.

**Comment by cyrielle-hada** [comment]
@kamalaknn any idea how to unblock @garrucho? Looks like the problem was addressed with RBAC but the app is still trying to sync the collection. Let us know if you need anything else to debug this issue.

**Comment by DannyDainton** [comment]
Hey @kamalaknn, Is this something that we can close out now?

**Comment by garrucho** [comment]
Just for the record, it was never solved:

![image](https://user-images.githubusercontent.com/7749043/86022167-5e1dd080-ba00-11ea-8f22-acefaf491f7c.png)

For every new Postman window, I change to another workspace (since I can't change the default, which doesn't work). But the problem itself was solved moving my collections, envs, and ignoring the old history to use a new workspace.

**Comment by DannyDainton** [comment]
Hey folks,

Is anyone still experiencing this issue in the latest version of the app?

**Comment by cyrielle-hada** [comment]
@DannyDainton we never received any other reports of this issue. However, it looks like we never managed to solve it retroactively

**Comment by DannyDainton** [comment]
Closing this issue - Can reopen if needed.
