### ISSUE TITLE
Unable to Copy response text

### ISSUE THREAD

**Issue by DOLPHYNNNN** [a85/POSTMan-Chrome-Extension#6876]
In version v7.3.1 I am unable to copy any of the body response text to the clipboard.  I can copy the input data, but not the response body data.  
This is on Windows 10.  
When selecting body text you can right click and hit copy and it nothing goes wrong, but if you try and paste you notice that nothing actually got copied to the clipboard.  

To recreate, post to an endpoint in a collection.  Choose the body tab to see the response.  Select some of that body text and right click and hit copy.  Go to an editor and hit paste.  Notice that the text you copied is not pasted and what is pasted is whatever was previously in the clipboard.  

Expected Behavior = When you copy body text it gets copied into the clipboard, as it did previously.

**Comment by kamalaknn** [comment]
@DOLPHYNNNN 

Thanks for reporting this. We were able to reproduce this.

We did some improvements in the response body viewer, that has caused this. We will push a fix for this in the next release.

In the meantime, the `ctrl/cmd + C` shortcut should work for copying the selection. There is also a `Copy Response` icon on the top right of the response section.

We'll keep the thread updated.

**Comment by bastiewendt** [comment]
Hi there,
the issue still persists in Postman v7.3.4
Thanks for the hint to use the keyboard instead of mouse, works fine ;-)

**Comment by ankurdengla** [comment]
Hey! @DOLPHYNNNN @bastiewendt The fix for this issue is out on our Canary channel - [PostmanCanary 7.3.5-canary01](https://www.getpostman.com/downloads/canary).

**Comment by timatanu** [comment]
So I'm using canary04 and yes the click to select issue is fixed but it seems to have broken the double-click select. So I used to be able to put the cursor to the right of the second [ and double click and it selected all the JSON up to the ] for example \<![CDATA[**{"Event":{"EventHeader":{"TimestampExtracted":"2019-08-01 03:12:46.377"}}**]]\>

**Comment by ankurdengla** [comment]
Hey @timatanu ! Thanks for confirming the fix for the select and copy issue and for bringing the new case to our notice. Since that is a different issue than the one being discussed in this thread, I've created a new GitHub issue for the same.
You can track updates for it in this issue - https://github.com/postmanlabs/postman-app-support/issues/7040

**Comment by kamalaknn** [comment]
The fix for copy action in the context menu is on the stable channel from Postman 7.3.6. Please update and give it a try.

**Comment by ankurdoshi87** [comment]
The issue still occurs. 
Example if i double click on '{' then the whole inside object get selected in request body. But the same thing doesnt happen in response body.

<img width="881" alt="Screen Shot 2019-08-07 at 6 37 32 PM" src="https://user-images.githubusercontent.com/3383866/62662558-785f4380-b942-11e9-89da-13f81d2a15cf.png">

**Comment by ankurdengla** [comment]
Hey @ankurdoshi87 ! Thanks for reaching out. We are tracking the issue of response text inside brackets not getting selected here - https://github.com/postmanlabs/postman-app-support/issues/7040. Please follow that thread for updates regarding the same.
