### ISSUE TITLE
Postman header encoding breaks when adding a body

### ISSUE THREAD

**Issue by DeoMortis** [a85/POSTMan-Chrome-Extension#7094]
**Describe the bug**
Whenever you send utf-8 characters in request header without a request body then the data is transmitted fine. If only a body is added (no matter what type) then encoding of headers changes and they are unreadable for server.

**To Reproduce**

A simple test can be done against mockbin.org server. I also looked at the wireshark logs which confirm the behavior.

1. Create a POST request against `https://mockbin.org/request`
with a header like `X-Encoding-Test:öäü`
don't add the body yet to see correct behavior
2. Click on 'Send'
3. Look at the results.
Expecially the headers object ` "x-encoding-test": "öäü",` which is fine.
4. Add a body to the request. Any type. size > 0.
5. Click send
6. Observe results
`"x-encoding-test": "Ã¶Ã¤Ã¼" `

Wireshark logged header:
without body:
`x-encoding-test: \366\344\374\r\n`
with body:
`x-encoding-test: \303\266\303\244\303\274\r\n`

**Expected behavior**
The encoding should be the same for no body and body requests. Preferably the one readable (as currently without the body)

**Screenshots**
No needed

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.3.6 
 - OS: Windows 10 also confirmed on Linux Mint 19.1

**Additional context**
Testing identical requests using any other tool like curl shows consistent behavior (encoding is fine).

**Comment by codenirvana** [comment]
@DeoMortis Thanks for reporting this issue. For me, it's encoding correctly with the body (weird 🤔).

This looks like an issue with our low-level request sending library and might take a while to reproduce and get this issue fixed. Will update the progress here once it's fixed in our Canary or Production channel.

**Comment by DeoMortis** [comment]
@codenirvana Thank you. If anything is needed from me I will be more than happy to help. 
I am reproducing it constantly on my machine with Windows 10. My collegue also reproduced it himself on his Linux Mint.

**Comment by DeoMortis** [comment]
I decided to revisit this issue after a while and I confirm it still persists.
Checked on different PC with latest Postman 7.20.1 version. Windows 8.1 64-bit.

**Comment by gyana12** [comment]
i too noticed the issue.

**Comment by gyana12** [comment]
but couldn't find any solutio.
