### ISSUE TITLE
Copy and Paste  is invalid  in postman

### ISSUE THREAD

**Issue by chron-xie** [a85/POSTMan-Chrome-Extension#7100]
when create a new request in postman ,copy and paste are not available.

**To Reproduce**
1. create a new request 
2. select Body's tab or Tests's tab
3. The text box prompts the content，“Copy and paste are invalid  in Postman，but right click is Ok 。Attachment is postman's version”
4. cmd+C and cmd+V  are no effect

**Expected behavior**
Copy and paste are available.

**Screenshots**
![image](https://user-images.githubusercontent.com/9361238/62912387-84238d80-bdba-11e9-9267-c056c83e6e23.png)

**App information:**
 - App Type  Chrome App
 - Postman Version 7.3.6
 - OS: macOS High Sierra 10.13.6

**Comment by preethammavin** [comment]
@Chronchon just reiterating the problem so that I understand the issue correctly 
You are unable to copy paste texts into Body/Test script tab? If yes, it is available and the text that you see is not something the Postman shows. Can you try again on a new request? and let us know?

**Comment by chron-xie** [comment]
@preethammavin  open Postman APP, when I create the first new request, the body script Tab has the word as last Screenshots ,create another request, body script tab is blank, but cmd+C and cmd+V are also no effect

another new request screenshots:
![image](https://user-images.githubusercontent.com/9361238/62918740-31a29b00-bdd3-11e9-935a-70bacf81d4f5.png)

ps: Download other versions, the problem still exists

**Comment by preethammavin** [comment]
@Chronchon would be really helpful if you can do a screen recording with the issue as I am unable to reproduce it. 

But going through the flow I think there is an UX issue where on selection on body, we do not auto focus on the editor but if you click on it once it works.

**Comment by chron-xie** [comment]
@preethammavin  I'm sorry. App updated to 7.5.0 and then rolled back to 7.3.6. that prompt disappear, but cmd+C and cmd+V are also no effect in 7.5.0 and 7.3.6

**Comment by preethammavin** [comment]
@Chronchon any chance you can share the screen recording? if you can please share the screen recording with user logs, which you can find in view->developer -> view logs in finder and send it across to help@getpostman.com. 

This will help us debug and address the issue ASAP.

**Comment by chron-xie** [comment]
@preethammavin   logs and video have sent to help@getpostman.com.

**Comment by preethammavin** [comment]
@Chronchon I am unable to locate your ticket, would be great if you could reply with the github issue id in the ticket raised.

**Comment by chron-xie** [comment]
@preethammavin I had  replied  github issue title and id  as mail header . can't get my sent mail ?

**Comment by preethammavin** [comment]
@Chronchon I am not able to locate the mail, can you resend it or just mention this thread and my name on the email.

**Comment by chron-xie** [comment]
@preethammavin   resend it again  at 6:55 PM

**Comment by rohit-taneja** [comment]
@preethammavin 
I am having the same issue:
Mac, Postman - 7.5.0
When I copy from Postman and paste on any other window it works, but
When I copy from any window other than Postman, it is not pasting by CMD + V in Postman, to paste I have to right click and then paste

**Comment by nzulfigarov** [comment]
@preethammavin 
I'm having the same issue too.
```
Postman for Mac
Version 7.5.0
OS X 18.7.0 / x64
```

**Comment by nzulfigarov** [comment]
@preethammavin @Chronchon @rohit-taneja 
Idk why is this happening every time, but i found solution in five minutes after I posted comment...
It's all starts working after disabling (this command was added earlier to "cmd + V" shortcut)

>  "Paste and Match Style"

You can found it in your System preferences => Keyboard => Shortcuts => App Shortcuts

Also, i think this is not quite good, this should be fixed in next releases.

**Comment by kevin-postman** [comment]
@Chronchon @rohit-taneja I have tried to duplicate this issue on Linux, Windows and Mac with no success. Could you please try updating to the latest release and see if the issue is resolved?

**Comment by rohit-taneja** [comment]
@kevin-postman Updating to 7.8.0 also didn't solve the problem but as @nzulfigarov said, removing the shortcut for paste and match style from system preferences did the trick.
Thanks both of you.

**Comment by harryi3t** [comment]
@rohit-taneja @Chronchon @nzulfigarov 
We were able to reproduce the issue (thanks @nzulfigarov for the info provided). It looks like when you have `Paste and Match Style` action mapped to `Cmd + V` shortcut, it interferes with the actual `paste` action.
We are working on a fix for this. I will update the thread once the fix is out. 
Thanks for your patience!

**Comment by kevin-postman** [comment]
This issue is now resolved with 7.11.0.

**Comment by gerab** [comment]
still broken v 7.16.0 MacOs

**Comment by yhal003** [comment]
Still broken v 7.21.1 Ubuntu

**Comment by Crypto-Berto** [comment]
Postman really sucks. Copy and paste is a real nightmare. Please let the developers see to this as soon as possible.
