### ISSUE TITLE
No internet connection, 

### ISSUE THREAD

**Issue by tnkteja** [a85/POSTMan-Chrome-Extension#7130]
Though internet connection is available, the post man won't say.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by preethammavin** [comment]
@tnkteja are you working behind a firewall? can you try the same in different network and check if the issue persists?

**Comment by preethammavin** [comment]
@tnkteja closing the issue for now, feel free to reopen it with the requested information so that we can get it sorted for you.

**Comment by IeuanWalker** [comment]
Hi @preethammavin 

I'm having the same issue.
If i go to APIs i get the below screen -
![image](https://user-images.githubusercontent.com/6544051/74820316-b843b200-52f9-11ea-8b26-19567559f08d.png)

Also I'm unable to edit or create new Work spaces - 
![image](https://user-images.githubusercontent.com/6544051/74820371-cc87af00-52f9-11ea-92de-ba57ab2b447b.png)

I am behind a firewall/ proxy, I've added all the proxy info into the settings, but makes no difference.

**Comment by ankurdengla** [comment]
Hey @IeuanWalker !

The `Proxy` configuration in `Settings` only applies to the request sending flow in the app. The other features such as APIs, workspaces, login, syncing use the system-defined proxy settings by default. We currently do not have support for proxy servers that require authentication, but we're working on it. We're tracking it in this thread - https://github.com/postmanlabs/postman-app-support/issues/6053

We released authentication support for proxy servers in PostmanCanary v7.18.0-canary02 which can be downloaded from here - https://www.postman.com/downloads/canary .
Please do try it out and let us know if it solves your issue.

**Comment by IeuanWalker** [comment]
@ankurdengla ahh great thanks

**Comment by IeuanWalker** [comment]
@ankurdengla I've tried the canary version, still have the same issues :/

**Comment by ankurdengla** [comment]
Hey @IeuanWalker ! 

Could you provide the following info to help us identify the reason for your issue ?

1. What is the version of the Canary app you're using?
2. Did you see a window requesting you for your proxy credentials when you started the app?
3. Could you also send us logs at help@postman.com with the mail titled as `Logs fog Github issue #7130`. The logs can be accessed from `View → Developer → View Logs in Explorer/Finder`.

**Comment by IeuanWalker** [comment]
@ankurdengla 
1. 7.18.0-canary03
2. No
3. Done
