### ISSUE TITLE
Request timeout despite '0' timeout configuration

### ISSUE THREAD

**Issue by mbracero** [a85/POSTMan-Chrome-Extension#7221]
Postman replies with an ETIMEDOUT despite the timeout configuration is set to infinite (value = 0).

![image](https://user-images.githubusercontent.com/4550933/63915056-4e76d980-ca35-11e9-95b5-169277d0f4a1.png)

Postman stops in 20 seconds.

![image](https://user-images.githubusercontent.com/4550933/63914987-25eedf80-ca35-11e9-9071-a717a5f76eb4.png)

The request takes 40sec to reply. I have tried with both curl and another REST client and returns data.

![image](https://user-images.githubusercontent.com/4550933/63915754-1a9cb380-ca37-11e9-926f-f0bade575945.png)

**App information**
 - Postman Version: v7.5.0
 - OS: Windows 10 PRO 2018

**Comment by coditva** [comment]
Hey @mbracero, thanks for reaching out! Unfortunately I've been unable to reproduce this.

I tried sending a request to a local server I setup which sends response after 5 mins. Here's the code for the server:
```node
const express = require('express'),
    port = process.env.PORT || 3000,
    app = express();

app.use(express.json());

app.post('/timeout', (req, res) => {
    setTimeout(() => {
        res.json({ result: 'ok' }).end();
    }, 5 * 60 * 1000); // 5 mins
});

let server = app.listen(port, function (err) {
    if (err) {
        console.log(err);
    }
    console.log('Listening on', port);
});

server.setTimeout(10 * 60 * 1000); // 10 mins
```
Postman was able to get the response just like `curl`.

What kind of service are you using? Is there a chance this got timed out because of a Proxy/server?

Is there any publicly accessible endpoint I can reproduce this behaviour with?

Waiting for your reply!

**Comment by mbracero** [comment]
Hi @coditva , They're intranet endpoints, so unfortunatelly I can't shere with you.

They're simple REST API.

As I said, it's extrange becasue with another REST client app, it doesn´t happends. And even I thought that timeout was for the whole request (independently of the layers the request has to go thougth).

**Comment by coditva** [comment]
@mbracero We have updated the Postman Console to include a lot of information to help debug issues like these. Can you update to Postman v7.10.0 and try finding the cause of the timeout?

In the Console you see the re-directs and information about proxy which might help! 

Download link: https://dl.pstmn.io/download/version/7.10.0/win

**Comment by saswatds** [comment]
Closing this issue now, as we are not able to reproduce this and no other user have reported this. Feel free to re-open the issue if the issue still persists.

**Comment by Estigy** [comment]
I'm just now experiencing the very same behaviour.
I have a call to a REST API that always times out after about 20 seconds.
My time out value is set to 0, but increasing it to arbitrary numbers does not have any effect.
I'm running v 7.27.1

**Comment by Estigy** [comment]
> I'm just now experiencing the very same behaviour.
> I have a call to a REST API that always times out after about 20 seconds.
> My time out value is set to 0, but increasing it to arbitrary numbers does not have any effect.
> I'm running v 7.27.1

The problem was solved - partly: The underlying issue was on the network level. My computer with Postman was not allowed to connect to the target server.
I'm now wondering if Postman could report this back to me in a different way that could help me find the problem more easily.

**Comment by nagpureroshan** [comment]
I am now facing same issue with  Postman Version 7.28. I have tried couple of version with installations and i am stuck at same point. The API is accessible when tried through any browser but from Postman its still not accessible. Please resolve or share work around for this problem.

**Comment by arlemi** [comment]
@nagpureroshan Are you using a Proxy on your computer? If so please check this support page: https://support.getpostman.com/hc/en-us/articles/360008893713-How-do-I-configure-Postman-to-work-through-a-proxy-

**Comment by appurist** [comment]
I just ran into the same issue with Postman 8.6.2. I'm not using any obvious proxy (but I'm testing against a Netlify local dev server). While debugging my endpoint, which was being hit successfully, Postman would time out even with a 0 in the settings. (I don't think I ever set that though, it was just already set to 0.)

It was always a 10-second timeout, so I just changed the setting to 60000 ms just to see if that extended it. It did. So it's all working without an earlier timeout if I just give it a larger value. It is as if the 0 is not the actual value, but the UI is showing 0 if it's not yet set. Probably now that I've changed it to 60000, if I set it back to 0 it will probably not timeout at all anymore.  Oh, that's a quick test so... and yes, confirmed. Set back to 0, after setting it to 60000, and it is not timing out after 10 seconds anymore.

I strongly suspect it's not reproducible because the bug is only present when the timeout _has never been set_, and it's already been set to something in the installations being tested.

For others reading this, there appears to be a workaround of setting it to something other than zero, then setting it to zero.

**Comment by boylec** [comment]
> I just ran into the same issue with Postman 8.6.2. I'm not using any obvious proxy (but I'm testing against a Netlify local dev server). While debugging my endpoint, which was being hit successfully, Postman would time out even with a 0 in the settings. (I don't think I ever set that though, it was just already set to 0.)
> 
> It was always a 10-second timeout, so I just changed the setting to 60000 ms just to see if that extended it. It did. So it's all working without an earlier timeout if I just give it a larger value. It is as if the 0 is not the actual value, but the UI is showing 0 if it's not yet set. Probably now that I've changed it to 60000, if I set it back to 0 it will probably not timeout at all anymore. Oh, that's a quick test so... and yes, confirmed. Set back to 0, after setting it to 60000, and it is not timing out after 10 seconds anymore.
> 
> I strongly suspect it's not reproducible because the bug is only present when the timeout _has never been set_, and it's already been set to something in the installations being tested.
> 
> For others reading this, there appears to be a workaround of setting it to something other than zero, then setting it to zero.

I think you're on to something here but this didn't solve it for me unfortunately. My experience:

Request is a non proxied totally regular POST to an external server.
1. Timeout setting set to 0 in Postman. Request times out after 76 seconds consistently.
2. Set timeout setting to 10000 in Postman. Request now times out after 10 seconds consistently.
3. Set timeout setting back to 0 in Postman. Request now times out after 76 seconds consistently.

Seems more than likely that there is something along the request path causing this besides Postman but I'm unable to prove that and as far as I know there is nothing of the sort.

:|

**Comment by arlemi** [comment]
@boylec Is the server timing out, or is Postman timing out? In the first case you'll still get a response with an error, in the second one you should be getting this error: 
![image](https://user-images.githubusercontent.com/5029719/130434075-9dab4055-32f9-41b9-b7ac-d8b627fc73cf.png)

@appurist Thank you for the details, we'll see if we can replicate it on our end. cc @saswatds

**Comment by boylec** [comment]
@arlemi Thanks for the response.

Turns out this is a case where I was using the wrong URL. (wrong subdomain to be precise)

Curious that this causes a "Request timed out" rather than a "DNS record not found" or some such.

Either way though this turned out to not be an issue with the request timeout setting for me.

**Comment by dt-prime** [comment]
This the error message I’m getting. The response didn’t time out, the sending of the request itself timed out.

![image](https://user-images.githubusercontent.com/36053409/134417280-7b7494d1-1dba-4cbf-a794-3364e4a700b1.png)

#### Text Format
Could not send request
Error: Request timed out

**Comment by arlemi** [comment]
@dennis-thomas-o Can you open the Console and let us know what's in there?

**Comment by MitchellGrelson** [comment]
@arlemi I have the same issue as above, here's a screenshot of the console:
![image](https://user-images.githubusercontent.com/83843674/159765185-6834b1d2-9fc9-4d5c-9e80-6cc6fa6b22c5.png)

**Comment by bpleon** [comment]
Is this happening again?
I'm on v9.24.2 and the request is taking a min or so (of a 1.5 min request) and am getting the `Error: connect ETIMEDOUT`

Follow-up: The request was firewalled, so the TCP connection was never established, which is what was timing out. Which is why I get the connection timeout error, and not some other request data timeout error.

**Comment by alexa2me** [comment]
I'm running into the same problem 😞.

If I send something wrong in the body of the request, the warning message comes correctly, but if the body is correct, request always return `ETIMEDOUT`:

<img width="557" alt="Captura de Tela 2022-08-14 às 15 54 08" src="https://user-images.githubusercontent.com/63327969/184551063-41aace9c-6b23-4f66-8649-2f797229df3e.png">

- Return when body is wrong (purposely):

<img width="469" alt="Captura de Tela 2022-08-14 às 16 00 48" src="https://user-images.githubusercontent.com/63327969/184551139-b0393809-cabc-439c-8553-02560161e145.png">

**Comment by arlemi** [comment]
@alexa2me Is it possible that the server times out and not Postman? If you're still seeing the issue please open a new issue so we can look into it.
