### ISSUE TITLE
Dynamic variables in the request body returning 400 bad request when running the collection through Newman

### ISSUE THREAD

**Issue by ponu25** [a85/POSTMan-Chrome-Extension#7671]
Dynamic variables like {{$randomPassword}} is working fine when I run the collection from Postman application. But, when I export the same collection as json and running it in jenkins with newman command, it returns 400 bad request. Please help.

**Comment by codenirvana** [comment]
@ponu25 Looks like you are using an older version of Newman.
Try updating the Newman dependency to the latest and try again.

**Comment by crumpledpineapple** [comment]
I can confirm that this issue is still happening on newman 4.6.0 when running colelctions from jenkins.

**Comment by crumpledpineapple** [comment]
I can confirm that this issue is still happening on newman 4.6.0 when running colelctions from jenkins.

**Comment by codenirvana** [comment]
@crumpledpineapple Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by crumpledpineapple** [comment]
@codenirvana I have attached a scaled down collection. 
[scaled_down_collection.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/4265981/scaled_down_collection.postman_collection.json.txt)

**Comment by codenirvana** [comment]
@crumpledpineapple I am not able to reproduce this issue with the attached collection.

<img width="1440" alt="Screenshot 2020-02-28 at 2 10 44 PM" src="https://user-images.githubusercontent.com/4865836/75525064-27758080-5a35-11ea-9948-5ea65798ac2e.png">

As you can see in the attached screenshot, the dynamic variable `$randomBankAccountIban` is resolved correctly.

**Comment by crumpledpineapple** [comment]
@codenirvana I only have the issue when running newman from jenklns... 
![scaledDown_cleaned](https://user-images.githubusercontent.com/61550303/75537137-c474f100-5a16-11ea-81fc-b79e8be4506f.png)

**Comment by codenirvana** [comment]
@crumpledpineapple That's because you are not using the latest version of Newman on Jenkins.
You are probably using the `v4.5.0` as I can infer from the user-agent header.

I hope updating the Newman version on Jenkins fixes your issue.

**Comment by crumpledpineapple** [comment]
@crumpledpineapple Still happening on jenkins with newman 4.6.0
