### ISSUE TITLE
Missing collections when using PostmanCanary-linux-x64-8.0.0-canary01

### ISSUE THREAD

**Issue by idkw** [a85/POSTMan-Chrome-Extension#9416]
**Describe the Issue**

When opening PostmanCanary-linux-x64-8.0.0-canary01 some of my collections are missing, only a few of them are displayed

**Steps to Reproduce**

Open PostmanCanary-linux-x64-8.0.0-canary01 and look at the list of connections. Only 7 of them are displayed.
If i switch workspace and switch back to the original workspace, all the collections are now displayed correctly.
So this seems to be a UI bug rather than a data corruption bug. Still very annoying.

**Environment Information**

 - Platform Type: Linux
 - Postman Version: 8.0.0-canary01
 - Operating System: Linux Mint  20

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

Just happened after upgrading from PostmanCanary 7.x to 8.0.0

**Comment by numaanashraf** [comment]
@idkw Thanks for reporting this. This has been resolved internally and the fix will be available in today's canary release.

**Comment by idkw** [comment]
@numaanashraf As there are other blocking errors that prevent me to work on the 8.0.0 version, I'd like to download the latest canary version on the 7.x branch, where can I find that ? Thanks

**Comment by numaanashraf** [comment]
@idkw Could you share more details on which errors are blocking you from working on v8.0.0 canary?

**Comment by idkw** [comment]
@numaanashraf this is very random and happens rather a lot so of various different screens
For example when editing authorization on a colleciton, instead of showing the page, postman display an error screen which says to send a mail to the support. I'm not sure how to give you more information than that because I can't share the affected collection publicly.

For now, because there are too much bugs that prevents me from working with my usual collections, I'm sorry to say I had to download the normal build of Postman on the 7.x branch which doesn't suffer from theses issues.

**Comment by alxtr1bal** [comment]
> 
> 
> @idkw Thanks for reporting this. This has been resolved internally and the fix will be available in today's canary release.

Issue is still there on latest canary (v8.0.0-canary03) : Message "Couldn't load collections".
Windows 10  (Insider build 21286)

**Comment by jibiabraham** [comment]
@alxtr1bal could you post more information on the issue you are facing? Specifically, 

1. Is the collection visible on your sidebar, but this message shows up when you attempt to open it
2. If so, could you post the ids of the workspace, and the affected collections?

**Comment by alxtr1bal** [comment]
@jibiabraham , i can't see any collections at all.

<img width="602" alt="Postman_Coll" src="https://user-images.githubusercontent.com/10094922/104704660-33cffe00-5719-11eb-9d0c-4a39f5629d38.png">

**Comment by alxtr1bal** [comment]
@jibiabraham , i think this log extract is related :  

```
[21092][1610701492162][requester][warn]["ListingAPIAdapter~hydrate: Failed to hydrate collections",{"name":"TypeError","message":"Cannot read property 'forEach' of null","stack":"TypeError: Cannot read property 'forEach' of null\n    at CollectionSidebarModel.updateFoldersFromOrder (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:244890:24)\n    at executeAction$$1 (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21956:19)\n    at CollectionSidebarModel.res (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21948:16)\n    at file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245022:12\n    at arrayEach (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:1037:11)\n    at Function.forEach (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:9863:14)\n    at CollectionSidebarModel.updateCollectionTree (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245017:7)\n    at executeAction$$1 (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21956:19)\n    at CollectionSidebarModel.res (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21948:16)\n    at CollectionSidebarModel.hydrate (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245136:10)\n    at Object.hydrate (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:244738:15)\n    at file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/sidebar/CollectionSidebarController.js:253:40"}]
[21092][1610701492171][requester][error]["CollectionSidebarController~fetchCollections: Error in loading collection list",{"name":"TypeError","message":"Cannot read property 'forEach' of null","stack":"TypeError: Cannot read property 'forEach' of null\n    at CollectionSidebarModel.updateFoldersFromOrder (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:244890:24)\n    at executeAction$$1 (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21956:19)\n    at CollectionSidebarModel.res (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21948:16)\n    at file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245022:12\n    at arrayEach (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:1037:11)\n    at Function.forEach (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:9863:14)\n    at CollectionSidebarModel.updateCollectionTree (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245017:7)\n    at executeAction$$1 (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21956:19)\n    at CollectionSidebarModel.res (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/vendor-shared.js:21948:16)\n    at CollectionSidebarModel.hydrate (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:245136:10)\n    at Object.hydrate (file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/CommonLazyChunk.js:244738:15)\n    at file:///C:/Users/alxtr/AppData/Local/PostmanCanary/app-8.0.0-canary06/resources/app.asar/js/sidebar/CollectionSidebarController.js:253:40"}]
```

**Comment by coditva** [comment]
@alxtr1bal Thanks for the info! This helped a lot. We're working on fixing this asap.

**Comment by coditva** [comment]
@alxtr1bal We've fixed this issue in the latest Postman Canary `v8.0.0-canary07`. Can you please try it out and confirm if it's fixed for you?

**Comment by alxtr1bal** [comment]
> 
> 
> @alxtr1bal We've fixed this issue in the latest Postman Canary `v8.0.0-canary07`. Can you please try it out and confirm if it's fixed for you?

@coditva Confirmed working now, thank you.
